### ISSUE TITLE
Importing from URL does not work, importing the source from the same URL does work

### ISSUE THREAD

**Issue by yavuzaydin** [TandoorRecipes/recipes#1021]
### Version
Version: 1.0.0

### Information
Exact URL you are trying to import from:
https://www.ah.nl/allerhande/recept/R-R853514/witlof-met-peer-en-blauwaderkaas

When did the issue happen: When pressing the search button with the url

Response/Message shown 
```
There was an error loading a resource! 500 Internal Server Error
```

### Extra information:
```
version: "3"
services:
  db_recipes:
    restart: always
    image: postgres:11-alpine
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - ./.env

  web_recipes:
    image: vabene1111/recipes
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./staticfiles:/opt/recipes/staticfiles
      - ./mediafiles:/opt/recipes/mediafiles
    ports:
      - "9987:8080"
    depends_on:
      - db_recipes
```

I'm running a nginx reverse proxy in front of it. Nginx is installed on the host system.

Nginx config:
```
server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  location / {
    #proxy_pass http://127.0.0.1:9986;
    proxy_pass http://127.0.0.1:9987;
    proxy_set_header Host $http_host;
    proxy_http_version 1.1;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
```

Error shown in logs:
```
  File "/opt/recipes/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/opt/recipes/venv/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/opt/recipes/venv/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fabe5dacd90>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/recipes/venv/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/recipes/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/opt/recipes/venv/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.ah.nl', port=443): Max retries exceeded with url: /allerhande/recept/R-R853514/witlof-met-peer-en-blauwaderkaas (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fabe5dacd90>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/recipes/cookbook/views/api.py", line 839, in recipe_from_source
    scrape = scrape_me(url, wild_mode=True)
  File "/opt/recipes/venv/lib/python3.9/site-packages/recipe_scrapers/__init__.py", line 353, in scrape_me
    wild_scraper = SchemaScraperFactory.generate(url_path, **options)
  File "/opt/recipes/venv/lib/python3.9/site-packages/recipe_scrapers/_factory.py", line 48, in generate
    return cls.SchemaScraper(url, **options)
  File "/opt/recipes/venv/lib/python3.9/site-packages/recipe_scrapers/_abstract.py", line 33, in __init__
    page_data = requests.get(
  File "/opt/recipes/venv/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/recipes/venv/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/recipes/venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/recipes/venv/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/opt/recipes/venv/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.ah.nl', port=443): Max retries exceeded with url: /allerhande/recept/R-R853514/witlof-met-peer-en-blauwaderkaas (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fabe5dacd90>: Failed to establish a new connection: [Errno -3] Try again'))
```

I can run `wget https://www.ah.nl/allerhande/recept/R-R853514/witlof-met-peer-en-blauwaderkaas` perfectly fine on console.

**Comment by smilerz** [comment]
can you try this again?  I was able to successfully import from that URL

**Comment by yavuzaydin** [comment]
Tried again, still the same. Importing from URL shows same error, if I import the source it is imported correctly.

**Comment by vabene1111** [comment]
What system are you hosting your server at? Is it in a data center or a public network that might be blocked by the requesting server.

Did you execute wget on the same machine that runs tandoor?

**Comment by yavuzaydin** [comment]
> Is it in a data center or a public network that might be blocked by the requesting server.

Datacenter.

> Did you execute wget on the same machine that runs tandoor?

I tested wget from the same server on the URL and it works. Also importing in Tandoor from other URL's doesn't seem to work on my system. I tried lots of URL's.

Come to think of it: I do have both a public IPv4 and a public IPv6. But it seems like www.ah.nl is IPv4 only:
```
wget --inet6-only https://www.ah.nl/allerhande/recept/R-R853514/witlof-met-peer-en-blauwaderkaas
--2021-11-05 14:51:31--  https://www.ah.nl/allerhande/recept/R-R853514/witlof-met-peer-en-blauwaderkaas
Resolving www.ah.nl (www.ah.nl)... failed: Name or service not known.
wget: unable to resolve host address ‘www.ah.nl’
```

How do we proceed on debugging this?

**Comment by vabene1111** [comment]
Hmm that is a case that is new to me. You seem to be familiar with the shell a little so you might be able to execute into the container, activate the virtual environment launch an interactive python shell and use requests.get() on some page that will return you the ip Adress making the request. This way you will know which external interface the container uses.

I am on my mobile so can't write you the code right now, if you don't know how to do this I can help you on Sunday. There are also likely other ways to find out what ip is used but I don't know how they work so can't really help you here, at least from my phone.

**Comment by yavuzaydin** [comment]
OK, it seems this was an error with my firewall blocking requests going out from a bridged network. This has been resolved on my setup, this is not a bug.
