### ISSUE TITLE
Docker upgrade from 0.16.8 to 1.1.0 fails on keyword migration

### ISSUE THREAD

**Issue by jens108** [TandoorRecipes/recipes#1075]
Hi there! I am creating a new issues as requested in https://github.com/TandoorRecipes/recipes/issues/1070#issuecomment-968615808

### Version
0.16.8  -> 1.1.0
I have a docker setup, so I am pretty much just doing a rebase of https://hub.docker.com/r/vabene1111/recipes

### Bug description
I'm trying to update from 0.16.8 to 1.1.0 but something goes wrong with the migration of the keywords. I have a theory that it might be because I have emojis in my keywords??

```
Updating database
Operations to perform:
  Apply all migrations: account, admin, auth, authtoken, contenttypes, cookbook, sessions, sites, socialaccount
Running migrations:
  Applying cookbook.0147_keyword_to_tree...js-reverse file written to /opt/recipes/cookbook/static/django_js_reverse

1019 static files copied to '/opt/recipes/staticfiles', 2939 post-processed.
Done
Traceback (most recent call last):
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.ObjectInUse: cannot ALTER TABLE "cookbook_keyword" because it has pending trigger events


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/recipes/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/operations/fields.py", line 244, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 608, in alter_field
    self._alter_field(model, old_field, new_field, old_type, new_type,
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/postgresql/schema.py", line 196, in _alter_field
    super()._alter_field(
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 800, in _alter_field
    self.execute(self._create_unique_sql(model, [new_field.column]))
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 145, in execute
    cursor.execute(sql, params)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.OperationalError: cannot ALTER TABLE "cookbook_keyword" because it has pending trigger events

[2021-11-14 20:10:52 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2021-11-14 20:10:52 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2021-11-14 20:10:52 +0000] [1] [INFO] Using worker: sync
[2021-11-14 20:10:52 +0000] [11] [INFO] Booting worker with pid: 11
```

**Comment by vabene1111** [comment]
Ok sorry for taking so long to answer. 

I never had the issue you posted about before but from what a quick search shows it might be related to something still locking the keyword table while django is already trying to run the migration. If this were a new update i would suspect the migration is broken but since the migration has been out for month and thousands of people have run them i think its something particular to your setup.

Can you make sure to properly down all containers including the database and then bring up the app/database from a fresh start ? Are you having any other applications or services that might access the DB and could impose a lock somewhere ?

**Comment by jens108** [comment]
Hi @vabene1111 , thank you for your reply. You didn't take long to answer.
I have stopped everything and tried to reapply the update again. This time, I got a different error.

It's the docker container from dockerhub and a standard database. There really is nothing I can think of about the setup I can change, because the docker container is out of my control and the database is just a database with default values I never tempered with.

```
Updating database
Operations to perform:
  Apply all migrations: account, admin, auth, authtoken, contenttypes, cookbook, sessions, sites, socialaccount
Running migrations:
  Applying cookbook.0139_space_created_at...js-reverse file written to /opt/recipes/cookbook/static/django_js_reverse

1019 static files copied to '/opt/recipes/staticfiles', 2939 post-processed.
Done
172.17.0.1 - - [17/Nov/2021:10:48:50 +0100] "GET / HTTP/1.0" 500 145 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
172.17.0.1 - - [17/Nov/2021:10:48:50 +0100] "GET /favicon.ico HTTP/1.0" 500 145 "https://eat.jensbahr.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
172.17.0.1 - - [17/Nov/2021:10:48:52 +0100] "GET /service-worker.js HTTP/1.0" 500 145 "https://eat.jensbahr.com/service-worker.js" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
172.17.0.1 - - [17/Nov/2021:10:48:54 +0100] "GET / HTTP/1.0" 302 0 "-" "Chrome/54.0 (Windows NT 10.0)"
172.17.0.1 - - [17/Nov/2021:10:48:55 +0100] "GET /search/ HTTP/1.0" 302 0 "https://eat.jensbahr.com" "Chrome/54.0 (Windows NT 10.0)"
Updating database
Operations to perform:
  Apply all migrations: account, admin, auth, authtoken, contenttypes, cookbook, sessions, sites, socialaccount
Running migrations:
  Applying cookbook.0139_space_created_at...js-reverse file written to /opt/recipes/cookbook/static/django_js_reverse

1 static file copied to '/opt/recipes/staticfiles', 1018 unmodified, 1981 post-processed.
Done
172.17.0.1 - - [17/Nov/2021:10:49:12 +0100] "GET / HTTP/1.0" 500 145 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
172.17.0.1 - - [17/Nov/2021:10:49:12 +0100] "GET /favicon.ico HTTP/1.0" 500 145 "https://eat.jensbahr.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
172.17.0.1 - - [17/Nov/2021:10:49:14 +0100] "GET /service-worker.js HTTP/1.0" 500 145 "https://eat.jensbahr.com/service-worker.js" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
Traceback (most recent call last):
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.DuplicateColumn: column "created_at" of relation "cookbook_space" already exists


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/recipes/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/operations/fields.py", line 104, in database_forwards
    schema_editor.add_field(
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 522, in add_field
    self.execute(sql, params)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 145, in execute
    cursor.execute(sql, params)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "created_at" of relation "cookbook_space" already exists

[2021-11-17 09:48:43 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2021-11-17 09:48:43 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2021-11-17 09:48:43 +0000] [1] [INFO] Using worker: sync
[2021-11-17 09:48:43 +0000] [11] [INFO] Booting worker with pid: 11
[2021-11-17 09:48:56 +0000] [1] [INFO] Handling signal: term
[2021-11-17 10:48:56 +0100] [11] [INFO] Worker exiting (pid: 11)
[2021-11-17 09:48:57 +0000] [1] [INFO] Shutting down: Master
Traceback (most recent call last):
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.DuplicateColumn: column "created_at" of relation "cookbook_space" already exists


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/recipes/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/operations/fields.py", line 104, in database_forwards
    schema_editor.add_field(
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 522, in add_field
    self.execute(sql, params)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 145, in execute
    cursor.execute(sql, params)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "created_at" of relation "cookbook_space" already exists

[2021-11-17 09:49:05 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2021-11-17 09:49:05 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2021-11-17 09:49:05 +0000] [1] [INFO] Using worker: sync
[2021-11-17 09:49:05 +0000] [12] [INFO] Booting worker with pid: 12

```

**Comment by vabene1111** [comment]
this looks very strange, i have never seen this issue before but my best guess would be that for some reason, even tough migrations should always run trough either completely or not, your last attempt of migrating created some columns but not all and thus left your database in an inconsistent stage. 

I am not sure if this helps but i would do the following 
1. dump the whole database as a backup!!!
2. dump all data from the database (but not the structure, only inserts).
3. delete the database (or spin up a second one)
4. start the containers with tandoor version 0.16.8 (by adding that to the docker compose image `vabene111/recipes:0.16.8`)
5. this will run all migrations to that point cleanly
6. import the data you dumped in step 2
7. down the container, remove `0.16.8` from the docker compose, pull the latest image and start again

This should basically act as a clean migration from 0.16.8 to 1.X. I hope this works, if not let me know and i will see what i can do

**Comment by jens108** [comment]
I followed your instructions! This time I got this error. It's always a different one it seems!

```
Updating database
Operations to perform:
  Apply all migrations: account, admin, auth, authtoken, contenttypes, cookbook, sessions, sites, socialaccount
Running migrations:
  Applying cookbook.0143_build_full_text_index...js-reverse file written to /opt/recipes/cookbook/static/django_js_reverse

1019 static files copied to '/opt/recipes/staticfiles', 2939 post-processed.
Done
172.17.0.1 - - [18/Nov/2021:17:11:31 +0100] "GET / HTTP/1.0" 500 145 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
172.17.0.1 - - [18/Nov/2021:17:11:31 +0100] "GET /favicon.ico HTTP/1.0" 500 145 "https://eat.jensbahr.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
172.17.0.1 - - [18/Nov/2021:17:11:33 +0100] "GET / HTTP/1.0" 500 145 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
172.17.0.1 - - [18/Nov/2021:17:11:33 +0100] "GET /favicon.ico HTTP/1.0" 500 145 "https://eat.jensbahr.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
172.17.0.1 - - [18/Nov/2021:17:11:33 +0100] "GET /service-worker.js HTTP/1.0" 500 145 "https://eat.jensbahr.com/service-worker.js" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
172.17.0.1 - - [18/Nov/2021:17:11:35 +0100] "GET /service-worker.js HTTP/1.0" 500 145 "https://eat.jensbahr.com/service-worker.js" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36"
Traceback (most recent call last):
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedFunction: function unaccent(character varying) does not exist
LINE 1: ...tweight(to_tsvector('simple'::regconfig, COALESCE(UNACCENT("...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/recipes/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 244, in handle
    post_migrate_state = executor.migrate(
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/opt/recipes/cookbook/migrations/0143_build_full_text_index.py", line 21, in set_default_search_vector
    Recipe.objects.all().update(
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/models/query.py", line 783, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1559, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: function unaccent(character varying) does not exist
LINE 1: ...tweight(to_tsvector('simple'::regconfig, COALESCE(UNACCENT("...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

[2021-11-18 16:11:21 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2021-11-18 16:11:21 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2021-11-18 16:11:21 +0000] [1] [INFO] Using worker: sync
[2021-11-18 16:11:21 +0000] [11] [INFO] Booting worker with pid: 11
```

**Comment by jens108** [comment]
This did not work, sadly. I have also tried cleaning up the table cookbook_keywords manually, and then even tried truncating it. Not the same error appears for the table "cookbook_food".

**Comment by jens108** [comment]
I only had 6 recipes in the DB, and the update has now taken longer than just creating a new database and pasting them in again. So I deleted the database and created a new installation with version 1.1.0. Let's hope it keeps working! :-)

**Comment by vabene1111** [comment]
very interesting, glad you got it working but would have loved to understand what whats causing this. Let me know if you need any help in the future
