### ISSUE TITLE
Migrations error and webpack-stats.json file missing after fresh install

### ISSUE THREAD

**Issue by deldelu** [TandoorRecipes/recipes#1209]
### Version

Version:  1.0.4 (Docker)

### Bug description

I used the original `Dockerfile` to install the application.

#### Migrations error

The application tell to run the command `manage.py makemigrations` in the log after the fresh install:

```
recipes-app  | Updating database
recipes-app  | Operations to perform:
recipes-app  |   Apply all migrations: account, admin, auth, authtoken, contenttypes, cookbook, sessions, sites, socialaccount
recipes-app  | Running migrations:
recipes-app  |   No migrations to apply.
recipes-app  |   Your models in app(s): 'cookbook' have changes that are not yet reflected in a migration, and so won't be applied.
recipes-app  |   Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```

Maybe this command could be integrated in the `boot.sh` file.

#### webpack-stats.json file missing

Moreover, after a fresh install and admin account configuration, the application return the following error on some pages like **/search/**:

```
recipes-app  | Internal Server Error: /search/
recipes-app  | Traceback (most recent call last):
recipes-app  |   File "/opt/recipes/venv/lib/python3.9/site-packages/webpack_loader/loader.py", line 26, in load_assets
recipes-app  |     with open(self.config['STATS_FILE'], encoding="utf-8") as f:
recipes-app  | FileNotFoundError: [Errno 2] No such file or directory: '/opt/recipes/vue/webpack-stats.json'
recipes-app  |
recipes-app  | During handling of the above exception, another exception occurred:
recipes-app  |
recipes-app  | Traceback (most recent call last):
recipes-app  |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
recipes-app  |     response = get_response(request)
recipes-app  |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
recipes-app  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
recipes-app  |   File "/opt/recipes/cookbook/views/views.py", line 61, in search
recipes-app  |     return search_v2(request)
recipes-app  |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
recipes-app  |     return view_func(request, *args, **kwargs)
recipes-app  |   File "/opt/recipes/cookbook/views/views.py", line 96, in search_v2
recipes-app  |     return render(request, 'search.html', {})
recipes-app  |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/shortcuts.py", line 19, in render
recipes-app  |     content = loader.render_to_string(template_name, context, request, using=using)
recipes-app  |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
recipes-app  |     return template.render(context, request)
recipes-app  |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
recipes-app  |     return self.template.render(context)
recipes-app  |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/template/base.py", line 170, in render
recipes-app  |     return self._render(context)
recipes-app  |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
recipes-app  |     return self.nodelist.render(context)
recipes-app  |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
recipes-app  |     bit = node.render_annotated(context)
recipes-app  |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
recipes-app  |     return self.render(context)
recipes-app  |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render
recipes-app  |     return compiled_parent._render(context)
recipes-app  |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
recipes-app  |     return self.nodelist.render(context)
recipes-app  |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
recipes-app  |     bit = node.render_annotated(context)
recipes-app  |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
recipes-app  |     return self.render(context)
recipes-app  |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 62, in render
recipes-app  |     result = block.nodelist.render(context)
recipes-app  |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
recipes-app  |     bit = node.render_annotated(context)
recipes-app  |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
recipes-app  |     return self.render(context)
recipes-app  |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/template/library.py", line 192, in render
recipes-app  |     output = self.func(*resolved_args, **resolved_kwargs)
recipes-app  |   File "/opt/recipes/venv/lib/python3.9/site-packages/webpack_loader/templatetags/webpack_loader.py", line 20, in render_bundle
recipes-app  |     tags = utils.get_as_tags(
recipes-app  |   File "/opt/recipes/venv/lib/python3.9/site-packages/webpack_loader/utils.py", line 61, in get_as_tags
recipes-app  |     bundle = _get_bundle(bundle_name, extension, config)
recipes-app  |   File "/opt/recipes/venv/lib/python3.9/site-packages/webpack_loader/utils.py", line 39, in _get_bundle
recipes-app  |     bundle = get_loader(config).get_bundle(bundle_name)
recipes-app  |   File "/opt/recipes/venv/lib/python3.9/site-packages/webpack_loader/loader.py", line 72, in get_bundle
recipes-app  |     assets = self.get_assets()
recipes-app  |   File "/opt/recipes/venv/lib/python3.9/site-packages/webpack_loader/loader.py", line 39, in get_assets
recipes-app  |     return self.load_assets()
recipes-app  |   File "/opt/recipes/venv/lib/python3.9/site-packages/webpack_loader/loader.py", line 29, in load_assets
recipes-app  |     raise IOError(
recipes-app  | OSError: Error reading /opt/recipes/vue/webpack-stats.json. Are you sure webpack has generated the file and the path is correct?
recipes-app  | 172.19.0.3 - - [02/Jan/2022:17:46:39 +0100] "GET /search/ HTTP/1.0" 500 186212 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"
recipes-app  | Not Found: /favicon.ico
```

I thing the yarn installation step missing in the Dockerfile. I could resolve the issue with the following commands in the container:

```sh
apk add yarn
yarn cache clean --all
yarn install
yarn build
```

These commands may be integrate in the `Dockerfile`.

Don't hesite to ask me if you need more information.

**Comment by vabene1111** [comment]
i think the manual install contains this step, as for manually building the docker file there are no instructions as i dont intend to support this as an offical method of installation. The workflow that build the docker image via the CI works so basically just replicate that and your build should work as well.
