### ISSUE TITLE
Keyword error recipe export

### ISSUE THREAD

**Issue by Korndaweizen** [TandoorRecipes/recipes#1213]
### Version
Version: 1.0.4

### Bug description
Hi there! Unfortunately I cannot export any of my recipes. The following error occurrs:

```
Environment:

Request Method: POST
Request URL: https://myurl.pw/export/

Django Version: 3.2.10
Python Version: 3.9.5
Installed Applications:
['dal',
 'dal_select2',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'django.contrib.postgres',
 'django_prometheus',
 'django_tables2',
 'corsheaders',
 'django_filters',
 'crispy_forms',
 'rest_framework',
 'rest_framework.authtoken',
 'django_cleanup.apps.CleanupConfig',
 'webpack_loader',
 'django_js_reverse',
 'hcaptcha',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'cookbook.apps.CookbookConfig',
 'treebeard']
Installed Middleware:
['corsheaders.middleware.CorsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'cookbook.helper.scope_middleware.ScopeMiddleware',
 'recipes.middleware.SqlPrintingMiddleware',
 'recipes.middleware.CustomRemoteUser']



Traceback (most recent call last):
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/recipes/venv/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/recipes/cookbook/views/import_export.py", line 121, in export_recipe
    integration = get_integration(request, form.cleaned_data['type'])
  File "/opt/recipes/cookbook/views/import_export.py", line 36, in get_integration
    return Default(request, export_type)
  File "/opt/recipes/cookbook/integration/integration.py", line 44, in __init__
    name = f'Import {int(last_kw.name.replace("Import ", "")) + 1}'

Exception Type: ValueError at /export/
Exception Value: invalid literal for int() with base 10: '2. April 2021 10:39.38'
```

**Comment by Korndaweizen** [comment]
I justed fixed this issue by editing the keyword via the admin mode. Still, this may be an issue for non-devs

**Comment by vabene1111** [comment]
ah i hate this stupid keyword thing. one would think its so stupidly easy but for some reason we keep messing things up 😂 i will review it and try to add a fix, i think we have always focused on import in the past so export might not have been reviewed properly
