### ISSUE TITLE
Manual Installation on Raspberry Pi 3B: gunicorn_recipes.service failed (ModuleNotFoundError: No module named 'recipes')

### ISSUE THREAD

**Issue by jmtw35** [TandoorRecipes/recipes#1223]
### Version

Version: 1.0.4

### Bug description

When manually setting up Tandoor on the Raspberry Pi 3B (Raspbian GNU/Linux 11 (bullseye)), gunicorn_recipes.service failed with result 'exit-code'.

Here is the output from /tmp/gunicorn_err.log:

```
[2022-01-04 12:27:52 +0000] [7062] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['unix:/var/www/recipes/recipes.sock']
  backlog: 2048
  workers: 1
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /var/www/recipes
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1001
  group: 33
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /tmp/gunicorn_err.log
  loglevel: debug
  capture_output: True
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: recipes.wsgi:application
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x75e5e850>
  on_reload: <function OnReload.on_reload at 0x75e5e8e0>
  when_ready: <function WhenReady.when_ready at 0x75e5e970>
  pre_fork: <function Prefork.pre_fork at 0x75e5ea48>
  post_fork: <function Postfork.post_fork at 0x75e5ead8>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x75e5ebb0>
  worker_int: <function WorkerInt.worker_int at 0x75e5ec40>
  worker_abort: <function WorkerAbort.worker_abort at 0x75e5ecd0>
  pre_exec: <function PreExec.pre_exec at 0x75e5ed60>
  pre_request: <function PreRequest.pre_request at 0x75e5edf0>
  post_request: <function PostRequest.post_request at 0x75e5ee38>
  child_exit: <function ChildExit.child_exit at 0x75e5ef10>
  worker_exit: <function WorkerExit.worker_exit at 0x75e5efa0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x75e00070>
  on_exit: <function OnExit.on_exit at 0x75e00100>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2022-01-04 12:27:52 +0000] [7062] [INFO] Starting gunicorn 20.1.0
[2022-01-04 12:27:52 +0000] [7062] [DEBUG] Arbiter booted
[2022-01-04 12:27:52 +0000] [7062] [INFO] Listening at: unix:/var/www/recipes/recipes.sock (7062)
[2022-01-04 12:27:52 +0000] [7062] [INFO] Using worker: sync
[2022-01-04 12:27:52 +0000] [7063] [INFO] Booting worker with pid: 7063
[2022-01-04 12:27:52 +0000] [7063] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/var/www/recipes/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/var/www/recipes/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/var/www/recipes/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/var/www/recipes/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/var/www/recipes/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/var/www/recipes/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/var/www/recipes/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'recipes'
[2022-01-04 12:27:52 +0000] [7063] [INFO] Worker exiting (pid: 7063)
[2022-01-04 12:27:52 +0000] [7062] [DEBUG] 1 workers
[2022-01-04 12:27:52 +0000] [7062] [INFO] Shutting down: Master
[2022-01-04 12:27:52 +0000] [7062] [INFO] Reason: Worker failed to boot.
```

**Comment by vabene1111** [comment]
since this is just a gunicorn error without any other information about your setup and the log does not include anything that i can trace back to the application i cannot help you. I also sadly do not have the time to offer support for all setup methods. Generally speaking this looks like gunicorn is not pointed to the right place or does not load the correct environment but i have no idea, its been several years since i last manually installed a django application with gunicorn, sorry.

maybe someone from the community can help if you post more information and post this issue on our discord.
