### ISSUE TITLE
Broken after Latest Update

### ISSUE THREAD

**Issue by wkelton** [TandoorRecipes/recipes#1407]
### Tandoor Version

1.0.5

### Setup

Docker / Docker-Compose

### Reverse Proxy

jwilder's nginx proxy

### Bug description

After updating to latest release, site did not come back up. Looking at the logs, it appears that perhaps db upgrades failed?

Running postgres as db and here is part of it's log:
```
today at 10:08:45 PM2022-01-25 04:08:45.969 UTC [27] ERROR:  column cookbook_space.show_facet_count does not exist at character 310
today at 10:08:45 PM2022-01-25 04:08:45.969 UTC [27] STATEMENT:  SELECT "cookbook_space"."id", "cookbook_space"."name", "cookbook_space"."created_by_id", "cookbook_space"."created_at", "cookbook_space"."message", "cookbook_space"."max_recipes", "cookbook_space"."max_file_storage_mb", "cookbook_space"."max_users", "cookbook_space"."allow_sharing", "cookbook_space"."demo", "cookbook_space"."show_facet_count" FROM "cookbook_space" WHERE "cookbook_space"."id" = 1 LIMIT 21
today at 10:08:59 PM2022-01-25 04:08:59.971 UTC [30] ERROR:  column cookbook_userpreference.mealplan_autoadd_shopping does not exist at character 543
today at 10:08:59 PM2022-01-25 04:08:59.971 UTC [30] STATEMENT:  SELECT "cookbook_userpreference"."user_id", "cookbook_userpreference"."theme", "cookbook_userpreference"."nav_color", "cookbook_userpreference"."default_unit", "cookbook_userpreference"."use_fractions", "cookbook_userpreference"."use_kj", "cookbook_userpreference"."default_page", "cookbook_userpreference"."search_style", "cookbook_userpreference"."show_recent", "cookbook_userpreference"."ingredient_decimals", "cookbook_userpreference"."comments", "cookbook_userpreference"."shopping_auto_sync", "cookbook_userpreference"."sticky_navbar", "cookbook_userpreference"."mealplan_autoadd_shopping", "cookbook_userpreference"."mealplan_autoexclude_onhand", "cookbook_userpreference"."mealplan_autoinclude_related", "cookbook_userpreference"."shopping_add_onhand", "cookbook_userpreference"."filter_to_supermarket", "cookbook_userpreference"."left_handed", "cookbook_userpreference"."default_delay", "cookbook_userpreference"."shopping_recent_days", "cookbook_userpreference"."csv_delim", "cookbook_userpreference"."csv_prefix", "cookbook_userpreference"."created_at", "cookbook_userpreference"."space_id" FROM "cookbook_userpreference" WHERE "cookbook_userpreference"."user_id" = 1 LIMIT 21
```

See log below for callstacks thrown in the recipes container.

### Relevant logs

```shell
recipes container:

today at 10:08:43 PMUpdating database
today at 10:08:44 PMOperations to perform:
today at 10:08:44 PM  Apply all migrations: account, admin, auth, authtoken, contenttypes, cookbook, sessions, sites, socialaccount
today at 10:08:44 PMRunning migrations:
today at 10:08:45 PMTraceback (most recent call last):
today at 10:08:45 PM  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 173, in __get__
today at 10:08:45 PM    rel_obj = self.field.get_cached_value(instance)
today at 10:08:45 PM  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/models/fields/mixins.py", line 15, in get_cached_value
today at 10:08:45 PM    return instance._state.fields_cache[cache_name]
today at 10:08:45 PMKeyError: 'space'
today at 10:08:45 PM
today at 10:08:45 PMDuring handling of the above exception, another exception occurred:
today at 10:08:45 PM
today at 10:08:45 PMTraceback (most recent call last):
today at 10:08:45 PM  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
today at 10:08:45 PM    return self.cursor.execute(sql, params)
today at 10:08:45 PMpsycopg2.errors.UndefinedColumn: column cookbook_space.show_facet_count does not exist
today at 10:08:45 PMLINE 1: ..._space"."allow_sharing", "cookbook_space"."demo", "cookbook_...
today at 10:08:45 PM                                                             ^
today at 10:08:45 PM
today at 10:08:45 PM
today at 10:08:45 PMThe above exception was the direct cause of the following exception:
today at 10:08:45 PM
today at 10:08:45 PMTraceback (most recent call last):
today at 10:08:45 PM  File "/opt/recipes/manage.py", line 15, in <module>
today at 10:08:45 PM    execute_from_command_line(sys.argv)
today at 10:08:45 PM  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
today at 10:08:45 PM    utility.execute()
today at 10:08:45 PM  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
today at 10:08:45 PM    self.fetch_command(subcommand).run_from_argv(self.argv)
today at 10:08:45 PM  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
today at 10:08:45 PM    self.execute(*args, **cmd_options)
today at 10:08:45 PM  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
today at 10:08:45 PM    output = self.handle(*args, **options)
today at 10:08:45 PM  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/base.py", line 89, in wrapped
today at 10:08:45 PM    res = handle_func(*args, **kwargs)
today at 10:08:45 PM  File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 244, in handle
today at 10:08:45 PM    post_migrate_state = executor.migrate(
today at 10:08:45 PM  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/executor.py", line 117, in migrate
today at 10:08:45 PM    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
today at 10:08:45 PM  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
today at 10:08:45 PM    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
today at 10:08:45 PM  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/executor.py", line 227, in apply_migration
today at 10:08:45 PM    state = migration.apply(state, schema_editor)
today at 10:08:45 PM  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/migration.py", line 126, in apply
today at 10:08:45 PM    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
today at 10:08:45 PM  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
today at 10:08:45 PM    self.code(from_state.apps, schema_editor)
today at 10:08:45 PM  File "/opt/recipes/cookbook/migrations/0159_add_shoppinglistentry_fields.py", line 18, in copy_values_to_sle
today at 10:08:45 PM    entry.space = entry.shoppinglist_set.first().space
today at 10:08:45 PM  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 187, in __get__
today at 10:08:45 PM    rel_obj = self.get_object(instance)
today at 10:08:45 PM  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/models/fields/related_descriptors.py", line 154, in get_object
today at 10:08:45 PM    return qs.get(self.field.get_reverse_related_filter(instance))
today at 10:08:45 PM  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/models/query.py", line 431, in get
today at 10:08:45 PM    num = len(clone)
today at 10:08:45 PM  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/models/query.py", line 262, in __len__
today at 10:08:45 PM    self._fetch_all()
today at 10:08:45 PM  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/models/query.py", line 1324, in _fetch_all
today at 10:08:45 PM    self._result_cache = list(self._iterable_class(self))
today at 10:08:45 PM  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/models/query.py", line 51, in __iter__
today at 10:08:45 PM    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
today at 10:08:45 PM  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
today at 10:08:45 PM    cursor.execute(sql, params)
today at 10:08:45 PM  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
today at 10:08:45 PM    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
today at 10:08:45 PM  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
today at 10:08:45 PM    return executor(sql, params, many, context)
today at 10:08:45 PM  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
today at 10:08:45 PM    return self.cursor.execute(sql, params)
today at 10:08:45 PM  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
today at 10:08:45 PM    raise dj_exc_value.with_traceback(traceback) from exc_value
today at 10:08:45 PM  File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
today at 10:08:45 PM    return self.cursor.execute(sql, params)
today at 10:08:45 PMdjango.db.utils.ProgrammingError: column cookbook_space.show_facet_count does not exist
today at 10:08:45 PMLINE 1: ..._space"."allow_sharing", "cookbook_space"."demo", "cookbook_...
```

**Comment by Athan1** [comment]
same with me.

**Comment by eikeschott** [comment]
Same logs here, page is showing `Server Error (500)`.

**Comment by ThomasDaheim** [comment]
I get

`2022-01-25 15:30:33.288 UTC [3005] ERROR:  column cookbook_userpreference.left_handed does not exist at character 813`

I can see errors like

`2022-01-25 14:41:25.878 UTC [2950] ERROR:  column "show_facet_count" of relation "cookbook_space" already exists` 

maybe some database upgrade that failed?

**Comment by ThomasDaheim** [comment]
> same issue, looks like its trying to add a dupe column in the db, if your error is that it already exists i fixed by doing the following, hope it helps you lot:
> 
> exec into container and then edit this file:
> 
> `vi cookbook/migrations/0164_space_show_facet_count.py `
> 
> comment out the operations bit as such:
> 
> ```
>     operations = [
> #        migrations.AddField(
> #            model_name='space',
> #            name='show_facet_count',
> #            field=models.BooleanField(default=False),
> #        ),
>     ]
> ```
> 
> and then run migrate again
> 
> ```
> source venv/bin/activate
> python manage.py migrate
> ```
> 
> followed by a restart

No sure how I could achieve that for my running docker container?

**Comment by smilerz** [comment]
fixed with 1.0.5.2

**Comment by fabiopbx** [comment]
also looks like v1.0.5.2 has the same fix but seems docker still has v1.0.5.1

https://github.com/TandoorRecipes/recipes/blob/1.0.5.2/cookbook/migrations/0164_space_show_facet_count.py

**Comment by smilerz** [comment]
> also looks like v1.0.5.2 has the same fix but seems docker still has v1.0.5.1
> 
> https://github.com/TandoorRecipes/recipes/blob/1.0.5.2/cookbook/migrations/0164_space_show_facet_count.py

it's building now

**Comment by smilerz** [comment]
notification will also go out [here](https://discord.com/channels/890556779023466497/890576241449631775) when the build is complete

**Comment by wkelton** [comment]
Confirmed latest fixes this issue for me.
