### ISSUE TITLE
Default-Setup doesn't work, when changing volumes

### ISSUE THREAD

**Issue by GeraldVonRiva** [TandoorRecipes/recipes#1415]
### Issue

I am using the default docker-compose-plain-setup (https://github.com/TandoorRecipes/recipes/tree/develop/docs/install/docker/plain), just modifying the volume location.
The default setup uses the docker-volumes "nginx_config" and "staticfiles". Also it creates the volumes "postgresql" and "mediafiles" in local directories.

I want to change this, so the volumes all are placed in full path defined location.

If I use the default-setup without any modification, it works (waiting about 5 Minutes after containerstart before it is accessible). If I use custom locations for the volumes, Port 80 only got open on 127.0.0.1, not on the "normal" network. Also on 127.0.0.1 I can't open the side, even after Waiting for more then 10 minutes.

> pi@Tandoor:~/docker/TandoorRecipes $ nmap 127.0.0.1
Starting Nmap 7.80 ( https://nmap.org ) at 2022-01-26 12:50 CET
Nmap scan report for localhost (127.0.0.1)
Host is up (0.0012s latency).
Not shown: 998 closed ports
PORT   STATE SERVICE
22/tcp open  ssh
80/tcp open  http

>Nmap done: 1 IP address (1 host up) scanned in 0.43 seconds
pi@Tandoor:~/docker/TandoorRecipes $ wget 127.0.0.1
--2022-01-26 12:50:46--  http://127.0.0.1/
Verbindungsaufbau zu 127.0.0.1 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … Lesefehler (Die Verbindung wurde vom Kommunikationspartner zurückgesetzt) beim Vorspann (header).
Erneuter Versuch.

>pi@Tandoor:~/docker/TandoorRecipes $ nmap 192.168.198.63
Starting Nmap 7.80 ( https://nmap.org ) at 2022-01-26 12:50 CET
Nmap scan report for PiNAS.fritz.box (192.168.198.63)
Host is up (0.0014s latency).
Not shown: 999 closed ports
PORT   STATE SERVICE
22/tcp open  ssh

### Tandoor Version

1.0.5

### OS Version

Pi OS (64 bit)

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Environment file

```shell
# only set this to true when testing/debugging
# when unset: 1 (true) - dont unset this, just for development
DEBUG=0
SQL_DEBUG=0

# hosts the application can run under e.g. recipes.mydomain.com,cooking.mydomain.com,...
ALLOWED_HOSTS=*

# random secret key, use for example `base64 /dev/urandom | head -c50` to generate one
# ---------------------------- REQUIRED -------------------------
SECRET_KEY=...
# ---------------------------------------------------------------

# your default timezone See https://timezonedb.com/time-zones for a list of timezones
TIMEZONE=Europe/Berlin

# add only a database password if you want to run with the default postgres, otherwise change settings accordingly
DB_ENGINE=django.db.backends.postgresql
# DB_OPTIONS= {} # e.g. {"sslmode":"require"} to enable ssl
POSTGRES_HOST=db_recipes
POSTGRES_PORT=5432
POSTGRES_USER=djangouser
# ---------------------------- REQUIRED -------------------------
POSTGRES_PASSWORD=...
# ---------------------------------------------------------------
POSTGRES_DB=djangodb

# the default value for the user preference 'fractions' (enable/disable fraction support)
# default: disabled=0
FRACTION_PREF_DEFAULT=0

# the default value for the user preference 'comments' (enable/disable commenting system)
# default comments enabled=1
COMMENT_PREF_DEFAULT=1

# Users can set a amount of time after which the shopping list is refreshed when they are in viewing mode
# This is the minimum interval users can set. Setting this to low will allow users to refresh very frequently which
# might cause high load on the server. (Technically they can obviously refresh as often as they want with their own scripts)
SHOPPING_MIN_AUTOSYNC_INTERVAL=5


# Serve mediafiles directly using gunicorn. Basically everyone recommends not doing this. Please use any of the examples
# provided that include an additional nxginx container to handle media file serving.
# If you know what you are doing turn this back on (1) to serve media files using djangos serve() method.
# when unset: 1 (true) - this is temporary until an appropriate amount of time has passed for everyone to migrate
GUNICORN_MEDIA=0

# allow authentication via reverse proxy (e.g. authelia), leave off if you dont know what you are doing
# see docs for more information https://vabene1111.github.io/recipes/features/authentication/
# when unset: 0 (false)
REVERSE_PROXY_AUTH=0

# Enables exporting PDF (see export docs)
# Disabled by default, unc
```

### Docker-Compose file

```shell
version: "3"
services:
  db_recipes:
    restart: always
    image: postgres:11-alpine
    volumes:
      - /home/pi/docker/TandoorRecipes/volumes/postgresql:/var/lib/postgresql/data
    env_file:
      - ./.env

  web_recipes:
    image: vabene1111/recipes
    restart: always
    env_file:
      - ./.env
    volumes:
      - /home/pi/docker/TandoorRecipes/volumes/staticfiles:/opt/recipes/staticfiles
      - /home/pi/docker/TandoorRecipes/volumes/nginx_config:/opt/recipes/nginx/conf.d
      - /home/pi/docker/TandoorRecipes/volumes/mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes

  nginx_recipes:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - 80:80
    env_file:
      - ./.env
    depends_on:
      - web_recipes
    volumes:
      - /home/pi/docker/TandoorRecipes/volumes/nginx_config:/etc/nginx/conf.d:ro
      - /home/pi/docker/TandoorRecipes/volumes/staticfiles:/static
      - /home/pi/docker/TandoorRecipes/volumes/mediafiles:/media
```

### Relevant logs

```shell
tandoorrecipes-web_recipes-1  | Updating database
tandoorrecipes-db_recipes-1   | The files belonging to this database system will be owned by user "postgres".
tandoorrecipes-db_recipes-1   | This user must also own the server process.
tandoorrecipes-db_recipes-1   | 
tandoorrecipes-db_recipes-1   | The database cluster will be initialized with locale "en_US.utf8".
tandoorrecipes-db_recipes-1   | The default database encoding has accordingly been set to "UTF8".
tandoorrecipes-db_recipes-1   | The default text search configuration will be set to "english".
tandoorrecipes-db_recipes-1   | 
tandoorrecipes-web_recipes-1  | Traceback (most recent call last):
tandoorrecipes-web_recipes-1  |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
tandoorrecipes-web_recipes-1  |     self.connect()
tandoorrecipes-web_recipes-1  |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
tandoorrecipes-web_recipes-1  |     return func(*args, **kwargs)
tandoorrecipes-web_recipes-1  |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
tandoorrecipes-web_recipes-1  |     self.connection = self.get_new_connection(conn_params)
tandoorrecipes-web_recipes-1  |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
tandoorrecipes-web_recipes-1  |     return func(*args, **kwargs)
tandoorrecipes-web_recipes-1  |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
tandoorrecipes-web_recipes-1  |     connection = Database.connect(**conn_params)
tandoorrecipes-web_recipes-1  |   File "/opt/recipes/venv/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
tandoorrecipes-web_recipes-1  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
tandoorrecipes-web_recipes-1  | psycopg2.OperationalError: could not connect to server: Connection refused
tandoorrecipes-web_recipes-1  | 	Is the server running on host "db_recipes" (172.23.0.2) and accepting
tandoorrecipes-web_recipes-1  | 	TCP/IP connections on port 5432?
tandoorrecipes-web_recipes-1  | 
tandoorrecipes-web_recipes-1  | 
tandoorrecipes-web_recipes-1  | The above exception was the direct cause of the following exception:
tandoorrecipes-db_recipes-1   | Data page checksums are disabled.
tandoorrecipes-db_recipes-1   | 
tandoorrecipes-db_recipes-1   | fixing permissions on existing directory /var/lib/postgresql/data ... ok
tandoorrecipes-db_recipes-1   | creating subdirectories ... ok
tandoorrecipes-db_recipes-1   | selecting default max_connections ... 100
tandoorrecipes-db_recipes-1   | selecting default shared_buffers ... 128MB
tandoorrecipes-db_recipes-1   | selecting default timezone ... UTC
tandoorrecipes-db_recipes-1   | selecting dynamic shared memory implementation ... posix
tandoorrecipes-db_recipes-1   | creating configuration files ... ok
tandoorrecipes-db_recipes-1   | running bootstrap script ... ok
tandoorrecipes-db_recipes-1   | sh: locale: not found
tandoorrecipes-db_recipes-1   | 2022-01-26 12:52:16.587 UTC [31] WARNING:  no usable system locales were found
tandoorrecipes-db_recipes-1   | performing post-bootstrap initialization ... ok
tandoorrecipes-web_recipes-1  | 
tandoorrecipes-web_recipes-1  | Traceback (most recent call last):
tandoorrecipes-web_recipes-1  |   File "/opt/recipes/manage.py", line 15, in <module>
tandoorrecipes-web_recipes-1  |     execute_from_command_line(sys.argv)
tandoorrecipes-web_recipes-1  |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
tandoorrecipes-web_recipes-1  |     utility.execute()
tandoorrecipes-web_recipes-1  |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
tandoorrecipes-web_recipes-1  |     django.setup()
tandoorrecipes-web_recipes-1  |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
tandoorrecipes-web_recipes-1  |     apps.populate(settings.INSTALLED_APPS)
tandoorrecipes-web_recipes-1  |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/apps/registry.py", line 122, in populate
tandoorrecipes-web_recipes-1  |     app_config.ready()
tandoorrecipes-web_recipes-1  |   File "/opt/recipes/venv/lib/python3.9/site-packages/django_prometheus/apps.py", line 24, in ready
tandoorrecipes-web_recipes-1  |     ExportMigrations()
tandoorrecipes-web_recipes-1  |   File "/opt/recipes/venv/lib/python3.9/site-packages/django_prometheus/migrations.py", line 52, in ExportMigrations
tandoorrecipes-web_recipes-1  |     executor = MigrationExecutor(connections[alias])
tandoorrecipes-web_recipes-1  |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/executor.py", line 18, in __init__
tandoorrecipes-web_recipes-1  |     self.loader = MigrationLoader(self.connection)
tandoorrecipes-web_recipes-1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/loader.py", line 53, in __init__
tandoorrecipes-nginx_recipes-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
tandoorrecipes-nginx_recipes-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
tandoorrecipes-nginx_recipes-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
tandoorrecipes-web_recipes-1    |     self.build_graph()
tandoorrecipes-web_recipes-1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/loader.py", line 220, in build_graph
tandoorrecipes-web_recipes-1    |     self.applied_migrations = recorder.applied_migrations()
tandoorrecipes-nginx_recipes-1  | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
tandoorrecipes-nginx_recipes-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
tandoorrecipes-nginx_recipes-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
tandoorrecipes-nginx_recipes-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
tandoorrecipes-nginx_recipes-1  | 2022/01/26 12:52:17 [notice] 1#1: using the "epoll" event method
tandoorrecipes-nginx_recipes-1  | 2022/01/26 12:52:17 [notice] 1#1: nginx/1.21.5
tandoorrecipes-nginx_recipes-1  | 2022/01/26 12:52:17 [notice] 1#1: built by gcc 10.3.1 20211027 (Alpine 10.3.1_git20211027) 
tandoorrecipes-nginx_recipes-1  | 2022/01/26 12:52:17 [notice] 1#1: OS: Linux 5.10.92-v8+
tandoorrecipes-nginx_recipes-1  | 2022/01/26 12:52:17 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
tandoorrecipes-nginx_recipes-1  | 2022/01/26 12:52:17 [notice] 1#1: start worker processes
tandoorrecipes-nginx_recipes-1  | 2022/01/26 12:52:17 [notice] 1#1: start worker process 23
tandoorrecipes-nginx_recipes-1  | 2022/01/26 12:52:17 [notice] 1#1: start worker process 24
tandoorrecipes-nginx_recipes-1  | 2022/01/26 12:52:17 [notice] 1#1: start worker process 25
tandoorrecipes-nginx_recipes-1  | 2022/01/26 12:52:17 [notice] 1#1: start worker process 26
tandoorrecipes-web_recipes-1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 77, in applied_migrations
tandoorrecipes-web_recipes-1    |     if self.has_table():
tandoorrecipes-web_recipes-1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 55, in has_table
tandoorrecipes-web_recipes-1    |     with self.connection.cursor() as cursor:
tandoorrecipes-web_recipes-1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
tandoorrecipes-web_recipes-1    |     return func(*args, **kwargs)
tandoorrecipes-web_recipes-1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 259, in cursor
tandoorrecipes-web_recipes-1    |     return self._cursor()
tandoorrecipes-web_recipes-1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 235, in _cursor
tandoorrecipes-web_recipes-1    |     self.ensure_connection()
tandoorrecipes-web_recipes-1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
tandoorrecipes-web_recipes-1    |     return func(*args, **kwargs)
tandoorrecipes-web_recipes-1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
tandoorrecipes-web_recipes-1    |     self.connect()
tandoorrecipes-web_recipes-1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
tandoorrecipes-web_recipes-1    |     raise dj_exc_value.with_traceback(traceback) from exc_value
tandoorrecipes-web_recipes-1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
tandoorrecipes-web_recipes-1    |     self.connect()
tandoorrecipes-web_recipes-1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
tandoorrecipes-web_recipes-1    |     return func(*args, **kwargs)
tandoorrecipes-web_recipes-1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
tandoorrecipes-web_recipes-1    |     self.connection = self.get_new_connection(conn_params)
tandoorrecipes-web_recipes-1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
tandoorrecipes-web_recipes-1    |     return func(*args, **kwargs)
tandoorrecipes-web_recipes-1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
tandoorrecipes-web_recipes-1    |     connection = Database.connect(**conn_params)
tandoorrecipes-web_recipes-1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
tandoorrecipes-web_recipes-1    |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
tandoorrecipes-web_recipes-1    | django.db.utils.OperationalError: could not connect to server: Connection refused
tandoorrecipes-web_recipes-1    | 	Is the server running on host "db_recipes" (172.23.0.2) and accepting
tandoorrecipes-web_recipes-1    | 	TCP/IP connections on port 5432?
tandoorrecipes-web_recipes-1    |
```

**Comment by smilerz** [comment]
Please see the documentation [here](https://docs.tandoor.dev/install/docker/#volumes-vs-bind-mounts).
