### ISSUE TITLE
Server Error (500) after update

### ISSUE THREAD

**Issue by JSAnyone** [TandoorRecipes/recipes#1433]
### Tandoor Version

1.0.5.2

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Bug description

Tandoor is not starting correctly after the newest update, I’m just getting a `Server Error (500)` or a debug message when debug-mode is enabled..

My docker-compose file:
```
version: "3"
services:
  db_recipes:
    restart: always
    image: postgres:11-alpine
    volumes:
- postgres-storage:/var/lib/postgresql/data
    env_file:
- ./.env

  web_recipes:
    image: vabene1111/recipes:1.0.5.2
    restart: always
    env_file:
- ./.env
    volumes:
- staticfiles-storage:/opt/recipes/staticfiles
- nginxconfig-storage:/opt/recipes/nginx/conf.d
- mediafiles-storage:/opt/recipes/mediafiles
    depends_on:
- db_recipes

  nginx_recipes:
    image: nginx:mainline-alpine
    restart: always
#   ports:
#     - 8080:80
    env_file:
- ./.env
    depends_on:
- web_recipes
    volumes:
- nginxconfig-storage:/etc/nginx/conf.d:ro
- staticfiles-storage:/static
- mediafiles-storage:/media
    networks:
- default
- docker-compose_traefik-network
    labels:
- "traefik.enable=true"
- "traefik.http.middlewares.recipes-redirect.redirectscheme.scheme=https"
- "traefik.http.routers.recipes-local.entrypoints=web"
- "traefik.http.routers.recipes-local.rule=Host(`192.168.0.1`)&&PathPrefix(`/recipes`)"
- "traefik.http.routers.recipes.entrypoints=web"
- "traefik.http.routers.recipes.rule=Host(`myserver.net`)&&PathPrefix(`/recipes`)"
- "traefik.http.routers.recipes.middlewares=recipes-redirect"
- "traefik.http.routers.recipes-secure.entrypoints=websecure"
- "traefik.http.routers.recipes-secure.rule=Host(`myserver.net`)&&PathPrefix(`/recipes`)"
- "traefik.http.routers.recipes-secure.tls=true"
- "traefik.http.routers.recipes-secure.tls.certresolver=myresolver"

networks:
docker-compose_traefik-network:
external: true

volumes:
postgres-storage:
nginxconfig-storage:
staticfiles-storage:
mediafiles-storage:
```

### Relevant logs

```shell
root@Raspi-Server:/opt/docker-recipes# docker-compose up
Starting docker-recipes_db_recipes_1 ... done
Starting docker-recipes_web_recipes_1 ... done
Starting docker-recipes_nginx_recipes_1 ... done
Attaching to docker-recipes_db_recipes_1, docker-recipes_web_recipes_1, docker-recipes_nginx_recipes_1
db_recipes_1     | 
db_recipes_1     | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_recipes_1     | 
db_recipes_1     | 2022-01-28 14:46:52.710 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_recipes_1     | 2022-01-28 14:46:52.710 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_recipes_1     | 2022-01-28 14:46:52.726 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_recipes_1     | 2022-01-28 14:46:52.801 UTC [21] LOG:  database system was shut down at 2022-01-28 14:46:44 UTC
db_recipes_1     | 2022-01-28 14:46:52.826 UTC [1] LOG:  database system is ready to accept connections
nginx_recipes_1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx_recipes_1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx_recipes_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx_recipes_1  | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
nginx_recipes_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
web_recipes_1    | Updating database
nginx_recipes_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx_recipes_1  | /docker-entrypoint.sh: Configuration complete; ready for start up
nginx_recipes_1  | 2022/01/28 14:46:55 [notice] 1#1: using the "epoll" event method
nginx_recipes_1  | 2022/01/28 14:46:55 [notice] 1#1: nginx/1.21.6
nginx_recipes_1  | 2022/01/28 14:46:55 [notice] 1#1: built by gcc 10.3.1 20211027 (Alpine 10.3.1_git20211027) 
nginx_recipes_1  | 2022/01/28 14:46:55 [notice] 1#1: OS: Linux 5.10.63-v8+
nginx_recipes_1  | 2022/01/28 14:46:55 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
nginx_recipes_1  | 2022/01/28 14:46:55 [notice] 1#1: start worker processes
nginx_recipes_1  | 2022/01/28 14:46:55 [notice] 1#1: start worker process 23
nginx_recipes_1  | 2022/01/28 14:46:55 [notice] 1#1: start worker process 24
nginx_recipes_1  | 2022/01/28 14:46:55 [notice] 1#1: start worker process 25
nginx_recipes_1  | 2022/01/28 14:46:55 [notice] 1#1: start worker process 26
web_recipes_1    | Operations to perform:
web_recipes_1    |   Apply all migrations: account, admin, auth, authtoken, contenttypes, cookbook, sessions, sites, socialaccount
web_recipes_1    | Running migrations:
web_recipes_1    |   No migrations to apply.
web_recipes_1    | js-reverse file written to /opt/recipes/cookbook/static/django_js_reverse
web_recipes_1    | 
web_recipes_1    | 1 static file copied to '/opt/recipes/staticfiles', 1026 unmodified, 2006 post-processed.
web_recipes_1    | Done
web_recipes_1    | [2022-01-28 14:47:26 +0000] [1] [INFO] Starting gunicorn 20.1.0
web_recipes_1    | [2022-01-28 14:47:26 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
web_recipes_1    | [2022-01-28 14:47:26 +0000] [1] [INFO] Using worker: sync
web_recipes_1    | [2022-01-28 14:47:26 +0000] [12] [INFO] Booting worker with pid: 12
web_recipes_1    | 
web_recipes_1    | 
web_recipes_1    |   [SQL Queries for] /
web_recipes_1    | 
web_recipes_1    |   [TOTAL TIME: 0.004 seconds]
web_recipes_1    |   [TOTAL QUERIES: 1]
nginx_recipes_1  | 172.24.0.9 - - [28/Jan/2022:14:47:47 +0000] "GET /recipes/ HTTP/1.1" 302 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15" "109.250.0.21"
web_recipes_1    | 172.20.0.4 - - [28/Jan/2022:15:47:47 +0100] "GET /recipes/ HTTP/1.0" 302 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15"
nginx_recipes_1  | 172.24.0.9 - - [28/Jan/2022:14:47:47 +0000] "GET /recipes/search/ HTTP/1.1" 302 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15" "109.250.0.21"
web_recipes_1    | 172.20.0.4 - - [28/Jan/2022:15:47:47 +0100] "GET /recipes/search/ HTTP/1.0" 302 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15"
db_recipes_1     | 2022-01-28 14:47:48.167 UTC [31] ERROR:  column cookbook_space.show_facet_count does not exist at character 310
db_recipes_1     | 2022-01-28 14:47:48.167 UTC [31] STATEMENT:  SELECT "cookbook_space"."id", "cookbook_space"."name", "cookbook_space"."created_by_id", "cookbook_space"."created_at", "cookbook_space"."message", "cookbook_space"."max_recipes", "cookbook_space"."max_file_storage_mb", "cookbook_space"."max_users", "cookbook_space"."allow_sharing", "cookbook_space"."demo", "cookbook_space"."show_facet_count" FROM "cookbook_space" ORDER BY "cookbook_space"."id" ASC LIMIT 1
db_recipes_1     | 2022-01-28 14:47:48.232 UTC [31] ERROR:  column cookbook_space.show_facet_count does not exist at character 310
db_recipes_1     | 2022-01-28 14:47:48.232 UTC [31] STATEMENT:  SELECT "cookbook_space"."id", "cookbook_space"."name", "cookbook_space"."created_by_id", "cookbook_space"."created_at", "cookbook_space"."message", "cookbook_space"."max_recipes", "cookbook_space"."max_file_storage_mb", "cookbook_space"."max_users", "cookbook_space"."allow_sharing", "cookbook_space"."demo", "cookbook_space"."show_facet_count" FROM "cookbook_space" LIMIT 21
db_recipes_1     | 2022-01-28 14:47:48.235 UTC [31] ERROR:  column cookbook_space.show_facet_count does not exist at character 310
db_recipes_1     | 2022-01-28 14:47:48.235 UTC [31] STATEMENT:  SELECT "cookbook_space"."id", "cookbook_space"."name", "cookbook_space"."created_by_id", "cookbook_space"."created_at", "cookbook_space"."message", "cookbook_space"."max_recipes", "cookbook_space"."max_file_storage_mb", "cookbook_space"."max_users", "cookbook_space"."allow_sharing", "cookbook_space"."demo", "cookbook_space"."show_facet_count" FROM "cookbook_space" ORDER BY "cookbook_space"."id" ASC LIMIT 1
db_recipes_1     | 2022-01-28 14:47:48.238 UTC [31] ERROR:  column cookbook_space.show_facet_count does not exist at character 310
db_recipes_1     | 2022-01-28 14:47:48.238 UTC [31] STATEMENT:  SELECT "cookbook_space"."id", "cookbook_space"."name", "cookbook_space"."created_by_id", "cookbook_space"."created_at", "cookbook_space"."message", "cookbook_space"."max_recipes", "cookbook_space"."max_file_storage_mb", "cookbook_space"."max_users", "cookbook_space"."allow_sharing", "cookbook_space"."demo", "cookbook_space"."show_facet_count" FROM "cookbook_space" ORDER BY "cookbook_space"."id" ASC LIMIT 1
db_recipes_1     | 2022-01-28 14:47:48.241 UTC [31] ERROR:  column cookbook_space.show_facet_count does not exist at character 310
db_recipes_1     | 2022-01-28 14:47:48.241 UTC [31] STATEMENT:  SELECT "cookbook_space"."id", "cookbook_space"."name", "cookbook_space"."created_by_id", "cookbook_space"."created_at", "cookbook_space"."message", "cookbook_space"."max_recipes", "cookbook_space"."max_file_storage_mb", "cookbook_space"."max_users", "cookbook_space"."allow_sharing", "cookbook_space"."demo", "cookbook_space"."show_facet_count" FROM "cookbook_space" ORDER BY "cookbook_space"."id" ASC LIMIT 1
web_recipes_1    | Internal Server Error: /recipes/accounts/login/
web_recipes_1    | Traceback (most recent call last):
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
web_recipes_1    |     return self.cursor.execute(sql, params)
web_recipes_1    | psycopg2.errors.UndefinedColumn: column cookbook_space.show_facet_count does not exist
web_recipes_1    | LINE 1: ..._space"."allow_sharing", "cookbook_space"."demo", "cookbook_...
web_recipes_1    |                                                              ^
web_recipes_1    | 
web_recipes_1    | 
web_recipes_1    | The above exception was the direct cause of the following exception:
web_recipes_1    | 
web_recipes_1    | Traceback (most recent call last):
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
web_recipes_1    |     response = get_response(request)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 204, in _get_response
web_recipes_1    |     response = response.render()
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/template/response.py", line 105, in render
web_recipes_1    |     self.content = self.rendered_content
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/template/response.py", line 83, in rendered_content
web_recipes_1    |     return template.render(context, self._request)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
web_recipes_1    |     return self.template.render(context)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/template/base.py", line 170, in render
web_recipes_1    |     return self._render(context)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
web_recipes_1    |     return self.nodelist.render(context)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
web_recipes_1    |     bit = node.render_annotated(context)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
web_recipes_1    |     return self.render(context)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/template/loader_tags.py", line 150, in render
web_recipes_1    |     return compiled_parent._render(context)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/template/base.py", line 162, in _render
web_recipes_1    |     return self.nodelist.render(context)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/template/base.py", line 938, in render
web_recipes_1    |     bit = node.render_annotated(context)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/template/base.py", line 905, in render_annotated
web_recipes_1    |     return self.render(context)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/template/library.py", line 192, in render
web_recipes_1    |     output = self.func(*resolved_args, **resolved_kwargs)
web_recipes_1    |   File "/opt/recipes/cookbook/templatetags/custom_tags.py", line 114, in message_of_the_day
web_recipes_1    |     return Space.objects.first().message
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
web_recipes_1    |     return getattr(self.get_queryset(), name)(*args, **kwargs)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/models/query.py", line 674, in first
web_recipes_1    |     for obj in (self if self.ordered else self.order_by('pk'))[:1]:
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/models/query.py", line 280, in __iter__
web_recipes_1    |     self._fetch_all()
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/models/query.py", line 1324, in _fetch_all
web_recipes_1    |     self._result_cache = list(self._iterable_class(self))
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/models/query.py", line 51, in __iter__
web_recipes_1    |     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
web_recipes_1    |     cursor.execute(sql, params)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 98, in execute
web_recipes_1    |     return super().execute(sql, params)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
web_recipes_1    |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
web_recipes_1    |     return executor(sql, params, many, context)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
web_recipes_1    |     return self.cursor.execute(sql, params)
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
web_recipes_1    |     raise dj_exc_value.with_traceback(traceback) from exc_value
web_recipes_1    |   File "/opt/recipes/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
web_recipes_1    |     return self.cursor.execute(sql, params)
web_recipes_1    | django.db.utils.ProgrammingError: column cookbook_space.show_facet_count does not exist
web_recipes_1    | LINE 1: ..._space"."allow_sharing", "cookbook_space"."demo", "cookbook_...
web_recipes_1    |                                                              ^
web_recipes_1    | 
nginx_recipes_1  | 172.24.0.9 - - [28/Jan/2022:14:47:48 +0000] "GET /recipes/accounts/login/?next=/recipes/search/ HTTP/1.1" 500 194356 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15" "109.250.0.21"
web_recipes_1    | 
web_recipes_1    | 
web_recipes_1    |   [SQL Queries for] /accounts/login/
web_recipes_1    | 
web_recipes_1    |   [TOTAL TIME: 0.011000000000000003 seconds]
web_recipes_1    |   [TOTAL QUERIES: 6]
web_recipes_1    | 172.20.0.4 - - [28/Jan/2022:15:47:48 +0100] "GET /recipes/accounts/login/?next=/recipes/search/ HTTP/1.0" 500 194356 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15"
^CGracefully stopping... (press Ctrl+C again to force)
Stopping docker-recipes_nginx_recipes_1 ... done
Stopping docker-recipes_web_recipes_1   ... done
Stopping docker-recipes_db_recipes_1    ... done
root@Raspi-Server:/opt/docker-recipes#
```

**Comment by vabene1111** [comment]
are you sure that you pulled the latest image ? this was broken in an intermediate release but is now fixed.

**Comment by smilerz** [comment]
Which version are you upgrading from?  Was it potentially a previous version of develop?  That would probably break the upgrade path.

Also, as a side note - the SQL_DEBUG is only relevant if you are developing.  No need to add the overhead otherwise.

**Comment by JSAnyone** [comment]
> are you sure that you pulled the latest image ? this was broken in an intermediate release but is now fixed.

Yes. That’s why is used the `1.0.5.2` release instead of the `latest` release.


> Which version are you upgrading from? Was it potentially a previous version of develop? That would probably break the upgrade path.

It was a latest version, however I don’t know which. But sometimes ago I used a self built `develop` image, could that still have consequences?

**Comment by JSAnyone** [comment]
For testing purpose I went back to `vabene1111/recipes:1.0.4.1`. All was working as expected.
Switching to `vabene1111/recipes:latest` again ended in the same errors.
