### ISSUE TITLE
Manual Update is not working

### ISSUE THREAD

**Issue by hyperbit00** [TandoorRecipes/recipes#1503]
I Installed Tandoor without Docker (manual)
and now i try to update to current relase but it isnt working 

https://docs.tandoor.dev/install/manual/
```
git pull
export $(cat /var/www/recipes/.env |grep "^[^#]" | xargs)
bin/python3.9 manage.py migrate
bin/python3.9 manage.py collectstatic
bin/python3.9 manage.py collectstatic_js_reverse
cd vue
yarn install
yarn build
sudo systemctl restart gunicorn_recipes

```
It seems, the update is not working ? 

```


Last login: Mon Feb  7 10:07:22 2022 from 192.168.188.205
root@kochbuch:~# cd ..
root@kochbuch:/# cd var
root@kochbuch:/var# cd www
root@kochbuch:/var/www# cd recipes
root@kochbuch:/var/www/recipes# git pull
Updating 8a7c4e11..cffe1161
error: Your local changes to the following files would be overwritten by merge:
        cookbook/static/django_js_reverse/reverse.js
Please commit your changes or stash them before you merge.
Aborting
root@kochbuch:/var/www/recipes# git stash
Saved working directory and index state WIP on master: 8a7c4e11 fixed invite link counting
root@kochbuch:/var/www/recipes# git pull
Updating 8a7c4e11..cffe1161
Fast-forward
 .dockerignore                                                                |   19 +-
 .env.template                                                                |   12 +-
 .github/ISSUE_TEMPLATE/bug_report.md                                         |   15 -
 .github/ISSUE_TEMPLATE/bug_report.md.bak                                     |   81 ++++++
 .github/ISSUE_TEMPLATE/bug_report.yml                                        |   64 ++++
 .github/ISSUE_TEMPLATE/config.yml                                            |    5 +
 .github/ISSUE_TEMPLATE/doc_issue.yml                                         |   40 +++
 .github/ISSUE_TEMPLATE/{feature_request.md => feature_request.md.bak}        |    0
 .github/ISSUE_TEMPLATE/feature_request.yml                                   |   39 +++
 .github/ISSUE_TEMPLATE/{help-request.md => help-request.md.bak}              |    0
 .github/ISSUE_TEMPLATE/help_request.yml                                      |   82 ++++++
 .github/ISSUE_TEMPLATE/{url_import.md => url_import.md.bak}                  |    0
 .github/ISSUE_TEMPLATE/website_import.yml                                    |   36 +++
 .github/workflows/ci.yml                                                     |    2 +-
 README.md                                                                    |    2 +-
 SECURITY.md                                                                  |    2 +-
 cookbook/admin.py                                                            |   75 ++++-
 cookbook/apps.py                                                             |   47 ++-
 cookbook/forms.py                                                            |  113 +++++--
 cookbook/helper/HelperFunctions.py                                           |   13 +
 cookbook/helper/permission_helper.py                                         |   11 +-
 cookbook/helper/recipe_search.py                                             | 1272 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++-----------------------
 cookbook/helper/scope_middleware.py                                          |   10 +-
 cookbook/helper/shopping_helper.py                                           |  309 ++++++++++++++++++++
 cookbook/integration/default.py                                              |   35 ++-
 cookbook/integration/integration.py                                          |  115 ++++----
 cookbook/integration/pdfexport.py                                            |   69 +++++
 cookbook/integration/recettetek.py                                           |    4 +-
 cookbook/integration/recipesage.py                                           |   11 +
 cookbook/integration/{safron.py => saffron.py}                               |   43 ++-
 cookbook/locale/ca/LC_MESSAGES/django.mo                                     |  Bin 24294 -> 24107 bytes
 cookbook/locale/ca/LC_MESSAGES/django.po                                     | 1009 ++++++++++++++++++++++++++++++++++++++++-----------------------
 cookbook/locale/de/LC_MESSAGES/django.mo                                     |  Bin 60039 -> 59896 bytes
 cookbook/locale/de/LC_MESSAGES/django.po                                     | 1023 ++++++++++++++++++++++++++++++++++++++++------------------------
 cookbook/locale/en/LC_MESSAGES/django.po                                     |  975 ++++++++++++++++++++++++++++++++++++++-----------------------
 cookbook/locale/es/LC_MESSAGES/django.mo                                     |  Bin 27861 -> 27651 bytes
 cookbook/locale/es/LC_MESSAGES/django.po                                     | 1009 ++++++++++++++++++++++++++++++++++++++++-----------------------
 cookbook/locale/fr/LC_MESSAGES/django.mo                                     |  Bin 42137 -> 63560 bytes
 cookbook/locale/fr/LC_MESSAGES/django.po                                     | 1454 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++---------------------------------
 cookbook/locale/hu_HU/LC_MESSAGES/django.po                                  |  979 ++++++++++++++++++++++++++++++++++++++-----------------------
 cookbook/locale/it/LC_MESSAGES/django.mo                                     |  Bin 48134 -> 48920 bytes
 cookbook/locale/it/LC_MESSAGES/django.po                                     | 1024 ++++++++++++++++++++++++++++++++++++++++------------------------
 cookbook/locale/lv/LC_MESSAGES/django.mo                                     |  Bin 24519 -> 24331 bytes
 cookbook/locale/lv/LC_MESSAGES/django.po                                     | 1007 ++++++++++++++++++++++++++++++++++++++++-----------------------
 cookbook/locale/nl/LC_MESSAGES/django.mo                                     |  Bin 59873 -> 59598 bytes
 cookbook/locale/nl/LC_MESSAGES/django.po                                     | 1009 ++++++++++++++++++++++++++++++++++++++++-----------------------
 cookbook/locale/pt/LC_MESSAGES/django.mo                                     |  Bin 14241 -> 14056 bytes
 cookbook/locale/pt/LC_MESSAGES/django.po                                     | 1008 ++++++++++++++++++++++++++++++++++++++++-----------------------
 cookbook/locale/rn/LC_MESSAGES/django.po                                     |  975 ++++++++++++++++++++++++++++++++++++++-----------------------
 cookbook/locale/sl/LC_MESSAGES/django.po                                     |  106 ++++---
 cookbook/locale/tr/LC_MESSAGES/django.po                                     |  977 ++++++++++++++++++++++++++++++++++++++-----------------------
 cookbook/locale/zh_CN/LC_MESSAGES/django.mo                                  |  Bin 11520 -> 46668 bytes
 cookbook/locale/zh_CN/LC_MESSAGES/django.po                                  | 1807 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++------------------------------------------------
 cookbook/management/commands/rebuildindex.py                                 |    2 +-
 cookbook/migrations/0143_build_full_text_index.py                            |   10 +-
 cookbook/migrations/0159_add_shoppinglistentry_fields.py                     |  149 ++++++++++
 cookbook/migrations/0160_delete_shoppinglist_orphans.py                      |   50 ++++
 cookbook/migrations/0161_alter_shoppinglistentry_food.py                     |   19 ++
 cookbook/migrations/0162_userpreference_csv_delim.py                         |   23 ++
 cookbook/migrations/0163_auto_20220105_0758.py                               |   41 +++
 cookbook/migrations/0164_space_show_facet_count.py                           |   19 ++
 cookbook/migrations/0165_remove_step_type.py                                 |   17 ++
 cookbook/migrations/0166_alter_userpreference_shopping_add_onhand.py         |   26 ++
 cookbook/migrations/0167_userpreference_left_handed.py                       |   18 ++
 cookbook/migrations/0168_add_unit_searchfields.py                            |   20 ++
 cookbook/migrations/0169_exportlog.py                                        |   34 +++
 cookbook/models.py                                                           |  230 +++++++++++++--
 cookbook/provider/nextcloud.py                                               |    6 +-
 cookbook/serializer.py                                                       |  351 +++++++++++++++-------
 cookbook/signals.py                                                          |  128 ++++++--
 cookbook/static/css/app.min.css                                              |    7 +
 cookbook/static/django_js_reverse/reverse.js                                 |    2 +-
 cookbook/static/themes/tandoor.min.css                                       |    5 +
 cookbook/templates/account/login.html                                        |   15 +-
 cookbook/templates/account/signup.html                                       |    4 +
 cookbook/templates/base.html                                                 |    3 +-
 cookbook/templates/export.html                                               |   42 +--
 cookbook/templates/{generic/checklist_template.html => export_response.html} |   18 +-
 cookbook/templates/generic/list_template.html                                |   21 +-
 cookbook/templates/include/log_cooking.html                                  |   80 -----
 cookbook/templates/index.html                                                |    3 +-
 cookbook/templates/manifest.json                                             |   92 +++---
 cookbook/templates/markdown_info.html                                        |    6 +-
 cookbook/templates/search_info.html                                          |    6 +-
 cookbook/templates/settings.html                                             |   52 +++-
 cookbook/templates/shopping_list.html                                        | 1612 +++++++++++++++++++++++++++++++++++++++++++++++++---------------------------------------------------
 cookbook/templates/shoppinglist_template.html                                |   17 ++
 cookbook/templates/space.html                                                |  305 ++++++++++---------
 cookbook/templates/url_import.html                                           |   57 +++-
 cookbook/templatetags/custom_tags.py                                         |    3 +-
 cookbook/tests/api/test_api_food.py                                          |  421 ++++++++++++++++----------
 cookbook/tests/api/test_api_food_shopping.py                                 |   96 ++++++
 cookbook/tests/api/test_api_meal_plan.py                                     |   21 +-
 cookbook/tests/api/test_api_recipe.py                                        |    2 +-
 cookbook/tests/api/test_api_related_recipe.py                                |   73 +++++
 cookbook/tests/api/test_api_shopping_list.py                                 |   17 +-
 cookbook/tests/api/test_api_shopping_list_entry.py                           |    9 +-
 cookbook/tests/api/test_api_shopping_list_entryv2.py                         |  248 ++++++++++++++++
 cookbook/tests/api/test_api_shopping_recipe.py                               |  242 +++++++++++++++
 cookbook/tests/api/test_api_step.py                                          |   10 +-
 cookbook/tests/api/test_api_unit.py                                          |    6 +-
 cookbook/tests/api/test_api_userpreference.py                                |   35 ++-
 cookbook/tests/conftest.py                                                   |   52 ++--
 cookbook/tests/factories/__init__.py                                         |  370 +++++++++++++++++++++++
 cookbook/tests/other/test_export.py                                          |   25 ++
 cookbook/urls.py                                                             |   37 ++-
 cookbook/views/api.py                                                        |  317 +++++++++++++++-----
 cookbook/views/data.py                                                       |    8 +-
 cookbook/views/import_export.py                                              |   67 ++++-
 cookbook/views/lists.py                                                      |   31 +-
 cookbook/views/telegram.py                                                   |   12 +-
 cookbook/views/views.py                                                      |   66 ++++-
 docs/faq.md                                                                  |   58 +++-
 docs/features/authentication.md                                              |   26 +-
 docs/features/external_recipes.md                                            |    2 +-
 docs/features/import_export.md                                               |   53 ++--
 docs/index.md                                                                |    4 +-
 docs/install/docker.md                                                       |  243 +++++++++++++---
 docs/install/docker/nginx-proxy/docker-compose.yml                           |    8 +-
 docs/install/docker/plain/docker-compose.yml                                 |   10 +-
 docs/install/docker/traefik-nginx/docker-compose.yml                         |   10 +-
 docs/install/k8s/{20-service-account.yml => 20-service-account.yaml}         |    0
 docs/install/kubernetes.md                                                   |   52 ++--
 docs/install/manual.md                                                       |   29 +-
 docs/install/other.md                                                        |    2 +-
 docs/install/swag.md                                                         |  118 ++++++++
 docs/install/synology.md                                                     |   62 ++--
 docs/install/traefik.md                                                      |    4 +-
 docs/install/unraid.md                                                       |   21 +-
 docs/system/backup.md                                                        |    2 +-
 docs/system/permissions.md                                                   |    4 +-
 recipes/locale/ca/LC_MESSAGES/django.po                                      |   26 +-
 recipes/locale/de/LC_MESSAGES/django.po                                      |   26 +-
 recipes/locale/en/LC_MESSAGES/django.po                                      |   26 +-
 recipes/locale/es/LC_MESSAGES/django.po                                      |   26 +-
 recipes/locale/fr/LC_MESSAGES/django.po                                      |   26 +-
 recipes/locale/hu_HU/LC_MESSAGES/django.po                                   |   26 +-
 recipes/locale/it/LC_MESSAGES/django.po                                      |   26 +-
 recipes/locale/lv/LC_MESSAGES/django.po                                      |   26 +-
 recipes/locale/nl/LC_MESSAGES/django.po                                      |   26 +-
 recipes/locale/pt/LC_MESSAGES/django.po                                      |   26 +-
 recipes/locale/rn/LC_MESSAGES/django.po                                      |   26 +-
 recipes/locale/tr/LC_MESSAGES/django.po                                      |   26 +-
 recipes/locale/zh_CN/LC_MESSAGES/django.po                                   |   26 +-
 recipes/middleware.py                                                        |   12 +-
 recipes/settings.py                                                          |   14 +-
 requirements.txt                                                             |   38 +--
 vue/.gitignore                                                               |   23 --
 vue/.openapi-generator/FILES                                                 |    8 +
 vue/.openapi-generator/VERSION                                               |    1 +
 vue/package.json                                                             |   13 +-
 vue/src/apps/ChecklistView/ChecklistView.vue                                 |  195 -------------
 vue/src/apps/CookbookView/CookbookView.vue                                   |  269 ++++++++---------
 vue/src/apps/ExportResponseView/ExportResponseView.vue                       |  145 +++++++++
 vue/src/apps/ExportResponseView/main.js                                      |   18 ++
 vue/src/apps/ExportView/ExportView.vue                                       |  174 +++++++++++
 vue/src/apps/{ChecklistView => ExportView}/main.js                           |    2 +-
 vue/src/apps/MealPlanView/MealPlanView.vue                                   | 1371 ++++++++++++++++++++++++++++++++++++++++++++-----------------------------------------
 vue/src/apps/ModelListView/ModelListView.vue                                 |  132 ++++-----
 vue/src/apps/RecipeEditView/RecipeEditView.vue                               | 1720 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-------------------------------------------------
 vue/src/apps/RecipeSearchView/RecipeSearchView.vue                           |  444 +++++++++++++++++-----------
 vue/src/apps/RecipeView/RecipeView.vue                                       |  486 ++++++++++++++++---------------
 vue/src/apps/ShoppingListView/ShoppingListView.vue                           | 1513 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 vue/src/apps/ShoppingListView/main.js                                        |   17 ++
 vue/src/apps/SupermarketView/SupermarketView.vue                             |  337 ++++++++++-----------
 vue/src/components/AddRecipeToBook.vue                                       |  198 ++++++-------
 vue/src/components/Badges.vue                                                |   64 ++--
 vue/src/components/Badges/Help.vue                                           |   58 ++++
 vue/src/components/Badges/Icon.vue                                           |    2 +-
 vue/src/components/Badges/LinkedRecipe.vue                                   |    2 +-
 vue/src/components/Badges/OnHand.vue                                         |   45 +++
 vue/src/components/Badges/Shopping.vue                                       |   88 ++++++
 vue/src/components/Buttons/CopyToClipboard.vue                               |   62 ++++
 vue/src/components/Buttons/DownloadCSV.vue                                   |   33 +++
 vue/src/components/Buttons/DownloadPDF.vue                                   |   32 ++
 vue/src/components/Buttons/RecipeSwitcher.vue                                |  225 ++++++++++++++
 vue/src/components/ContextMenu/ContextMenu.vue                               |  185 ++++++------
 vue/src/components/ContextMenu/ContextMenuItem.vue                           |   13 +-
 vue/src/components/ContextMenu/GenericContextMenu.vue                        |   38 +++
 vue/src/components/ContextMenu/ModelMenu.vue                                 |   52 ++++
 vue/src/components/CustomInputSpinButton.vue                                 |   86 ++++++
 vue/src/components/GenericContextMenu.vue                                    |   42 ---
 vue/src/components/GenericHorizontalCard.vue                                 |  515 +++++++++++++++++---------------
 vue/src/components/GenericMultiselect.vue                                    |  249 +++++++++-------
 vue/src/components/GenericOrderedPill.vue                                    |  121 ++++----
 vue/src/components/GenericPill.vue                                           |    7 +-
 vue/src/components/IngredientComponent.vue                                   |  194 +++++++-----
 vue/src/components/IngredientsCard.vue                                       |  248 ++++++++++++++++
 vue/src/components/KeywordsComponent.vue                                     |   15 +-
 vue/src/components/MealPlanCalenderHeader.vue                                |    2 +-
 vue/src/components/MealPlanCard.vue                                          |  222 +++++++-------
 vue/src/components/MealPlanEditModal.vue                                     |  437 ++++++++++++++-------------
 vue/src/components/Modals/AddRecipeToBook.vue                                |  122 ++++++++
 vue/src/components/Modals/CheckboxInput.vue                                  |   50 ++--
 vue/src/components/Modals/GenericModalForm.vue                               |   96 ++++--
 vue/src/components/Modals/LookupInput.vue                                    |   11 +-
 vue/src/components/Modals/ShoppingModal.vue                                  |  208 +++++++++++++
 vue/src/components/Modals/SmallText.vue                                      |   20 ++
 vue/src/components/Modals/TextInput.vue                                      |   59 ++--
 vue/src/components/ModelMenu.vue                                             |   74 -----
 vue/src/components/RecipeCard.vue                                            |  243 +++++++---------
 vue/src/components/RecipeContextMenu.vue                                     |  356 +++++++++++-----------
 vue/src/components/ShoppingLineItem.vue                                      |  354 ++++++++++++++++++++++
 vue/src/components/StepComponent.vue                                         |  362 +++++++++++------------
 vue/src/i18n.js                                                              |    1 +
 vue/src/locales/de.json                                                      |   89 +++++-
 vue/src/locales/en.json                                                      |   90 +++++-
 vue/src/locales/fi.json                                                      |    4 +-
 vue/src/locales/fr.json                                                      |   99 ++++++-
 vue/src/locales/hy.json                                                      |   76 +++--
 vue/src/locales/it.json                                                      |   41 ++-
 vue/src/locales/nl.json                                                      |   94 +++++-
 vue/src/locales/pl.json                                                      |   96 +++++-
 vue/src/locales/ro.json                                                      |    2 +-
 vue/src/locales/ru.json                                                      |    4 +-
 vue/src/locales/sl.json                                                      |  440 ++++++++++++++++------------
 vue/src/locales/zh_Hans.json                                                 |  256 ++++++++++++++--
 vue/src/sw.js                                                                |    2 +-
 vue/src/utils/api.js                                                         |    7 +-
 vue/src/utils/apiv2.js                                                       |   16 +
 vue/src/utils/models.js                                                      |  153 ++++++----
 vue/src/utils/openapi/api.ts                                                 | 2106 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-------------------------
 vue/src/utils/utils.js                                                       |   98 +++++--
 vue/vue.config.js                                                            |   13 +-
 vue/yarn.lock                                                                |  343 +++++++++++++++++-----
 yarn.lock                                                                    |    4 -
 226 files changed, 26831 insertions(+), 12917 deletions(-)
 delete mode 100644 .github/ISSUE_TEMPLATE/bug_report.md
 create mode 100644 .github/ISSUE_TEMPLATE/bug_report.md.bak
 create mode 100644 .github/ISSUE_TEMPLATE/bug_report.yml
 create mode 100644 .github/ISSUE_TEMPLATE/config.yml
 create mode 100644 .github/ISSUE_TEMPLATE/doc_issue.yml
 rename .github/ISSUE_TEMPLATE/{feature_request.md => feature_request.md.bak} (100%)
 create mode 100644 .github/ISSUE_TEMPLATE/feature_request.yml
 rename .github/ISSUE_TEMPLATE/{help-request.md => help-request.md.bak} (100%)
 create mode 100644 .github/ISSUE_TEMPLATE/help_request.yml
 rename .github/ISSUE_TEMPLATE/{url_import.md => url_import.md.bak} (100%)
 create mode 100644 .github/ISSUE_TEMPLATE/website_import.yml
 create mode 100644 cookbook/helper/HelperFunctions.py
 create mode 100644 cookbook/helper/shopping_helper.py
 create mode 100644 cookbook/integration/pdfexport.py
 rename cookbook/integration/{safron.py => saffron.py} (65%)
 create mode 100644 cookbook/migrations/0159_add_shoppinglistentry_fields.py
 create mode 100644 cookbook/migrations/0160_delete_shoppinglist_orphans.py
 create mode 100644 cookbook/migrations/0161_alter_shoppinglistentry_food.py
 create mode 100644 cookbook/migrations/0162_userpreference_csv_delim.py
 create mode 100644 cookbook/migrations/0163_auto_20220105_0758.py
 create mode 100644 cookbook/migrations/0164_space_show_facet_count.py
 create mode 100644 cookbook/migrations/0165_remove_step_type.py
 create mode 100644 cookbook/migrations/0166_alter_userpreference_shopping_add_onhand.py
 create mode 100644 cookbook/migrations/0167_userpreference_left_handed.py
 create mode 100644 cookbook/migrations/0168_add_unit_searchfields.py
 create mode 100644 cookbook/migrations/0169_exportlog.py
 rename cookbook/templates/{generic/checklist_template.html => export_response.html} (52%)
 delete mode 100644 cookbook/templates/include/log_cooking.html
 create mode 100644 cookbook/templates/shoppinglist_template.html
 create mode 100644 cookbook/tests/api/test_api_food_shopping.py
 create mode 100644 cookbook/tests/api/test_api_related_recipe.py
 create mode 100644 cookbook/tests/api/test_api_shopping_list_entryv2.py
 create mode 100644 cookbook/tests/api/test_api_shopping_recipe.py
 create mode 100644 cookbook/tests/factories/__init__.py
 create mode 100644 cookbook/tests/other/test_export.py
 rename docs/install/k8s/{20-service-account.yml => 20-service-account.yaml} (100%)
 create mode 100644 docs/install/swag.md
 delete mode 100644 vue/.gitignore
 create mode 100644 vue/.openapi-generator/FILES
 create mode 100644 vue/.openapi-generator/VERSION
 delete mode 100644 vue/src/apps/ChecklistView/ChecklistView.vue
 create mode 100644 vue/src/apps/ExportResponseView/ExportResponseView.vue
 create mode 100644 vue/src/apps/ExportResponseView/main.js
 create mode 100644 vue/src/apps/ExportView/ExportView.vue
 rename vue/src/apps/{ChecklistView => ExportView}/main.js (92%)
 create mode 100644 vue/src/apps/ShoppingListView/ShoppingListView.vue
 create mode 100644 vue/src/apps/ShoppingListView/main.js
 create mode 100644 vue/src/components/Badges/Help.vue
 create mode 100644 vue/src/components/Badges/OnHand.vue
 create mode 100644 vue/src/components/Badges/Shopping.vue
 create mode 100644 vue/src/components/Buttons/CopyToClipboard.vue
 create mode 100644 vue/src/components/Buttons/DownloadCSV.vue
 create mode 100644 vue/src/components/Buttons/DownloadPDF.vue
 create mode 100644 vue/src/components/Buttons/RecipeSwitcher.vue
 create mode 100644 vue/src/components/ContextMenu/GenericContextMenu.vue
 create mode 100644 vue/src/components/ContextMenu/ModelMenu.vue
 create mode 100644 vue/src/components/CustomInputSpinButton.vue
 delete mode 100644 vue/src/components/GenericContextMenu.vue
 create mode 100644 vue/src/components/IngredientsCard.vue
 create mode 100644 vue/src/components/Modals/AddRecipeToBook.vue
 create mode 100644 vue/src/components/Modals/ShoppingModal.vue
 create mode 100644 vue/src/components/Modals/SmallText.vue
 delete mode 100644 vue/src/components/ModelMenu.vue
 create mode 100644 vue/src/components/ShoppingLineItem.vue
 create mode 100644 vue/src/utils/apiv2.js
 delete mode 100644 yarn.lock
root@kochbuch:/var/www/recipes# export $(cat /var/www/recipes/.env |grep "^[^#]" | xargs)
root@kochbuch:/var/www/recipes# bin/python3.9 manage.py migrate
Traceback (most recent call last):
  File "/var/www/recipes/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/recipes/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/var/www/recipes/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/recipes/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/recipes/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/var/www/recipes/lib/python3.9/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/var/www/recipes/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 75, in handle
    self.check(databases=[database])
  File "/var/www/recipes/lib/python3.9/site-packages/django/core/management/base.py", line 419, in check
    all_issues = checks.run_checks(
  File "/var/www/recipes/lib/python3.9/site-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/var/www/recipes/lib/python3.9/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/var/www/recipes/lib/python3.9/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/var/www/recipes/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/var/www/recipes/lib/python3.9/site-packages/django/urls/resolvers.py", line 602, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/var/www/recipes/lib/python3.9/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/var/www/recipes/lib/python3.9/site-packages/django/urls/resolvers.py", line 595, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/www/recipes/recipes/urls.py", line 26, in <module>
    path('', include('cookbook.urls')),
  File "/var/www/recipes/lib/python3.9/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/www/recipes/cookbook/urls.py", line 15, in <module>
    from .views import api, data, delete, edit, import_export, lists, new, telegram, views
  File "/var/www/recipes/cookbook/views/__init__.py", line 5, in <module>
    import cookbook.views.import_export
  File "/var/www/recipes/cookbook/views/import_export.py", line 32, in <module>
    from cookbook.integration.pdfexport import PDFexport
  File "/var/www/recipes/cookbook/integration/pdfexport.py", line 6, in <module>
    from pyppeteer import launch
ModuleNotFoundError: No module named 'pyppeteer'
root@kochbuch:/var/www/recipes#



```

eigentlich ist pyppeteer für python 2.x - 3.9.1 installiert

**Comment by vabene1111** [comment]
you need to reinstall requirmentes in each update. Other than that i cannot offer any support for manual setups as there are simply to many things that can be wrong and it just takes way to much time for me to debug and understan all possibel manual setups, thats why we recommend using docker. `pip install -r requirements.txt` should do the trick
