### ISSUE TITLE
PDF Export

### ISSUE THREAD

**Issue by monster010** [TandoorRecipes/recipes#1551]
### Tandoor Version

1.0.8

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

Heyho,

I thought it would be a good idea to test the PDF export and found an error and will share it with you.

I would be happy about solutions, would also help with testing.

Kind regards
monster010

### Relevant logs

```shell
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/recipes/cookbook/integration/integration.py", line 77, in do_export
    files = self.get_files_from_recipes(recipes, el, self.request.COOKIES)
  File "/opt/recipes/cookbook/integration/pdfexport.py", line 69, in get_files_from_recipes
    return asyncio.run(self.get_files_from_recipes_async(recipes, el, cookie))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/recipes/cookbook/integration/pdfexport.py", line 28, in get_files_from_recipes_async
    browser = await launch(
  File "/opt/recipes/venv/lib/python3.9/site-packages/pyppeteer/launcher.py", line 307, in launch
    return await Launcher(options, **kwargs).launch()
  File "/opt/recipes/venv/lib/python3.9/site-packages/pyppeteer/launcher.py", line 148, in launch
    self.proc = subprocess.Popen(  # type: ignore
  File "/usr/local/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/share/pyppeteer/local-chromium/588429/chrome-linux/chrome'
```

**Comment by vabene1111** [comment]
pypepeteer is not downloading its needed chromium instance so it cannot perform the export. There is a recent issue somewhere detailing why this wont be fixed, i just cannot find where it is right now. If its just a config fix or something then anyone feel free to post it and i will implement it, but there wont be any special build or something.

**Comment by monster010** [comment]
I don't know if it's of any help to you, but I've tried around a bit.

I added chromium to the container and adjusted the launch parameters accordingly
```shell
browser = await launch(
            handleSIGINT=False,
            handleSIGTERM=False,
            handleSIGHUP=False,
            ignoreHTTPSErrors=True,
            executablePath="/usr/bin/chromium-browser",
            args=['--no-sandbox', '--disable-gpu']
        )
```

Now the problem was that the connection to the page i could be established
```shell
File "/opt/recipes/cookbook/integration/pdfexport.py", line 56, in get_files_from_recipes_async
    await page.goto('http://'+cmd.default_addr+':'+cmd.default_port+'/view/recipe/'+str(recipe.id), {'waitUntil': 'domcontentloaded'})
  File "/opt/recipes/venv/lib/python3.9/site-packages/pyppeteer/page.py", line 831, in goto
    raise PageError(result)
pyppeteer.errors.PageError: net::ERR_CONNECTION_REFUSED at http://127.0.0.1:8000/view/recipe/2
```

To remove the error, I simply removed the cmd.default_port parameter and set the correct hardcoded port.
The error I'm stuck on now is the following, maybe it will still help you to solve the error.

```shell
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/recipes/cookbook/integration/integration.py", line 77, in do_export
    files = self.get_files_from_recipes(recipes, el, self.request.COOKIES)
  File "/opt/recipes/cookbook/integration/pdfexport.py", line 71, in get_files_from_recipes
    return asyncio.run(self.get_files_from_recipes_async(recipes, el, cookie))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/recipes/cookbook/integration/pdfexport.py", line 56, in get_files_from_recipes_async
    await page.waitForSelector('#printReady');
  File "/opt/recipes/venv/lib/python3.9/site-packages/pyppeteer/frame_manager.py", line 855, in __await__
    raise result
pyppeteer.errors.TimeoutError: Waiting for selector "#printReady" failed: timeout 30000ms exceeds.
```

**Comment by boospy** [comment]
As there is no way to pass on cookery books at the moment to other people, one of these two things would be very helpful. 
https://github.com/TandoorRecipes/recipes/issues/1551
