### ISSUE TITLE
Search crashes after an update > 1.1.0

### ISSUE THREAD

**Issue by egneziel** [TandoorRecipes/recipes#1627]
### Tandoor Version

1.1.2

### Setup

Manual Setup

### Reverse Proxy

Apache2

### Bug description

After updating to 1.1.2 (from ~1.0.8) the search crashes when accessing the view (see log below).

I helped myself with a simple 
```
if not isinstance(kwargs[kw_filter], int):
   continue 
```
at recipe_search.py in front of the line 318 (`keywords = Keyword.objects.filter(pk__in=kwargs[kw_filter])`).

But maybe someone should investigate why kwargs[kw_filter] contains a bool-literal in my case?

### Relevant logs

```shell
Internal Server Error: /api/recipe/
Traceback (most recent call last):
  File "/var/www/recipes/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1823, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'false'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/www/recipes/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/var/www/recipes/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/recipes/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/www/recipes/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/www/recipes/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/var/www/recipes/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/www/recipes/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/var/www/recipes/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/recipes/cookbook/views/api.py", line 686, in list
    return super().list(request, *args, **kwargs)
  File "/var/www/recipes/lib/python3.9/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/var/www/recipes/cookbook/views/api.py", line 677, in get_querysetq
    self.queryset = search.get_queryset(self.queryset).prefetch_related('cooklog_set')
  File "/var/www/recipes/cookbook/helper/recipe_search.py", line 126, in get_queryset
    self.keyword_filters(**self._keywords)
  File "/var/www/recipes/cookbook/helper/recipe_search.py", line 318, in keyword_filters
    keywords = Keyword.objects.filter(pk__in=kwargs[kw_filter])
  File "/var/www/recipes/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/www/recipes/lib/python3.9/site-packages/django/db/models/query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/var/www/recipes/lib/python3.9/site-packages/django/db/models/query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/var/www/recipes/lib/python3.9/site-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/var/www/recipes/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1393, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/var/www/recipes/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1412, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/var/www/recipes/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1347, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/var/www/recipes/lib/python3.9/site-packages/django/db/models/sql/query.py", line 1193, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/var/www/recipes/lib/python3.9/site-packages/django/db/models/lookups.py", line 25, in __init__
    self.rhs = self.get_prep_lookup()
  File "/var/www/recipes/lib/python3.9/site-packages/django/db/models/lookups.py", line 240, in get_prep_lookup
    rhs_value = self.lhs.output_field.get_prep_value(rhs_value)
  File "/var/www/recipes/lib/python3.9/site-packages/django/db/models/fields/__init__.py", line 1825, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'false'.
```

**Comment by vabene1111** [comment]
you are running a manual setup so a few questions

- are you using postgres ?
- have you installed are requirements correctly
- have you migrated your database without any errors 
- is your python version up to date

other than that can you please hit the "reset" button on the search page and tell us if results are shown and after that which change in the search yields the error (which parameters).

is it possible to visit `api/recipe` without any parameters to see a list of recipes ?

**Comment by egneziel** [comment]
Thank you for you support! Somehow my error is fexed now. Oo

Regarding your questions:
>are you using postgres ?
- Yes. 
>have you installed are requirements correctly
- I think so. I followd the steps shown documentations section for manual setups. I got no errors during the update process.
>have you migrated your database without any errors
- I think so. Got no errors during migration process. I had a look at the migration table which list the new migration steps > 0169
>is your python version up to date
- Im running an venv 3.9 as suggested in the documentation. 

>other than that can you please hit the "reset" button on the search page and tell us if results are shown and after that which change in the search yields the error (which parameters).
- I tried that multiple times dirctly after i did the update this morning. The error occured every time i accessed the search. The only way to access my recipes was with help of the admin page or to open a recipe book.

You stated this is a setup issue. What i did now to reproduce the error is:
* undo my local code changes (if not isinstance(kwargs[kw_filter], int):  continue)
* eliminate the apache2 reverse proxy by binding guicorn directly to a local if (e.g. gunicorn --capture-output --bind 192.168.bla.bla:83 recipes.wsgi:application)

Now the strange thing: I cannot reproduce the error anymore. Even behind the apache2 reverse proxy and without the changes in recipe_search.py again the error is not reproducible anymore. 

I guess there was something wrong with my database. Maybe a wrong default value or a missing value somewhere? Because directly after i manged to get 1.1.2 running with the local code changes this morning i tested the search including the following steps:
* created a new keyword for on of the recipes
* changed and save the search setting of my user account to use Pharse searching
* added some fields to the full text index index and some to be handled fuzzy

Maybe one of these steps fixed my database? 
If you have further questions ill try to give as much info as possible. Otherwise feel free to close this issue.

**Comment by smilerz** [comment]
But maybe someone should investigate why kwargs[kw_filter] contains a bool-literal in my case?

The function that builds the search URL is ordered - if you were caching an old version of the front-end you the url was built in an order that the backend doesn't expect.
