### ISSUE TITLE
Exporting recipes fail:  AttributeError: 'Step' object has no attribute 'type'

### ISSUE THREAD

**Issue by 5oid** [TandoorRecipes/recipes#1658]
### Tandoor Version

 0.0.0 (revision: 030d977a8c79606ca1fb7487efdb7f6aa34b8250 from 2022-03-02))

### Setup

Manual Setup

### Reverse Proxy

No reverse proxy

### Bug description

If I export recipes via Saffron or via Recipe Sage,  the operation fails with an message box on the web site saying "There was an error loading a resource!".  The log file   gunicorn_err.log says: "AttributeError: 'Step' object has no attribute 'type'".  See more log files below for more context.  Do you have any idea what is wrong?

### Relevant logs

```shell
If recipe export is done via Saffron,  I found the error below in gunicorn_err.log:

[2022-03-19 23:01:09 +0100] [1583] [DEBUG] POST /export/
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/var/www/recipes/cookbook/integration/integration.py", line 77, in do_export
    files = self.get_files_from_recipes(recipes, el, self.request.COOKIES)
  File "/var/www/recipes/cookbook/integration/saffron.py", line 93, in get_files_from_recipes
    filename, data = self.get_file_from_recipe(r)
  File "/var/www/recipes/cookbook/integration/saffron.py", line 74, in get_file_from_recipe
    if s.type != Step.TIME:
AttributeError: 'Step' object has no attribute 'type'


When exporting a recipe via Recipe Sage, the error below appears in the gunicorn_err.log:
[2022-03-19 23:04:13 +0100] [1583] [DEBUG] POST /export/
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/var/www/recipes/cookbook/integration/integration.py", line 77, in do_export
    files = self.get_files_from_recipes(recipes, el, self.request.COOKIES)
  File "/var/www/recipes/cookbook/integration/recipesage.py", line 94, in get_files_from_recipes
    json_list.append(self.get_file_from_recipe(r))
  File "/var/www/recipes/cookbook/integration/recipesage.py", line 80, in get_file_from_recipe
    if s.type != Step.TIME:
AttributeError: 'Step' object has no attribute 'type'
```

**Comment by vabene1111** [comment]
yes i think i might have missed those exporters when removing the type flag from steps. Wil take a look, thank you
