### ISSUE TITLE
TypeError by API call createRecipe 

### ISSUE THREAD

**Issue by ignis-draco** [TandoorRecipes/recipes#1728]
### Tandoor Version

1.1.4

### Setup

Manual Setup

### Reverse Proxy

No reverse proxy

### Bug description

Hi, 

I get a TypeError when I try to create a recipe through the API. 
I tested the whole thing with a freshly installed Tandoor. 

JSON: 
```{
    "name": "Asiatische Hähnchenpfanne ",
    "description": "mit Pak Choi, Paprika und Kokosreis",
    "keywords": [
        {
            "name": "family",
            "icon": null,
            "description": ""
        }
    ],
    "steps": [
        {
            "name": "Los geht's",
            "instruction": "Wasche Gemüse und Kräuter ab und tupfe das Fleisch mit Küchenpapier trocken. Erhitze 200 ml [300 ml | 400 ml] Wasser im Wasserkocher.",
            "ingredients": [
                {
                    "food": {
                        "name": "Kokosmilch",
                        "description": "",
                        "recipe": null,
                        "food_onhand": "false",
                        "supermarket_category": null,
                        "inherit_fields": null,
                        "ignore_shopping": false
                    },
                    "unit": {
                        "name": "ml",
                        "description": null
                    },
                    "amount": "150.0",
                    "note": "",
                    "order": 0,
                    "is_header": false,
                    "no_amount": false
                },
                {
                    "food": {
                        "name": "Knoblauchzehe",
                        "description": "",
                        "recipe": null,
                        "food_onhand": "false",
                        "supermarket_category": null,
                        "inherit_fields": null,
                        "ignore_shopping": false
                    },
                    "unit": {
                        "name": "Stk.",
                        "description": null
                    },
                    "amount": "1.0",
                    "note": "",
                    "order": 0,
                    "is_header": false,
                    "no_amount": false
                },
                {
                    "food": {
                        "name": "Sojasoße",
                        "description": "",
                        "recipe": null,
                        "food_onhand": "false",
                        "supermarket_category": null,
                        "inherit_fields": null,
                        "ignore_shopping": false
                    },
                    "unit": {
                        "name": "Stk.",
                        "description": null
                    },
                    "amount": "1.0",
                    "note": "",
                    "order": 0,
                    "is_header": false,
                    "no_amount": false
                },
                {
                    "food": {
                        "name": "Frühlingszwiebel",
                        "description": "",
                        "recipe": null,
                        "food_onhand": "false",
                        "supermarket_category": null,
                        "inherit_fields": null,
                        "ignore_shopping": false
                    },
                    "unit": {
                        "name": "Stk.",
                        "description": null
                    },
                    "amount": "1.0",
                    "note": "",
                    "order": 0,
                    "is_header": false,
                    "no_amount": false
                },
                {
                    "food": {
                        "name": "Baby-Pak-Choi",
                        "description": "",
                        "recipe": null,
                        "food_onhand": "false",
                        "supermarket_category": null,
                        "inherit_fields": null,
                        "ignore_shopping": false
                    },
                    "unit": {
                        "name": "Stk.",
                        "description": null
                    },
                    "amount": "2.0",
                    "note": "",
                    "order": 0,
                    "is_header": false,
                    "no_amount": false
                },
                {
                    "food": {
                        "name": "Basmatireis",
                        "description": "",
                        "recipe": null,
                        "food_onhand": "false",
                        "supermarket_category": null,
                        "inherit_fields": null,
                        "ignore_shopping": false
                    },
                    "unit": {
                        "name": "g",
                        "description": null
                    },
                    "amount": "150.0",
                    "note": "",
                    "order": 0,
                    "is_header": false,
                    "no_amount": false
                },
                {
                    "food": {
                        "name": "Honig",
                        "description": "",
                        "recipe": null,
                        "food_onhand": "false",
                        "supermarket_category": null,
                        "inherit_fields": null,
                        "ignore_shopping": false
                    },
                    "unit": {
                        "name": "g",
                        "description": null
                    },
                    "amount": "8.0",
                    "note": "",
                    "order": 0,
                    "is_header": false,
                    "no_amount": false
                },
                {
                    "food": {
                        "name": "Ingwer",
                        "description": "",
                        "recipe": null,
                        "food_onhand": "false",
                        "supermarket_category": null,
                        "inherit_fields": null,
                        "ignore_shopping": false
                    },
                    "unit": {
                        "name": "g",
                        "description": null
                    },
                    "amount": "15.0",
                    "note": "",
                    "order": 0,
                    "is_header": false,
                    "no_amount": false
                },
                {
                    "food": {
                        "name": "Paprika",
                        "description": "",
                        "recipe": null,
                        "food_onhand": "false",
                        "supermarket_category": null,
                        "inherit_fields": null,
                        "ignore_shopping": false
                    },
                    "unit": {
                        "name": "Stk.",
                        "description": null
                    },
                    "amount": "1.0",
                    "note": "",
                    "order": 0,
                    "is_header": false,
                    "no_amount": false
                },
                {
                    "food": {
                        "name": "Hähnchenbrustfilet",
                        "description": "",
                        "recipe": null,
                        "food_onhand": "false",
                        "supermarket_category": null,
                        "inherit_fields": null,
                        "ignore_shopping": false
                    },
                    "unit": {
                        "name": "g",
                        "description": null
                    },
                    "amount": "250.0",
                    "note": "",
                    "order": 0,
                    "is_header": false,
                    "no_amount": false
                }
            ],
            "time": 0,
            "order": 0,
            "show_as_header": true,
            "file": null,
            "step_recipe": null
        },
        {
            "name": "Reis garen",
            "instruction": "Reis in einem Sieb mit kaltem Wasser abspülen, bis dieses klar hindurchfließt. 200 mi [300 mi | 400 ml] heißes Wasser und Kokosmilch in einem kleinen Topf zum Kochen bringen, salzen, Reis einrühren und beischwacher Hitze 10 Min. köcheln lassen. Anschließend mit aufgesetztem Deckel 10 Min. ziehen lassen.",
            "ingredients": [],
            "time": 0,
            "order": 1,
            "show_as_header": true,
            "file": null,
            "step_recipe": null
        },
        {
            "name": "In der Zwischenzeit",
            "instruction": "Paprika halbieren, Kerngehäuse entfernen und Paprikahälften in 0,5 cm breite Streifen schneiden. Strunk vom Pak Choi ca. 1 cm abschneiden. Pak Choi in 2-3 cm große Stücke schneiden. Weißen und grünen Teil der Frühlingszwiebel getrennt voneinander in Ringe schneiden.",
            "ingredients": [],
            "time": 0,
            "order": 2,
            "show_as_header": true,
            "file": null,
            "step_recipe": null
        },
        {
            "name": "Teriyakisoße zubereiten",
            "instruction": "Knoblauch abziehen und in eine kleine Schüssel pressen. Die Hälfte [zwei Drittel | den Ganzen] Ingwer schälen, fein reiben und zum Knoblauch geben. Sojasoße, Honig und 1EL[1,5 EL |2 EL] Wasser zum Knoblauch geben und vermischen.",
            "ingredients": [],
            "time": 0,
            "order": 3,
            "show_as_header": true,
            "file": null,
            "step_recipe": null
        },
        {
            "name": "Hähnchenstreifen anbraten",
            "instruction": "Hähnchenbrust in mundgerechte Stücke schneiden. In einer großen Pfanne 1EL[1,5 EL|2 EL] Öl bei starker Hitze erwärmen und Hähnchenbruststücke darin 3-4 Min. anbraten.",
            "ingredients": [],
            "time": 0,
            "order": 4,
            "show_as_header": true,
            "file": null,
            "step_recipe": null
        },
        {
            "name": "Gemüse anbraten",
            "instruction": "Anschließend Hitze reduzieren und Paprikastreifen, Pak Choi und weiße Frühlingszwiebelringe unterrühren und weitere 4 Min. anbraten. Teriyakisoße dazugießen und alles 3 -4 Min. kochen lassen, bis das Gemüse weich ist.",
            "ingredients": [],
            "time": 0,
            "order": 5,
            "show_as_header": true,
            "file": null,
            "step_recipe": null
        },
        {
            "name": "Pfanne vollenden",
            "instruction": "Reis mit einer Gabel auflockern und auf Teller verteilen. Hähnchenpfanne darauf anrichten, grüne Frühlingszwiebelringe darüberstreuen und genießen. Guten Appetit",
            "ingredients": [],
            "time": 0,
            "order": 6,
            "show_as_header": true,
            "file": null,
            "step_recipe": null
        }
    ],
    "working_time": 40,
    "waiting_time": 0,
    "internal": true,
    "nutrition": null,
    "servings": 2,
    "file_path": "",
    "servings_text": ""
}
```

### Relevant logs

```shell

Environment:


Request Method: POST
Request URL: http://192.168.10.203:8002/api/recipe/

Django Version: 3.2.12
Python Version: 3.9.2
Installed Applications:
['dal',
 'dal_select2',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'django.contrib.postgres',
 'django_prometheus',
 'django_tables2',
 'corsheaders',
 'django_filters',
 'crispy_forms',
 'rest_framework',
 'rest_framework.authtoken',
 'django_cleanup.apps.CleanupConfig',
 'webpack_loader',
 'django_js_reverse',
 'hcaptcha',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'cookbook.apps.CookbookConfig',
 'treebeard']
Installed Middleware:
['corsheaders.middleware.CorsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'cookbook.helper.scope_middleware.ScopeMiddleware']



Traceback (most recent call last):
  File "/var/www/recipes/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/var/www/recipes/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/recipes/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/www/recipes/lib/python3.9/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/www/recipes/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/var/www/recipes/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/www/recipes/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/var/www/recipes/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/recipes/lib/python3.9/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/var/www/recipes/lib/python3.9/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/var/www/recipes/lib/python3.9/site-packages/drf_writable_nested/mixins.py", line 232, in save
    return super(BaseNestedModelSerializer, self).save(**kwargs)
  File "/var/www/recipes/lib/python3.9/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/var/www/recipes/cookbook/serializer.py", line 626, in create
    return super().create(validated_data)
  File "/var/www/recipes/lib/python3.9/site-packages/drf_writable_nested/mixins.py", line 260, in create
    self.update_or_create_reverse_relations(instance, reverse_relations)
  File "/var/www/recipes/lib/python3.9/site-packages/drf_writable_nested/mixins.py", line 187, in update_or_create_reverse_relations
    related_instance = serializer.save(**save_kwargs)
  File "/var/www/recipes/lib/python3.9/site-packages/drf_writable_nested/mixins.py", line 232, in save
    return super(BaseNestedModelSerializer, self).save(**kwargs)
  File "/var/www/recipes/lib/python3.9/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/var/www/recipes/cookbook/serializer.py", line 506, in create
    return super().create(validated_data)
  File "/var/www/recipes/lib/python3.9/site-packages/drf_writable_nested/mixins.py", line 260, in create
    self.update_or_create_reverse_relations(instance, reverse_relations)
  File "/var/www/recipes/lib/python3.9/site-packages/drf_writable_nested/mixins.py", line 187, in update_or_create_reverse_relations
    related_instance = serializer.save(**save_kwargs)
  File "/var/www/recipes/lib/python3.9/site-packages/drf_writable_nested/mixins.py", line 232, in save
    return super(BaseNestedModelSerializer, self).save(**kwargs)
  File "/var/www/recipes/lib/python3.9/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/var/www/recipes/cookbook/serializer.py", line 482, in create
    return super().create(validated_data)
  File "/var/www/recipes/lib/python3.9/site-packages/drf_writable_nested/mixins.py", line 252, in create
    self.update_or_create_direct_relations(
  File "/var/www/recipes/lib/python3.9/site-packages/drf_writable_nested/mixins.py", line 223, in update_or_create_direct_relations
    attrs[field_source] = serializer.save(
  File "/var/www/recipes/lib/python3.9/site-packages/drf_writable_nested/mixins.py", line 232, in save
    return super(BaseNestedModelSerializer, self).save(**kwargs)
  File "/var/www/recipes/lib/python3.9/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/var/www/recipes/cookbook/serializer.py", line 443, in create
    obj, created = Food.objects.get_or_create(name=name, space=space, defaults=validated_data)
  File "/var/www/recipes/cookbook/models.py", line 80, in get_or_create
    for related_obj in many_to_many[field]:

Exception Type: TypeError at /api/recipe/
Exception Value: 'NoneType' object is not iterable
```

**Comment by vabene1111** [comment]
This appears to be part of the default TreeManager `get_or_create` implementation. 

I currently dont know what causes this but i know the application uses the API as well and everything works so you might be able to create the foods first via the api and then link them using their ID's. To actually fix this i will need some time to dig into first your api call and the TreeManager get or create function.

**Comment by ignis-draco** [comment]
How can I link the ingredients to a step? 
I can't find anything in the API documentation. 

Do I simply have to extend the ingredients object with "id":<number>?

**Comment by vabene1111** [comment]
i would recommend using the specific food endpoint `createFood` to create foods and `createUnit` for units and after that use the create recipe endpoint as you did before but, maybe with the correct ids for the foods.

**Comment by ignis-draco** [comment]
Hi, 

I have now managed to create over 130 recipes. 
The workaround to create the food entry separately and then only the recipe has worked well and reliably.
