### ISSUE TITLE
IntegrityError when viewing recipe directly after reverse proxy auth

### ISSUE THREAD

**Issue by andrinbr** [TandoorRecipes/recipes#1749]
### Tandoor Version

1.1.4

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Bug description

When using Reverse Proxy Auth and directly opening a recipe (https://recipes.domain.tld/view/recipe/4/429232ff-db7d-480a-b9ee-fc9a642e373f), the request fails the first time with:
"null value in column "space_id" violates not-null constraint"

Simply refreshing the page solves the issue. It only happends if the user is not authenticated before and tires to directly access a recipe. After the authentication happend, the user gets redirected to the recipe and this error shows up.
Accessing the main page works fine.

Log/Settings:
[IntegrityError at _view_recipe_4_429232ff-db7d-480a-b9ee-fc9a642e373f.pdf](https://github.com/TandoorRecipes/recipes/files/8594139/IntegrityError.at._view_recipe_4_429232ff-db7d-480a-b9ee-fc9a642e373f.pdf)

### Relevant logs

```shell
Environment:

Request Method: GET
Request URL: https://recipes.domain.tld/view/recipe/4/429232ff-db7d-480a-b9ee-fc9a642e373f

Django Version: 3.2.12
Python Version: 3.10.2
Installed Applications:
['dal',
 'dal_select2',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'django.contrib.postgres',
 'django_prometheus',
 'django_tables2',
 'corsheaders',
 'django_filters',
 'crispy_forms',
 'rest_framework',
 'rest_framework.authtoken',
 'django_cleanup.apps.CleanupConfig',
 'webpack_loader',
 'django_js_reverse',
 'hcaptcha',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'cookbook.apps.CookbookConfig',
 'treebeard']
Installed Middleware:
['corsheaders.middleware.CorsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'cookbook.helper.scope_middleware.ScopeMiddleware',
 'recipes.middleware.CustomRemoteUser']



Traceback (most recent call last):
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)

The above exception (null value in column "space_id" violates not-null constraint
DETAIL:  Failing row contains (37, 2022-04-29 09:54:59.734372+00, 2, 4, null).
) was the direct cause of the following exception:
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/recipes/cookbook/views/views.py", line 206, in recipe_view
    ViewLog.objects.create(recipe=recipe, created_by=request.user, space=request.space)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/base.py", line 739, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/base.py", line 776, in save_base
    updated = self._save_table(
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/base.py", line 881, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django_prometheus/models.py", line 43, in _do_insert
    return super()._do_insert(*args, **kwargs)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/base.py", line 919, in _do_insert
    return manager._insert(
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute
    with self.db.wrap_database_errors:
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)

Exception Type: IntegrityError at /view/recipe/4/429232ff-db7d-480a-b9ee-fc9a642e373f
Exception Value: null value in column "space_id" violates not-null constraint
DETAIL:  Failing row contains (37, 2022-04-29 09:54:59.734372+00, 2, 4, null).
```

**Comment by vabene1111** [comment]
this might be related to the order in which the middlewares process the request, i will look into this

**Comment by vabene1111** [comment]
i have changed the order of the reverse auth middleware that should now process the request in the correct order, please let me know if this helpted after the next release
