### ISSUE TITLE
Cookmate Import not working as expected

### ISSUE THREAD

**Issue by allesauseinerhand** [TandoorRecipes/recipes#1772]
### Tandoor Version

1.2.3

### Setup

Synology

### Reverse Proxy

Others (please state below)

### Other

Synology Reverse Proxy

### Bug description

Hi,

First of all a very big thank you for supporting Cookmate Recipes import.

But I struggle to get it work. I tried to import the following mcb file: [my_cookbook2022_05_04_22_07_31.zip](https://github.com/TandoorRecipes/recipes/files/8626929/my_cookbook2022_05_04_22_07_31.zip)

The recipes are imported partially but in strange ways. I uploaded a short video to YouTube ([Link](https://youtu.be/DaClFb_PglY)), in which I'm going through the import process to. And I attached also the logs containing the error message "'NoneType' object has no attribute 'strip'".

Can you give me an advice what's going on?

Regards,
Björn

### Relevant logs

```shell
2022-05-04T20:08:57.150426647Z 172.25.0.2 - - [04/May/2022:22:08:57 +0200] "GET /api/meal-plan/?from_date=2022-05-04&to_date=2022-05-04 HTTP/1.0" 200 2 "https://koch.melbjo.myds.me/search/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:08:57.274095888Z 172.25.0.2 - - [04/May/2022:22:08:57 +0200] "GET /api/recipe/?query=&internal=false&random=false&new=true&page=1&page_size=25&include_children=true&num_recent=5 HTTP/1.0" 200 3623 "https://koch.melbjo.myds.me/search/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:08:59.177482062Z 172.25.0.2 - - [04/May/2022:22:08:59 +0200] "GET /service-worker.js HTTP/1.0" 200 54553 "https://koch.melbjo.myds.me/service-worker.js" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:11:42.217518393Z 172.25.0.2 - - [04/May/2022:22:11:42 +0200] "GET /data/import/url HTTP/1.0" 200 19247 "https://koch.melbjo.myds.me/search/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:11:42.791470456Z 172.25.0.2 - - [04/May/2022:22:11:42 +0200] "GET /manifest.json HTTP/1.0" 200 1325 "https://koch.melbjo.myds.me/data/import/url" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:11:44.471214363Z 172.25.0.2 - - [04/May/2022:22:11:44 +0200] "GET /service-worker.js HTTP/1.0" 200 54553 "https://koch.melbjo.myds.me/service-worker.js" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:11:59.413944241Z 172.25.0.2 - - [04/May/2022:22:11:59 +0200] "POST /import/ HTTP/1.0" 200 16 "https://koch.melbjo.myds.me/data/import/url" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:11:59.463300370Z 172.25.0.2 - - [04/May/2022:22:11:59 +0200] "GET /import-response/7/ HTTP/1.0" 200 19186 "https://koch.melbjo.myds.me/data/import/url" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:11:59.506096182Z Traceback (most recent call last):
2022-05-04T20:11:59.506362336Z   File "/opt/recipes/cookbook/integration/integration.py", line 173, in do_import
2022-05-04T20:11:59.506428826Z     recipe = self.get_recipe_from_file(z)
2022-05-04T20:11:59.506461589Z   File "/opt/recipes/cookbook/integration/cookmate.py", line 42, in get_recipe_from_file
2022-05-04T20:11:59.506511610Z     recipe.source_url = recipe_xml.find('url').text.strip()
2022-05-04T20:11:59.506545591Z AttributeError: 'NoneType' object has no attribute 'strip'
2022-05-04T20:11:59.555697293Z Traceback (most recent call last):
2022-05-04T20:11:59.555841611Z   File "/opt/recipes/cookbook/integration/integration.py", line 173, in do_import
2022-05-04T20:11:59.555881229Z     recipe = self.get_recipe_from_file(z)
2022-05-04T20:11:59.555910410Z   File "/opt/recipes/cookbook/integration/cookmate.py", line 38, in get_recipe_from_file
2022-05-04T20:11:59.555943912Z     recipe.servings = parse_servings(recipe_xml.find('quantity').text.strip())
2022-05-04T20:11:59.555981550Z AttributeError: 'NoneType' object has no attribute 'strip'
2022-05-04T20:11:59.737369168Z 172.25.0.2 - - [04/May/2022:22:11:59 +0200] "GET /api/import-log/7/ HTTP/1.0" 200 167 "https://koch.melbjo.myds.me/import-response/7/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:11:59.842261277Z 172.25.0.2 - - [04/May/2022:22:11:59 +0200] "GET /manifest.json HTTP/1.0" 200 1325 "https://koch.melbjo.myds.me/import-response/7/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:12:01.344265264Z 172.25.0.2 - - [04/May/2022:22:12:01 +0200] "GET /service-worker.js HTTP/1.0" 200 54553 "https://koch.melbjo.myds.me/service-worker.js" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:12:02.511008706Z Traceback (most recent call last):
2022-05-04T20:12:02.511477033Z   File "/opt/recipes/cookbook/integration/integration.py", line 173, in do_import
2022-05-04T20:12:02.511531485Z     recipe = self.get_recipe_from_file(z)
2022-05-04T20:12:02.511563854Z   File "/opt/recipes/cookbook/integration/cookmate.py", line 35, in get_recipe_from_file
2022-05-04T20:12:02.511597365Z     recipe.waiting_time = parse_time(recipe_xml.find('cooktime').text.strip())
2022-05-04T20:12:02.511630862Z AttributeError: 'NoneType' object has no attribute 'strip'
2022-05-04T20:12:04.740201962Z 172.25.0.2 - - [04/May/2022:22:12:04 +0200] "GET /api/import-log/7/ HTTP/1.0" 200 839 "https://koch.melbjo.myds.me/import-response/7/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:13:10.444352520Z 172.25.0.2 - - [04/May/2022:22:13:10 +0200] "GET /search/ HTTP/1.0" 200 19245 "https://koch.melbjo.myds.me/import-response/7/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:13:11.225818419Z 172.25.0.2 - - [04/May/2022:22:13:11 +0200] "GET /api/meal-plan/?from_date=2022-05-04&to_date=2022-05-04 HTTP/1.0" 200 2 "https://koch.melbjo.myds.me/search/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:13:11.245883970Z 172.25.0.2 - - [04/May/2022:22:13:11 +0200] "GET /api/keyword/?query=&root=0&page=1&page_size=50 HTTP/1.0" 200 267 "https://koch.melbjo.myds.me/search/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:13:11.262029192Z 172.25.0.2 - - [04/May/2022:22:13:11 +0200] "GET /api/custom-filter/ HTTP/1.0" 200 2 "https://koch.melbjo.myds.me/search/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:13:11.278494809Z 172.25.0.2 - - [04/May/2022:22:13:11 +0200] "GET /api/recipe-book/ HTTP/1.0" 200 2 "https://koch.melbjo.myds.me/search/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:13:11.796786339Z 172.25.0.2 - - [04/May/2022:22:13:11 +0200] "GET /api/food/?query=&root=0&page=1&page_size=50 HTTP/1.0" 200 17589 "https://koch.melbjo.myds.me/search/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:13:11.812142433Z 172.25.0.2 - - [04/May/2022:22:13:11 +0200] "GET /api/meal-plan/?from_date=2022-05-04&to_date=2022-05-04 HTTP/1.0" 200 2 "https://koch.melbjo.myds.me/search/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:13:11.815506699Z 172.25.0.2 - - [04/May/2022:22:13:11 +0200] "GET /manifest.json HTTP/1.0" 200 1325 "https://koch.melbjo.myds.me/search/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:13:11.959305060Z 172.25.0.2 - - [04/May/2022:22:13:11 +0200] "GET /api/recipe/?query=&internal=false&random=false&new=true&page=1&page_size=25&include_children=true&num_recent=5 HTTP/1.0" 200 5130 "https://koch.melbjo.myds.me/search/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:13:14.114780703Z 172.25.0.2 - - [04/May/2022:22:13:14 +0200] "GET /service-worker.js HTTP/1.0" 200 54553 "https://koch.melbjo.myds.me/service-worker.js" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:14:09.616179074Z 172.25.0.2 - - [04/May/2022:22:14:09 +0200] "GET /search/ HTTP/1.0" 200 19245 "https://koch.melbjo.myds.me/import-response/7/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:14:09.991943657Z 172.25.0.2 - - [04/May/2022:22:14:09 +0200] "GET /api/custom-filter/ HTTP/1.0" 200 2 "https://koch.melbjo.myds.me/search/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:14:10.007495185Z 172.25.0.2 - - [04/May/2022:22:14:10 +0200] "GET /api/meal-plan/?from_date=2022-05-04&to_date=2022-05-04 HTTP/1.0" 200 2 "https://koch.melbjo.myds.me/search/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:14:10.542622550Z 172.25.0.2 - - [04/May/2022:22:14:10 +0200] "GET /api/food/?query=&root=0&page=1&page_size=50 HTTP/1.0" 200 17589 "https://koch.melbjo.myds.me/search/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:14:10.580724596Z 172.25.0.2 - - [04/May/2022:22:14:10 +0200] "GET /api/keyword/?query=&root=0&page=1&page_size=50 HTTP/1.0" 200 267 "https://koch.melbjo.myds.me/search/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:14:10.618595815Z 172.25.0.2 - - [04/May/2022:22:14:10 +0200] "GET /api/recipe-book/ HTTP/1.0" 200 2 "https://koch.melbjo.myds.me/search/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:14:10.647487453Z 172.25.0.2 - - [04/May/2022:22:14:10 +0200] "GET /api/meal-plan/?from_date=2022-05-04&to_date=2022-05-04 HTTP/1.0" 200 2 "https://koch.melbjo.myds.me/search/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:14:10.697597892Z 172.25.0.2 - - [04/May/2022:22:14:10 +0200] "GET /manifest.json HTTP/1.0" 200 1325 "https://koch.melbjo.myds.me/search/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:14:10.823815648Z 172.25.0.2 - - [04/May/2022:22:14:10 +0200] "GET /api/recipe/?query=&internal=false&random=false&new=true&page=1&page_size=25&include_children=true&num_recent=5 HTTP/1.0" 200 5130 "https://koch.melbjo.myds.me/search/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:14:12.584590739Z 172.25.0.2 - - [04/May/2022:22:14:12 +0200] "GET /service-worker.js HTTP/1.0" 200 54553 "https://koch.melbjo.myds.me/service-worker.js" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:14:31.093448532Z 172.25.0.2 - - [04/May/2022:22:14:31 +0200] "GET /view/recipe/350 HTTP/1.0" 200 20294 "https://koch.melbjo.myds.me/search/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:14:32.087538047Z 172.25.0.2 - - [04/May/2022:22:14:32 +0200] "GET /api/recipe/350/?share=None HTTP/1.0" 200 14622 "https://koch.melbjo.myds.me/view/recipe/350" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:14:32.090580493Z 172.25.0.2 - - [04/May/2022:22:14:32 +0200] "GET /manifest.json HTTP/1.0" 200 1325 "https://koch.melbjo.myds.me/view/recipe/350" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:14:32.179141306Z 172.25.0.2 - - [04/May/2022:22:14:32 +0200] "GET /api/meal-plan/?from_date=2022-05-04&to_date=2022-05-04 HTTP/1.0" 200 2 "https://koch.melbjo.myds.me/view/recipe/350" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:14:32.219460491Z 172.25.0.2 - - [04/May/2022:22:14:32 +0200] "GET /api/recipe/350/related/?levels=2&format=json HTTP/1.0" 200 2 "https://koch.melbjo.myds.me/view/recipe/350" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:14:32.814321216Z 172.25.0.2 - - [04/May/2022:22:14:32 +0200] "GET /api/recipe/350/ HTTP/1.0" 200 14622 "https://koch.melbjo.myds.me/view/recipe/350" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:14:33.840443076Z 172.25.0.2 - - [04/May/2022:22:14:33 +0200] "GET /service-worker.js HTTP/1.0" 200 54553 "https://koch.melbjo.myds.me/service-worker.js" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:14:34.417369052Z 172.25.0.2 - - [04/May/2022:22:14:34 +0200] "GET /view/recipe/351 HTTP/1.0" 200 20245 "https://koch.melbjo.myds.me/search/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:14:34.914116408Z 172.25.0.2 - - [04/May/2022:22:14:34 +0200] "GET /api/recipe/351/?share=None HTTP/1.0" 200 365 "https://koch.melbjo.myds.me/view/recipe/351" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:14:34.981053697Z 172.25.0.2 - - [04/May/2022:22:14:34 +0200] "GET /api/meal-plan/?from_date=2022-05-04&to_date=2022-05-04 HTTP/1.0" 200 2 "https://koch.melbjo.myds.me/view/recipe/351" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:14:35.022198593Z 172.25.0.2 - - [04/May/2022:22:14:35 +0200] "GET /api/recipe/351/related/?levels=2&format=json HTTP/1.0" 200 2 "https://koch.melbjo.myds.me/view/recipe/351" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:14:35.039307045Z 172.25.0.2 - - [04/May/2022:22:14:35 +0200] "GET /manifest.json HTTP/1.0" 200 1325 "https://koch.melbjo.myds.me/view/recipe/351" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:14:35.067328121Z 172.25.0.2 - - [04/May/2022:22:14:35 +0200] "GET /api/recipe/351/ HTTP/1.0" 200 365 "https://koch.melbjo.myds.me/view/recipe/351" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:14:36.643907122Z 172.25.0.2 - - [04/May/2022:22:14:36 +0200] "GET /service-worker.js HTTP/1.0" 200 54553 "https://koch.melbjo.myds.me/service-worker.js" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:15:24.717425561Z 172.25.0.2 - - [04/May/2022:22:15:24 +0200] "GET /view/recipe/346 HTTP/1.0" 200 20261 "https://koch.melbjo.myds.me/search/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:15:25.069787309Z 172.25.0.2 - - [04/May/2022:22:15:25 +0200] "GET /api/recipe/346/?share=None HTTP/1.0" 200 381 "https://koch.melbjo.myds.me/view/recipe/346" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:15:25.077583414Z 172.25.0.2 - - [04/May/2022:22:15:25 +0200] "GET /manifest.json HTTP/1.0" 200 1325 "https://koch.melbjo.myds.me/view/recipe/346" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:15:25.160824237Z 172.25.0.2 - - [04/May/2022:22:15:25 +0200] "GET /api/recipe/346/related/?levels=2&format=json HTTP/1.0" 200 2 "https://koch.melbjo.myds.me/view/recipe/346" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:15:25.176496885Z 172.25.0.2 - - [04/May/2022:22:15:25 +0200] "GET /api/meal-plan/?from_date=2022-05-04&to_date=2022-05-04 HTTP/1.0" 200 2 "https://koch.melbjo.myds.me/view/recipe/346" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:15:25.219815370Z 172.25.0.2 - - [04/May/2022:22:15:25 +0200] "GET /api/recipe/346/ HTTP/1.0" 200 381 "https://koch.melbjo.myds.me/view/recipe/346" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:15:26.665215240Z 172.25.0.2 - - [04/May/2022:22:15:26 +0200] "GET /service-worker.js HTTP/1.0" 200 54553 "https://koch.melbjo.myds.me/service-worker.js" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:15:26.723028018Z 172.25.0.2 - - [04/May/2022:22:15:26 +0200] "GET /manifest.json HTTP/1.0" 200 1325 "https://koch.melbjo.myds.me/search/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:15:27.167432662Z 172.25.0.2 - - [04/May/2022:22:15:27 +0200] "GET /api/recipe/?query=&internal=false&random=false&new=true&page=1&page_size=25&include_children=true&num_recent=5 HTTP/1.0" 200 5133 "https://koch.melbjo.myds.me/search/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:15:28.844725258Z 172.25.0.2 - - [04/May/2022:22:15:28 +0200] "GET /service-worker.js HTTP/1.0" 200 54553 "https://koch.melbjo.myds.me/service-worker.js" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:15:30.136531852Z 172.25.0.2 - - [04/May/2022:22:15:30 +0200] "GET /view/recipe/347 HTTP/1.0" 200 20271 "https://koch.melbjo.myds.me/search/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:15:30.952529308Z 172.25.0.2 - - [04/May/2022:22:15:30 +0200] "GET /api/recipe/347/?share=None HTTP/1.0" 200 18782 "https://koch.melbjo.myds.me/view/recipe/347" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:15:30.956235214Z 172.25.0.2 - - [04/May/2022:22:15:30 +0200] "GET /manifest.json HTTP/1.0" 200 1325 "https://koch.melbjo.myds.me/view/recipe/347" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:15:31.073919857Z 172.25.0.2 - - [04/May/2022:22:15:31 +0200] "GET /api/recipe/347/related/?levels=2&format=json HTTP/1.0" 200 2 "https://koch.melbjo.myds.me/view/recipe/347" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:15:31.091422463Z 172.25.0.2 - - [04/May/2022:22:15:31 +0200] "GET /api/meal-plan/?from_date=2022-05-04&to_date=2022-05-04 HTTP/1.0" 200 2 "https://koch.melbjo.myds.me/view/recipe/347" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:15:31.749265895Z 172.25.0.2 - - [04/May/2022:22:15:31 +0200] "GET /api/recipe/347/ HTTP/1.0" 200 18782 "https://koch.melbjo.myds.me/view/recipe/347" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
2022-05-04T20:15:31.876518703Z 172.25.0.2 - - [04/May/2022:22:15:31 +0200] "GET /service-worker.js HTTP/1.0" 200 54553 "https://koch.melbjo.myds.me/service-worker.js" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
```

**Comment by scepbjoern** [comment]
Sorry, I just saw, that I was logged in with my wrong github account. My normal account which I'm also using for sponsoring your project is scepbjoern.

**Comment by vabene1111** [comment]
i always test the importers with a limited set of sample data, so it might be that your mcb contains a few recipes that trigger some kind of edge case that i did not notice during testing. I will test your file and fix the issues you are describing, usually just small things :) thanks for the sponsor btw

**Comment by scepbjoern** [comment]
Thanks for fixing this!!! There are still 2 problems left, for which I opened a new issue #1820.
