### ISSUE TITLE
Beta: Copy Invite Link broken

### ISSUE THREAD

**Issue by tomtjes** [TandoorRecipes/recipes#1897]
### Tandoor Version

beta

### Setup

Others (please state below)

### Reverse Proxy

No reverse proxy

### Other

local Portainer

### Bug description

After creating an invite to a space, the _copy link_ and _copy token_ menu items do nothing.

**Comment by vabene1111** [comment]
interesting its working perfectly fine on windows but maybe safari has some clipboard things, i will look into this, thanks :)

**Comment by vabene1111** [comment]
i don't have a safari/macos browser to test this, can you open the browser console and see if any error messages are shown when you click on copy buttons

**Comment by tomtjes** [comment]
Does this help?

```
[Warning] service worker not in navigator (2, line 422)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (style.min.css.map, line 0)
[Error] TypeError: undefined is not an object (evaluating 'navigator.clipboard.writeText')
copyToClipboard — space_manage_view.js:1:243106
copyToClipboard
at — chunk-vendors.js:1054:11805
at — chunk-vendors.js:1054:11805
(anonymous function) — chunk-vendors.js:1054:26699
onClick — chunk-vendors.js:8:206689
onClick
at — chunk-vendors.js:1054:11805
(anonymous function) — chunk-vendors.js:8:82351
forEach
onClick — chunk-vendors.js:8:82330
onClick
at — chunk-vendors.js:1054:11805

	ut (chunk-vendors.js:1054:12183)
	st (chunk-vendors.js:1054:12094)
	ot (chunk-vendors.js:1054:11739)
	at (chunk-vendors.js:1054:11942)
	at (chunk-vendors.js:1054:11805)
	(anonymous function) (chunk-vendors.js:1054:26699)
	onClick (chunk-vendors.js:8:206689)
	onClick
	at (chunk-vendors.js:1054:11805)
	(anonymous function) (chunk-vendors.js:8:82351)
	forEach
	onClick (chunk-vendors.js:8:82330)
	onClick
	at (chunk-vendors.js:1054:11805)
```

**Comment by vabene1111** [comment]
hmm sadly this just confirms that its not working .. i guess i will have to use some kind of library or find another hack since apply had to do their own custom stupid thing here again ..

**Comment by tomtjes** [comment]
Although the copy button for the public share link of a recipe works as expected.

**Comment by vabene1111** [comment]
thats probably because it copies from a text input, i will need to refactor invite links to work like that as well.
