### ISSUE TITLE
Copy Me That importer broken

### ISSUE THREAD

**Issue by tomtjes** [TandoorRecipes/recipes#1932]
### Tandoor Version

beta (updated today)

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

0 recipes are imported, but the file upload seems to work.

### Relevant logs

```shell
File "/opt/recipes/cookbook/integration/integration.py", line 175, in do_import
    recipe = self.get_recipe_from_file(BytesIO(import_zip.read(z.filename)))
  File "/usr/local/lib/python3.10/zipfile.py", line 1475, in read
    with self.open(name, "r", pwd) as fp:
  File "/usr/local/lib/python3.10/zipfile.py", line 1514, in open
    zinfo = self.getinfo(name)
  File "/usr/local/lib/python3.10/zipfile.py", line 1441, in getinfo
    raise KeyError(
KeyError: 'There is no item named None in the archive'
Traceback (most recent call last):
  File "/opt/recipes/cookbook/integration/integration.py", line 175, in do_import
    recipe = self.get_recipe_from_file(BytesIO(import_zip.read(z.filename)))
  File "/usr/local/lib/python3.10/zipfile.py", line 1475, in read
    with self.open(name, "r", pwd) as fp:
  File "/usr/local/lib/python3.10/zipfile.py", line 1514, in open
    zinfo = self.getinfo(name)
  File "/usr/local/lib/python3.10/zipfile.py", line 1441, in getinfo
    raise KeyError(
KeyError: 'There is no item named None in the archive'
Traceback (most recent call last):
  File "/opt/recipes/cookbook/integration/integration.py", line 175, in do_import
    recipe = self.get_recipe_from_file(BytesIO(import_zip.read(z.filename)))
  File "/usr/local/lib/python3.10/zipfile.py", line 1475, in read
    with self.open(name, "r", pwd) as fp:
  File "/usr/local/lib/python3.10/zipfile.py", line 1514, in open
    zinfo = self.getinfo(name)
  File "/usr/local/lib/python3.10/zipfile.py", line 1441, in getinfo
    raise KeyError(
KeyError: 'There is no item named None in the archive'
Traceback (most recent call last):
  File "/opt/recipes/cookbook/integration/integration.py", line 175, in do_import
    recipe = self.get_recipe_from_file(BytesIO(import_zip.read(z.filename)))
  File "/usr/local/lib/python3.10/zipfile.py", line 1475, in read
    with self.open(name, "r", pwd) as fp:
  File "/usr/local/lib/python3.10/zipfile.py", line 1514, in open
    zinfo = self.getinfo(name)
  File "/usr/local/lib/python3.10/zipfile.py", line 1441, in getinfo
    raise KeyError(
KeyError: 'There is no item named None in the archive'
Traceback (most recent call last):
  File "/opt/recipes/cookbook/integration/integration.py", line 175, in do_import
    recipe = self.get_recipe_from_file(BytesIO(import_zip.read(z.filename)))
  File "/usr/local/lib/python3.10/zipfile.py", line 1475, in read
    with self.open(name, "r", pwd) as fp:
  File "/usr/local/lib/python3.10/zipfile.py", line 1514, in open
    zinfo = self.getinfo(name)
  File "/usr/local/lib/python3.10/zipfile.py", line 1441, in getinfo
    raise KeyError(
KeyError: 'There is no item named None in the archive'
Traceback (most recent call last):
  File "/opt/recipes/cookbook/integration/integration.py", line 175, in do_import
    recipe = self.get_recipe_from_file(BytesIO(import_zip.read(z.filename)))
  File "/usr/local/lib/python3.10/zipfile.py", line 1475, in read
    with self.open(name, "r", pwd) as fp:
  File "/usr/local/lib/python3.10/zipfile.py", line 1514, in open
    zinfo = self.getinfo(name)
  File "/usr/local/lib/python3.10/zipfile.py", line 1441, in getinfo
    raise KeyError(
KeyError: 'There is no item named None in the archive'
Traceback (most recent call last):
  File "/opt/recipes/cookbook/integration/integration.py", line 175, in do_import
    recipe = self.get_recipe_from_file(BytesIO(import_zip.read(z.filename)))
  File "/usr/local/lib/python3.10/zipfile.py", line 1475, in read
    with self.open(name, "r", pwd) as fp:
  File "/usr/local/lib/python3.10/zipfile.py", line 1514, in open
    zinfo = self.getinfo(name)
  File "/usr/local/lib/python3.10/zipfile.py", line 1441, in getinfo
    raise KeyError(
KeyError: 'There is no item named None in the archive'
Traceback (most recent call last):
  File "/opt/recipes/cookbook/integration/integration.py", line 175, in do_import
    recipe = self.get_recipe_from_file(BytesIO(import_zip.read(z.filename)))
  File "/usr/local/lib/python3.10/zipfile.py", line 1475, in read
    with self.open(name, "r", pwd) as fp:
  File "/usr/local/lib/python3.10/zipfile.py", line 1514, in open
    zinfo = self.getinfo(name)
  File "/usr/local/lib/python3.10/zipfile.py", line 1441, in getinfo
    raise KeyError(
KeyError: 'There is no item named None in the archive'
Traceback (most recent call last):
  File "/opt/recipes/cookbook/integration/integration.py", line 175, in do_import
    recipe = self.get_recipe_from_file(BytesIO(import_zip.read(z.filename)))
  File "/usr/local/lib/python3.10/zipfile.py", line 1475, in read
    with self.open(name, "r", pwd) as fp:
  File "/usr/local/lib/python3.10/zipfile.py", line 1514, in open
    zinfo = self.getinfo(name)
  File "/usr/local/lib/python3.10/zipfile.py", line 1441, in getinfo
    raise KeyError(
KeyError: 'There is no item named None in the archive'
Traceback (most recent call last):
  File "/opt/recipes/cookbook/integration/integration.py", line 175, in do_import
    recipe = self.get_recipe_from_file(BytesIO(import_zip.read(z.filename)))
  File "/usr/local/lib/python3.10/zipfile.py", line 1475, in read
    with self.open(name, "r", pwd) as fp:
  File "/usr/local/lib/python3.10/zipfile.py", line 1514, in open
    zinfo = self.getinfo(name)
  File "/usr/local/lib/python3.10/zipfile.py", line 1441, in getinfo
    raise KeyError(
KeyError: 'There is no item named None in the archive'
172.30.0.4 - - [12/Jul/2022:18:26:31 +0200] "GET /api/import-log/2/ HTTP/1.0" 200 70380 "http://192.168.21.2:81/import-response/2/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15"
```

**Comment by vabene1111** [comment]
fixed, not sure what changed but luckily a quick fix
