### ISSUE TITLE
Trouble importing recipe

### ISSUE THREAD

**Issue by supermar1010** [TandoorRecipes/recipes#2014]
### Tandoor Version

1.3.3

### Setup

Docker / Docker-Compose

### Reverse Proxy

Caddy

### Other

I also tried the hosted version, same error

### Bug description

Hello,
I'm trying to import a recipe exported from tandoor. I also tried using the one from this github [issue](https://github.com/TandoorRecipes/recipes/issues/1730), as I thought this might be a good test to see if it is the recipe that's faulty. The issue is tandoor never imports the recipe, always says imported 0 recipes. I tried uploading it as a file and pasting it in to the Input field.
The log is pasted below. 

My recipe looks like this:

``` json
{
  "name": "Chili sin Carne test",
  "description": null,
  "keywords": [],
  "steps": [
    {
      "name": "",
      "instruction": "Zwiebeln würfeln und glasig dünsten",
      "ingredients": [
        {
          "food": {
            "name": "Zwiebel",
            "ignore_shopping": false,
            "supermarket_category": null
          },
          "unit": { "name": "Stück", "description": null },
          "amount": 1.0,
          "note": "",
          "order": 0,
          "is_header": false,
          "no_amount": false
        }
      ],
      "time": 5,
      "order": 0,
      "show_as_header": true
    },
    {
      "name": "",
      "instruction": "Paprika und Knoblauch kleinschneiden und mitdünsten",
      "ingredients": [
        {
          "food": {
            "name": "Knoblauchzehe",
            "ignore_shopping": false,
            "supermarket_category": null
          },
          "unit": { "name": "Stück", "description": null },
          "amount": 1.0,
          "note": "",
          "order": 0,
          "is_header": false,
          "no_amount": false
        },
        {
          "food": {
            "name": "Paprika",
            "ignore_shopping": false,
            "supermarket_category": null
          },
          "unit": { "name": "Stück", "description": null },
          "amount": 1.0,
          "note": "",
          "order": 1,
          "is_header": false,
          "no_amount": false
        }
      ],
      "time": 5,
      "order": 1,
      "show_as_header": true
    },
    {
      "name": "",
      "instruction": "Kidneybohnen abwaschen, Tomaten würfeln und beides dazugeben",
      "ingredients": [
        {
          "food": {
            "name": "Tomate",
            "ignore_shopping": false,
            "supermarket_category": null
          },
          "unit": { "name": "Stück", "description": null },
          "amount": 1.0,
          "note": "",
          "order": 0,
          "is_header": false,
          "no_amount": false
        },
        {
          "food": {
            "name": "Kidneybohnen",
            "ignore_shopping": false,
            "supermarket_category": null
          },
          "unit": { "name": "Stück", "description": null },
          "amount": 1.0,
          "note": "",
          "order": 1,
          "is_header": false,
          "no_amount": false
        }
      ],
      "time": 5,
      "order": 2,
      "show_as_header": true
    },
    {
      "name": "",
      "instruction": "Gewürze dazugeben und 10 Minuten köcheln lassen\nEventuell Wasser hinzugeben, wenn es zu trocken ist",
      "ingredients": [
        {
          "food": {
            "name": "Oregano",
            "ignore_shopping": false,
            "supermarket_category": null
          },
          "unit": { "name": "TL", "description": null },
          "amount": 1.0,
          "note": "",
          "order": 0,
          "is_header": false,
          "no_amount": false
        },
        {
          "food": {
            "name": "Brühwürfel",
            "ignore_shopping": false,
            "supermarket_category": null
          },
          "unit": { "name": "Stück", "description": null },
          "amount": 1.5,
          "note": "",
          "order": 1,
          "is_header": false,
          "no_amount": false
        },
        {
          "food": {
            "name": "Salz",
            "ignore_shopping": false,
            "supermarket_category": null
          },
          "unit": null,
          "amount": 0.0,
          "note": "nach Bedarf",
          "order": 2,
          "is_header": false,
          "no_amount": false
        },
        {
          "food": {
            "name": "Sojasoße",
            "ignore_shopping": false,
            "supermarket_category": null
          },
          "unit": null,
          "amount": 0.0,
          "note": "nach Bedarf",
          "order": 3,
          "is_header": false,
          "no_amount": false
        },
        {
          "food": {
            "name": "Paprikapulver",
            "ignore_shopping": false,
            "supermarket_category": null
          },
          "unit": null,
          "amount": 0.0,
          "note": "nach Bedarf",
          "order": 4,
          "is_header": false,
          "no_amount": false
        },
        {
          "food": {
            "name": "Pfeffer",
            "ignore_shopping": false,
            "supermarket_category": null
          },
          "unit": null,
          "amount": 0.0,
          "note": "nach Bedarf",
          "order": 5,
          "is_header": false,
          "no_amount": false
        }
      ],
      "time": 10,
      "order": 3,
      "show_as_header": true
    },
    {
      "name": "",
      "instruction": "Olivenöl dazugeben und Einrühren",
      "ingredients": [
        {
          "food": {
            "name": "Olivenöl",
            "ignore_shopping": false,
            "supermarket_category": null
          },
          "unit": { "name": "EL", "description": null },
          "amount": 1.0,
          "note": "",
          "order": 0,
          "is_header": false,
          "no_amount": false
        }
      ],
      "time": 0,
      "order": 4,
      "show_as_header": true
    },
    {
      "name": "",
      "instruction": "Am Besten einmal klat werden lassen und nach dem Aufwärmen essen",
      "ingredients": [],
      "time": 0,
      "order": 5,
      "show_as_header": true
    }
  ],
  "working_time": 45,
  "waiting_time": 0,
  "internal": true,
  "nutrition": null,
  "servings": 4,
  "servings_text": "vier"
}
```

### Relevant logs

```shell
Traceback (most recent call last):
  File "/opt/recipes/cookbook/integration/integration.py", line 186, in do_import
    data_list = self.split_recipe_file(f['file'])
  File "/opt/recipes/cookbook/integration/integration.py", line 273, in split_recipe_file
    raise NotImplementedError('Method not implemented in integration')
NotImplementedError: Method not implemented in integration


```

**Comment by supermar1010** [comment]
Update I just managed to import it. I just uploaded the whole zip without unzipping the jsons. So it might have only been an user error? 
I had a look in the code, and it looks like it should also be possible to just upload the json?

**Comment by vabene1111** [comment]
No it needs to upload the zip. Maybe future versions can detect what you are uploading but currently that's not possible
