### ISSUE TITLE
Error during collectstatic on django 4.1

### ISSUE THREAD

**Issue by ambroisie** [TandoorRecipes/recipes#2043]
### Tandoor Version

1.3.3

### Setup

Others (please state below)

### Reverse Proxy

No reverse proxy

### Other

This is not during tandoor's usage, but at build-time

### Bug description

I am in the process of packaging Tandoor Recipes for NixOS (see NixOS/nixpkgs#145244).

At the moment, I am faced with the following error during the `collectstatic` step:

```
whitenoise.storage.MissingFileError: The file 'themes/maps/style.min.css.map' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x7ffff4b25e10>.
```

### Relevant logs

```shell
js-reverse file written to /build/source/cookbook/static/django_js_reverse
Post-processing 'themes/tandoor.min.css' failed!

Traceback (most recent call last):
  File "/build/source/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/nix/store/jqnsvh77gcd4i1860y5mb96chml9v2wa-python3.10-Django-4.1.1/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/nix/store/jqnsvh77gcd4i1860y5mb96chml9v2wa-python3.10-Django-4.1.1/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/nix/store/jqnsvh77gcd4i1860y5mb96chml9v2wa-python3.10-Django-4.1.1/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/nix/store/jqnsvh77gcd4i1860y5mb96chml9v2wa-python3.10-Django-4.1.1/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/nix/store/jqnsvh77gcd4i1860y5mb96chml9v2wa-python3.10-Django-4.1.1/lib/python3.10/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 209, in handle
    collected = self.collect()
  File "/nix/store/jqnsvh77gcd4i1860y5mb96chml9v2wa-python3.10-Django-4.1.1/lib/python3.10/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 154, in collect
    raise processed
whitenoise.storage.MissingFileError: The file 'themes/maps/style.min.css.map' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x7ffff4b25e10>.

The CSS file 'themes/tandoor.min.css' references a file which could not be found:
  themes/maps/style.min.css.map

Please check the URL references in this CSS file, particularly any
relative paths which might be pointing to the wrong location.
```

**Comment by ambroisie** [comment]
I think that, in the meantime, I can just `touch themes/maps/style.min.css.map` and it should work with an empty file.

**Comment by vabene1111** [comment]
interestingly the CI fails for the same reason, i am not sure yet why. I know there were problems before with an empty static manifest file but this does not seem to be the case. 

At the same time the automated deployment works and i can run the dev version with django 4.1 on my server so this appears to be something affected by the build environment.

**Comment by ambroisie** [comment]
@vabene1111 here's what I found on the subject: https://stackoverflow.com/a/73411956.

**Comment by vabene1111** [comment]
Awesome thanks for looking this up
