### ISSUE TITLE
Searching for tags does not return (partial) results

### ISSUE THREAD

**Issue by DennaGherlyn** [TandoorRecipes/recipes#2059]
### Tandoor Version

1.4.2

### Setup

Unraid

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

Since the new version searching for tags not working correctly. When typing there is a error loading a resource for every character and partial matches are not returned. Even after typing the whole name the suggested option is "add keyword" not "select" even though the tag already exists. 

![grafik](https://user-images.githubusercontent.com/13550824/192085164-9c0f6c94-21bd-4e9d-90ef-51a2f23f4f8d.png)

Adding the tag does add it like it where a new one (without emojis), but saving the recipe does translate the tag correctly to the existing one with emojis.

![grafik](https://user-images.githubusercontent.com/13550824/192085677-39c7512a-98a1-4fff-a339-d2ccb673f3bd.png)

![grafik](https://user-images.githubusercontent.com/13550824/192085697-75f84399-3ba0-4863-902d-4b0486fa9370.png)

Setup:
Docker container on Unraid
SQLite DB
Gunicorn enabled

### Relevant logs

```shell
192.168.1.252 - - [24/Sep/2022:09:13:45 +0200] "GET /api/keyword/?query=vega&page=1&page_size=25 HTTP/1.1" 500 145 "https://tandoor.hackish.codes/edit/recipe/internal/295/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
ERROR:django.request:Internal Server Error: /api/keyword/
Traceback (most recent call last):
File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
return self.cursor.execute(sql, params)
File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 477, in execute
return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such function: SIMILARITY

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
response = get_response(request)
File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/opt/recipes/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
return view_func(*args, **kwargs)
File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
return self.dispatch(request, *args, **kwargs)
File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
response = self.handle_exception(exc)
File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
self.raise_uncaught_exception(exc)
File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
raise exc
File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
response = handler(request, *args, **kwargs)
File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 40, in list
page = self.paginate_queryset(queryset)
File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/generics.py", line 171, in paginate_queryset
return self.paginator.paginate_queryset(queryset, self.request, view=self)
File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/pagination.py", line 204, in paginate_queryset
self.page = paginator.page(page_number)
File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/paginator.py", line 75, in page
number = self.validate_number(number)
File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/paginator.py", line 53, in validate_number
if number > self.num_pages:
File "/opt/recipes/venv/lib/python3.10/site-packages/django/utils/functional.py", line 49, in __get__
res = instance.__dict__[self.name] = self.func(instance)
File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/paginator.py", line 102, in num_pages
if self.count == 0 and not self.allow_empty_first_page:
File "/opt/recipes/venv/lib/python3.10/site-packages/django/utils/functional.py", line 49, in __get__
res = instance.__dict__[self.name] = self.func(instance)
File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/paginator.py", line 96, in count
return c()
File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/query.py", line 470, in count
return self.query.get_count(using=self.db)
File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 552, in get_count
number = obj.get_aggregation(using, ["__count"])["__count"]
File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 537, in get_aggregation
result = compiler.execute_sql(SINGLE)
File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1361, in execute_sql
cursor.execute(sql, params)
File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
return self._execute_with_wrappers(
File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
return executor(sql, params, many, context)
File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
with self.db.wrap_database_errors:
File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
raise dj_exc_value.with_traceback(traceback) from exc_value
File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
return self.cursor.execute(sql, params)
File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 477, in execute
return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such function: SIMILARITY
192.168.1.252 - - [24/Sep/2022:09:13:45 +0200] "GET /api/keyword/?query=vegan&page=1&page_size=25 HTTP/1.1" 500 145 "https://tandoor.hackish.codes/edit/recipe/internal/295/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"
```

**Comment by vabene1111** [comment]
Thanks for reporting, I have an idea what this might be caused by, will look into it

**Comment by vabene1111** [comment]
ok, this was a regression form allowing some sqlite settings that could not be applied before. Its fixed for now, the search will be handled in another round, release should be out in the next few days
