### ISSUE TITLE
Recipes errors out with 500 error

### ISSUE THREAD

**Issue by delize** [TandoorRecipes/recipes#2184]
### Tandoor Version

b3fba5cfb3d2

### Setup

Docker / Docker-Compose

### Reverse Proxy

SWAG

### Bug description

When starting Recipes via Docker, during bootup, a traceback error is written to console.

After the traceback error is loaded, recipes constantly attempts to load `/search` even when not specifying it. 

Removing the Docker image and starting again does not resolve the problem. No updates have been performed to Recipes for some time, so I do not know what has occurred here - as I have not created/updated/deleted recipes or files since it was working a few weeks back.

### Relevant logs

```shell
$ docker logs -f recipes
Checking configuration...
Waiting for database to be ready...
Database is ready
Migrating database
Operations to perform:
  Apply all migrations: account, admin, auth, authtoken, contenttypes, cookbook, oauth2_provider, sessions, sites, socialaccount
Running migrations:
  No migrations to apply.
Generating static files
js-reverse file written to /opt/recipes/cookbook/static/django_js_reverse
Traceback (most recent call last):
  File "/opt/recipes/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 184, in handle
    if self.is_local_storage() and self.storage.location:
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 245, in is_local_storage
    return isinstance(self.storage, FileSystemStorage)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/utils/functional.py", line 258, in inner
    self._setup()
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py", line 489, in _setup
    self._wrapped = get_storage_class(settings.STATICFILES_STORAGE)()
  File "/opt/recipes/venv/lib/python3.10/site-packages/whitenoise/storage.py", line 131, in __init__
    super().__init__(*args, **kwargs)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py", line 419, in __init__
    self.hashed_files = self.load_manifest()
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/contrib/staticfiles/storage.py", line 440, in load_manifest
    raise ValueError(
ValueError: Couldn't load manifest 'staticfiles.json' (version 1.0)
Done
[2022-11-25 08:20:00 +0100] [1] [INFO] Starting gunicorn 20.1.0
[2022-11-25 08:20:00 +0100] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2022-11-25 08:20:00 +0100] [1] [INFO] Using worker: gthread
[2022-11-25 08:20:00 +0100] [11] [INFO] Booting worker with pid: 11
[2022-11-25 08:20:00 +0100] [12] [INFO] Booting worker with pid: 12
[2022-11-25 08:20:00 +0100] [13] [INFO] Booting worker with pid: 13
172.23.0.7 - - [25/Nov/2022:08:20:13 +0100] "GET /search/ HTTP/1.1" 500 145 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"
172.23.0.7 - - [25/Nov/2022:08:20:13 +0100] "GET /favicon.ico HTTP/1.1" 500 145 "https://recipes.net-slum.org/search/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"
```

**Comment by vabene1111** [comment]
Please delete static files and re run startup

**Comment by delize** [comment]
Thanks that did it! :) 

Found another issue after deletion of the static files, but, will make a different ticket.
