### ISSUE TITLE
Get error when execute "bin/python3 manage.py migrate"

### ISSUE THREAD

**Issue by CactusStar** [TandoorRecipes/recipes#2230]
### Documentation link

https://docs.tandoor.dev/install/manual/

### Affected section

Installation

### Issue description

Dear community,

when I tried to manual install this application in a Centos system, when execute the command "bin/python3 manage.py migrate", I get below errors: 

Traceback (most recent call last):
  File "/var/www/recipes/lib/python3.9/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.UndefinedColumn: column c.relispartition does not exist
LINE 5:                     WHEN c.relispartition THEN 'p'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/www/recipes/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/recipes/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/var/www/recipes/lib/python3.9/site-packages/django/core/management/__init__.py", line 420, in execute
    django.setup()
  File "/var/www/recipes/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/var/www/recipes/lib/python3.9/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/var/www/recipes/lib/python3.9/site-packages/django_prometheus/apps.py", line 24, in ready
    ExportMigrations()
  File "/var/www/recipes/lib/python3.9/site-packages/django_prometheus/migrations.py", line 52, in ExportMigrations
    executor = MigrationExecutor(connections[alias])
  File "/var/www/recipes/lib/python3.9/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/var/www/recipes/lib/python3.9/site-packages/django/db/migrations/loader.py", line 58, in __init__
    self.build_graph()
  File "/var/www/recipes/lib/python3.9/site-packages/django/db/migrations/loader.py", line 235, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/var/www/recipes/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 81, in applied_migrations
    if self.has_table():
  File "/var/www/recipes/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 58, in has_table
    tables = self.connection.introspection.table_names(cursor)
  File "/var/www/recipes/lib/python3.9/site-packages/django/db/backends/base/introspection.py", line 58, in table_names
    return get_names(cursor)
  File "/var/www/recipes/lib/python3.9/site-packages/django/db/backends/base/introspection.py", line 51, in get_names
    for ti in self.get_table_list(cursor)
  File "/var/www/recipes/lib/python3.9/site-packages/django/db/backends/postgresql/introspection.py", line 51, in get_table_list
    cursor.execute(
  File "/var/www/recipes/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/var/www/recipes/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/var/www/recipes/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/var/www/recipes/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/www/recipes/lib/python3.9/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: column c.relispartition does not exist
LINE 5:                     WHEN c.relispartition THEN 'p'

could you please help to have a look on this?

thanks

**Comment by vabene1111** [comment]
Sorry, due to the basically unlimited amount of reasons wh, thus could fail there is no support for manual setups. I also don't see anything apparent that's wrong.
