### ISSUE TITLE
500 when importing from 

### ISSUE THREAD

**Issue by Georift** [TandoorRecipes/recipes#2277]
### Tandoor Version

beta

### Import URL

https://www.rainbownourishments.com/vegan-lemon-tart/#recipe

### When did the issue happen?

New installation of Tandoor, tried this recipe and the API 500-ed.

### Response / message shown

```shell
tandoor-web_recipes-1    | ERROR:django.request:Internal Server Error: /api/recipe-from-source/
tandoor-web_recipes-1    | Traceback (most recent call last):
tandoor-web_recipes-1    |   File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
tandoor-web_recipes-1    |     response = get_response(request)
tandoor-web_recipes-1    |   File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
tandoor-web_recipes-1    |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
tandoor-web_recipes-1    |   File "/opt/recipes/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
tandoor-web_recipes-1    |     return view_func(*args, **kwargs)
tandoor-web_recipes-1    |   File "/opt/recipes/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
tandoor-web_recipes-1    |     return self.dispatch(request, *args, **kwargs)
tandoor-web_recipes-1    |   File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
tandoor-web_recipes-1    |     response = self.handle_exception(exc)
tandoor-web_recipes-1    |   File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
tandoor-web_recipes-1    |     self.raise_uncaught_exception(exc)
tandoor-web_recipes-1    |   File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
tandoor-web_recipes-1    |     raise exc
tandoor-web_recipes-1    |   File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
tandoor-web_recipes-1    |     response = handler(request, *args, **kwargs)
tandoor-web_recipes-1    |   File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
tandoor-web_recipes-1    |     return func(*args, **kwargs)
tandoor-web_recipes-1    |   File "/opt/recipes/cookbook/views/api.py", line 1206, in recipe_from_source
tandoor-web_recipes-1    |     'recipe_json': helper.get_from_scraper(scrape, request),
tandoor-web_recipes-1    |   File "/opt/recipes/cookbook/helper/recipe_url_import.py", line 133, in get_from_scraper
tandoor-web_recipes-1    |     recipe_json['keywords'] = parse_keywords(list(set(map(str.casefold, keywords))), request.space)
tandoor-web_recipes-1    | TypeError: descriptor 'casefold' for 'str' objects doesn't apply to a 'NoneType' object
```
```

**Comment by smilerz** [comment]
How are you trying to import it?

**Comment by Georift** [comment]
I just booted up the development environment and it imported great.

The error I encountered was from the `beta` docker container.

**Comment by Georift** [comment]
^ On the develop branch

**Comment by Georift** [comment]
Switched to `origin/beta (aa5490ad)` and the import error presenting again.

**Comment by Georift** [comment]
3b9d2212 fixes this bug! Closing for now. Thanks for the quick reply.

**Comment by vabene1111** [comment]
interesting, i saw the error when testing but tought i fixed it, will look into it.

**Comment by vabene1111** [comment]
ok so this was just a frontend issue, the view did not support ingredients without a unit. Your recipe has some really screwed up ingredients with amount ranges and multiple units in each row, will save this recipe for future use in improving the ingredient parser but for now this should be resolved.

**Comment by Georift** [comment]
Appreciate it thank you :+1:
