### ISSUE TITLE
Recipe import fails when units contain singular 

### ISSUE THREAD

**Issue by tomtjes** [TandoorRecipes/recipes#2304]
### Tandoor Version

1.4.6

### Setup

Docker / Docker-Compose

### Reverse Proxy

SWAG

### Bug description

- merge unit `cups` into `cup` 
- add `cups` as plural form of `cup`
- import recipe that contains unit `cup` (using bookmarklet or source importer)
- > failed to create a resource

### Relevant logs

```shell
172.30.0.2 - - [05/Feb/2023:21:09:11 +0100] "GET /static/js/bookmarklet_v3.js?r=120126904 HTTP/1.1" 200 0 "https://cooking.nytimes.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15"
172.30.0.2 - - [05/Feb/2023:21:09:12 +0100] "POST /api/bookmarklet-import/ HTTP/1.1" 201 374365 "https://cooking.nytimes.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15"
172.30.0.2 - - [05/Feb/2023:21:09:13 +0100] "GET /data/import/url?id=58 HTTP/1.1" 200 20427 "https://cooking.nytimes.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15"
172.30.0.2 - - [05/Feb/2023:21:09:13 +0100] "GET /manifest.json HTTP/1.1" 200 1117 "https://recipes.redacted.domain/data/import/url?id=58" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15"
172.30.0.2 - - [05/Feb/2023:21:09:14 +0100] "GET /api/space/1/ HTTP/1.1" 200 317 "https://recipes.redacted.domain/data/import/url?id=58" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15"
172.30.0.2 - - [05/Feb/2023:21:09:14 +0100] "POST /api/recipe-from-source/ HTTP/1.1" 200 6744 "https://recipes.redacted.domain/data/import/url?id=58" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15"
172.30.0.2 - - [05/Feb/2023:21:09:14 +0100] "GET /service-worker.js HTTP/1.1" 200 24954 "https:" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15"
ERROR:django.request:Internal Server Error: /api/recipe/
Traceback (most recent call last):
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/query.py", line 929, in get_or_create
    return self.get(**kwargs), False
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
cookbook.models.Unit.DoesNotExist: Unit matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "u_unique_name_per_space"
DETAIL:  Key (space_id, name)=(1, cup) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/opt/recipes/venv/lib/python3.10/site-packages/drf_writable_nested/mixins.py", line 233, in save
    return super(BaseNestedModelSerializer, self).save(**kwargs)
  File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/opt/recipes/cookbook/serializer.py", line 758, in create
    return super().create(validated_data)
  File "/opt/recipes/venv/lib/python3.10/site-packages/drf_writable_nested/mixins.py", line 261, in create
    self.update_or_create_reverse_relations(instance, reverse_relations)
  File "/opt/recipes/venv/lib/python3.10/site-packages/drf_writable_nested/mixins.py", line 188, in update_or_create_reverse_relations
    related_instance = serializer.save(**save_kwargs)
  File "/opt/recipes/venv/lib/python3.10/site-packages/drf_writable_nested/mixins.py", line 233, in save
    return super(BaseNestedModelSerializer, self).save(**kwargs)
  File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/opt/recipes/cookbook/serializer.py", line 648, in create
    return super().create(validated_data)
  File "/opt/recipes/venv/lib/python3.10/site-packages/drf_writable_nested/mixins.py", line 261, in create
    self.update_or_create_reverse_relations(instance, reverse_relations)
  File "/opt/recipes/venv/lib/python3.10/site-packages/drf_writable_nested/mixins.py", line 188, in update_or_create_reverse_relations
    related_instance = serializer.save(**save_kwargs)
  File "/opt/recipes/venv/lib/python3.10/site-packages/drf_writable_nested/mixins.py", line 233, in save
    return super(BaseNestedModelSerializer, self).save(**kwargs)
  File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/opt/recipes/cookbook/serializer.py", line 619, in create
    return super().create(validated_data)
  File "/opt/recipes/venv/lib/python3.10/site-packages/drf_writable_nested/mixins.py", line 253, in create
    self.update_or_create_direct_relations(
  File "/opt/recipes/venv/lib/python3.10/site-packages/drf_writable_nested/mixins.py", line 224, in update_or_create_direct_relations
    attrs[field_source] = serializer.save(
  File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/opt/recipes/cookbook/serializer.py", line 439, in create
    obj, created = Unit.objects.get_or_create(name=name, plural_name=plural_name, space=space, defaults=validated_data)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/query.py", line 936, in get_or_create
    return self.create(**params), True
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/query.py", line 671, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/base.py", line 812, in save
    self.save_base(
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/base.py", line 863, in save_base
    updated = self._save_table(
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1006, in _save_table
    results = self._do_insert(
  File "/opt/recipes/venv/lib/python3.10/site-packages/django_prometheus/models.py", line 43, in _do_insert
    return super()._do_insert(*args, **kwargs)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/base.py", line 1047, in _do_insert
    return manager._insert(
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1791, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1660, in execute_sql
    cursor.execute(sql, params)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "u_unique_name_per_space"
DETAIL:  Key (space_id, name)=(1, cup) already exists.
```

**Comment by vabene1111** [comment]
thanks for the good report, fixed this for the next release :)
