### ISSUE TITLE
Can't login after watchtower update

### ISSUE THREAD

**Issue by raviolispy** [TandoorRecipes/recipes#2328]
### Tandoor Version

latest / unknown (see below)

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

After automatically upgrading via watchtower around 2/13, the web recipes container seems broken according to the following logs below. I discovered this when it said my credentials were invalid and when I tried to reset them by dropping to the shell on the web container it would say user xyz doesn't exist but the database container would simultaneously give a dupe primary key error saying that user xyz already existed. 

### Relevant logs

```shell
Running migrations:

Traceback (most recent call last):

  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute

    return self.cursor.execute(sql, params)

psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_attribute_relid_attnam_index"

DETAIL:  Key (attrelid, attname)=(16964, plural_name) already exists.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/opt/recipes/manage.py", line 15, in <module>

    execute_from_command_line(sys.argv)

  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line

    utility.execute()

  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute

    self.fetch_command(subcommand).run_from_argv(self.argv)

  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv

    self.execute(*args, **cmd_options)

  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute

    output = self.handle(*args, **options)

  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/management/base.py", line 96, in wrapped

    res = handle_func(*args, **kwargs)

  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 349, in handle

    post_migrate_state = executor.migrate(

  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 135, in migrate

    state = self._migrate_all_forwards(

  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards

    state = self.apply_migration(

  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 252, in apply_migration

    state = migration.apply(state, schema_editor)

  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/migrations/migration.py", line 130, in apply

    operation.database_forwards(

  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/migrations/operations/fields.py", line 108, in database_forwards

    schema_editor.add_field(

  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/base/schema.py", line 682, in add_field

    self.execute(sql, params)

  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/base/schema.py", line 199, in execute

    cursor.execute(sql, params)

  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute

    return self._execute_with_wrappers(

  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers

    return executor(sql, params, many, context)

  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute

    with self.db.wrap_database_errors:

  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__

    raise dj_exc_value.with_traceback(traceback) from exc_value

  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute

    return self.cursor.execute(sql, params)

django.db.utils.IntegrityError: duplicate key value violates unique constraint "pg_attribute_relid_attnam_index"

DETAIL:  Key (attrelid, attname)=(16964, plural_name) already exists.
```

**Comment by vabene1111** [comment]
this might be related to #2317 

whats interesting is that i have 4 seperate setups of tandoor all with data and in all of them the migrations ran trough fine. 

Can you please check if you also get an error when starting the container when django tries to run its migrations and can you check the `django_migration` table what the last migration of "cookbook" was that ran trough ?

**Comment by vabene1111** [comment]
I need to look into this. It's the same problem as in the linked issue, I already got some debug data there, I hope that I will find the time next week to find out why this is failing.

**Comment by vabene1111** [comment]
Closing this since it's a duplicate, if you want to migrate take a look at the other issue I have described some ways the problem might be solved.
