### ISSUE TITLE
Django 4.2.1/4.1.9 security update breaks build

### ISSUE THREAD

**Issue by mweinelt** [TandoorRecipes/recipes#2457]
### Tandoor Version

1.4.9

### Setup

Others (please state below)

### Reverse Proxy

No reverse proxy

### Other

NixOS distribution package

### Bug description

The Django 4.1.9 and 4.2.1 security update break the build of tandoor-recipes.

> In order to avoid the vulnerability, ClearableFileInput and FileInput` form widgets now raise ValueError when the multiple HTML attribute is set on them. To prevent the exception and keep the old behavior, set allow_multiple_selected to True.

https://www.djangoproject.com/weblog/2023/may/03/security-releases/

https://github.com/TandoorRecipes/recipes/blob/135640dd5832621f2ac26eaff56dc4351686f1e4/cookbook/forms.py#L170-L174

### Relevant logs

```shell
Traceback (most recent call last):
  File "/build/source/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/nix/store/p9rhwjlkvs6zqn02f16fyf4s74pcy378-python3.10-Django-4.1.9/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/nix/store/p9rhwjlkvs6zqn02f16fyf4s74pcy378-python3.10-Django-4.1.9/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/nix/store/p9rhwjlkvs6zqn02f16fyf4s74pcy378-python3.10-Django-4.1.9/lib/python3.10/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/nix/store/p9rhwjlkvs6zqn02f16fyf4s74pcy378-python3.10-Django-4.1.9/lib/python3.10/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/nix/store/cfcqmi293cxm8v4l9l0v5n5skwxz2mzq-python3.10-django-js-reverse-unstable-2022-09-16/lib/python3.10/site-packages/django_js_reverse/management/commands/collectstatic_js_reverse.py", line 42, in handle
    content = generate_js(default_urlresolver)
  File "/nix/store/cfcqmi293cxm8v4l9l0v5n5skwxz2mzq-python3.10-django-js-reverse-unstable-2022-09-16/lib/python3.10/site-packages/django_js_reverse/core.py", line 165, in generate_js
    data = generate_json(default_urlresolver, script_prefix)
  File "/nix/store/cfcqmi293cxm8v4l9l0v5n5skwxz2mzq-python3.10-django-js-reverse-unstable-2022-09-16/lib/python3.10/site-packages/django_js_reverse/core.py", line 114, in generate_json
    urls = sorted(list(prepare_url_list(default_urlresolver)))
  File "/nix/store/cfcqmi293cxm8v4l9l0v5n5skwxz2mzq-python3.10-django-js-reverse-unstable-2022-09-16/lib/python3.10/site-packages/django_js_reverse/core.py", line 80, in prepare_url_list
    for url_name in urlresolver.reverse_dict.keys():
  File "/nix/store/p9rhwjlkvs6zqn02f16fyf4s74pcy378-python3.10-Django-4.1.9/lib/python3.10/site-packages/django/urls/resolvers.py", line 619, in reverse_dict
    self._populate()
  File "/nix/store/p9rhwjlkvs6zqn02f16fyf4s74pcy378-python3.10-Django-4.1.9/lib/python3.10/site-packages/django/urls/resolvers.py", line 543, in _populate
    for url_pattern in reversed(self.url_patterns):
  File "/nix/store/p9rhwjlkvs6zqn02f16fyf4s74pcy378-python3.10-Django-4.1.9/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/nix/store/p9rhwjlkvs6zqn02f16fyf4s74pcy378-python3.10-Django-4.1.9/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/nix/store/p9rhwjlkvs6zqn02f16fyf4s74pcy378-python3.10-Django-4.1.9/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/nix/store/p9rhwjlkvs6zqn02f16fyf4s74pcy378-python3.10-Django-4.1.9/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/nix/store/6jx4nc20v3cfphlbypqid30q41i5vh5x-python3-3.10.11/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/build/source/recipes/urls.py", line 25, in <module>
    path('', include('cookbook.urls')),
  File "/nix/store/p9rhwjlkvs6zqn02f16fyf4s74pcy378-python3.10-Django-4.1.9/lib/python3.10/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/nix/store/6jx4nc20v3cfphlbypqid30q41i5vh5x-python3-3.10.11/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/build/source/cookbook/urls.py", line 16, in <module>
    from .views import api, data, delete, edit, import_export, lists, new, telegram, views
  File "/build/source/cookbook/views/__init__.py", line 1, in <module>
    import cookbook.views.api
  File "/build/source/cookbook/views/api.py", line 49, in <module>
    from cookbook.forms import ImportForm
  File "/build/source/cookbook/forms.py", line 169, in <module>
    class ImportForm(ImportExportBase):
  File "/build/source/cookbook/forms.py", line 170, in ImportForm
    files = forms.FileField(required=True, widget=forms.ClearableFileInput(attrs={'multiple': True}))
  File "/nix/store/p9rhwjlkvs6zqn02f16fyf4s74pcy378-python3.10-Django-4.1.9/lib/python3.10/site-packages/django/forms/widgets.py", line 427, in __init__
    raise ValueError(
ValueError: ClearableFileInput doesn't support uploading multiple files.
```

**Comment by ambroisie** [comment]
Will take a look when I have time (this weekend).

**Comment by ambroisie** [comment]
A quick fix for our packaging purposes is to patch `multiple: False` instead.

A better long-term fix is to actually follow the [upstream documentation](https://docs.djangoproject.com/en/4.2/topics/http/file-uploads/#uploading-multiple-files).
