### ISSUE TITLE
open data import fails to get resource; partial import and erroneous data

### ISSUE THREAD

**Issue by benniekiss** [TandoorRecipes/recipes#2501]
### Tandoor Version

beta-29b74557a6f48da013f842e4ead69a22f8815968

### Setup

Others (please state below)

### Reverse Proxy

Others (please state below)

### Other

podman and the official nginx container

### Bug description

**Recreate:**

Login >> Space Settings >> Open Data Import
Select "en" in the drop-down menu (it doesn't matter whether the check-boxes are marked)
Click import.

**Expected:** 

data imports like other languages.

**Result:**

Receive an error notification, "Failure: There was an error creating a resource!" Only some of the english data is imported, such as the "supermarkets" and "units", but information such as "food" and "conversions" does not populate.

An "en" import also includes data from other languages. Going to "properties", "supermarkets", or "units" shows non-english data.

### Relevant logs

```shell
CONTAINER LOGS:

{'selected_version': 'en', 'selected_datatypes': ['food', 'unit', 'category', 'property', 'store', 'conversion'], 'update_existing': True, 'use_metric': True}

Internal Server Error: /api-import-open-data/

Traceback (most recent call last):

  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner

    response = get_response(request)

  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response

    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/opt/recipes/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view

    return view_func(*args, **kwargs)

  File "/opt/recipes/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view

    return self.dispatch(request, *args, **kwargs)

  File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch

    response = self.handle_exception(exc)

  File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception

    self.raise_uncaught_exception(exc)

  File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception

    raise exc

  File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch

    response = handler(request, *args, **kwargs)

  File "/opt/recipes/cookbook/views/api.py", line 1453, in post

    response_obj['store'] = len(data_importer.import_supermarket())

  File "/opt/recipes/cookbook/helper/open_data_importer.py", line 90, in import_supermarket

    supermarket_id=self.slug_id_cache[datatype][k],

KeyError: 'store'

Internal Server Error: /api-import-open-data/

Traceback (most recent call last):

  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner

    response = get_response(request)

  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response

    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/opt/recipes/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view

    return view_func(*args, **kwargs)

  File "/opt/recipes/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view

    return self.dispatch(request, *args, **kwargs)

  File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch

    response = self.handle_exception(exc)

  File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception

    self.raise_uncaught_exception(exc)

  File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception

    raise exc

  File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch

    response = handler(request, *args, **kwargs)

  File "/opt/recipes/cookbook/views/api.py", line 1453, in post

    response_obj['store'] = len(data_importer.import_supermarket())

  File "/opt/recipes/cookbook/helper/open_data_importer.py", line 90, in import_supermarket

    supermarket_id=self.slug_id_cache[datatype][k],

KeyError: 'store'
```

**Comment by vabene1111** [comment]
ok forgot to change one keyword when i renamed supermarkets to stores in the open data repo.

Fixed now
