### ISSUE TITLE
Pasting ingredients does not work, ID undefined

### ISSUE THREAD

**Issue by Forceu** [TandoorRecipes/recipes#2519]
### Tandoor Version

1.5.3

### Setup

Docker / Docker-Compose

### Reverse Proxy

Others (please state below)

### Other

Nginx

### Bug description

When pasting ingredients on a new recipe, only a JS error is logged.

I pasted the following string:

```
1 kg Kartoffeln (Pellkartoffeln vom Vortag)

3 Zucchini

500 g Cocktailtomaten

2 EL Olivenöl

Salz

200 g ja! Kräuterquark

Pfeffer
```

### Relevant logs

```shell
katex.min.js:1 Warning: KaTeX doesn't work in quirks mode. Make sure your website has a suitable doctype.
1../src/ParseError @ katex.min.js:1
n @ katex.min.js:1
e @ katex.min.js:1
(anonymous) @ katex.min.js:1
(anonymous) @ katex.min.js:1
(anonymous) @ katex.min.js:1



TypeError: Cannot read properties of undefined (reading 'id')
    at edit_internal_recipe.cf66f808e5f3.js:1:18431
    at o.Tt [as _l] (chunk-vendors.f97ae76c89ae.js:1060:14350)
    at edit_internal_recipe.cf66f808e5f3.js:1:18377
    at o.Tt [as _l] (chunk-vendors.f97ae76c89ae.js:1060:14350)
    at o.n (edit_internal_recipe.cf66f808e5f3.js:1:11765)
    at e._render (chunk-vendors.f97ae76c89ae.js:1060:20103)
    at o.n (chunk-vendors.f97ae76c89ae.js:1060:24095)
    at e.get (chunk-vendors.f97ae76c89ae.js:1060:33537)
    at e.run (chunk-vendors.f97ae76c89ae.js:1060:34274)
    at Wr (chunk-vendors.f97ae76c89ae.js:1060:26282)
```

**Comment by vabene1111** [comment]
fixed, broke that a while ago when adding that the sorting is maintained

**Comment by smilerz** [comment]
> fixed, broke that a while ago when adding that the sorting is maintained

I still have this broken - which PR fixed it?
