### ISSUE TITLE
/api/recipe-from-source returns 500

### ISSUE THREAD

**Issue by wtfreely** [TandoorRecipes/recipes#2562]
### Tandoor Version

1.5.4

### Setup

Unraid

### Reverse Proxy

No reverse proxy

### Bug description

Tandoor provides a 500 error when I make a POST request to /api/recipe-from-source.

Posting the following JSON (with the `Authorization: Token xxxyyyzzz` headers) always returns a 500 error:

`{
  "url": "https://www.bbcgoodfood.com/recipes/flambeed-chicken-asparagus"
}
`

### Relevant logs

```shell
Internal Server Error: /api/recipe-from-source/
Traceback (most recent call last):
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/opt/recipes/cookbook/views/api.py", line 1274, in recipe_from_source
    data = unquote(serializer.validated_data.get('data', None))
  File "/usr/local/lib/python3.10/urllib/parse.py", line 667, in unquote
    if '%' not in string:
TypeError: argument of type 'NoneType' is not iterable
10.253.0.3 - - [24/Jul/2023:17:58:57 -0700] "POST /api/recipe-from-source/ HTTP/1.1" 500 145 "-" "Spectator-0.6.0"
```

**Comment by wtfreely** [comment]
I'm a moron, didn't realize API requires a data field, even if it's empty.
