### ISSUE TITLE
Issue adding some recipes via web import

### ISSUE THREAD

**Issue by marmata** [TandoorRecipes/recipes#2812]
### Tandoor Version

1.5.10

### Import URL

https://www.fattoincasadabenedetta.it/ricetta/dahl-di-lenticchie/

### When did the issue happen?

16/12/2023

### Response / message shown

```shell
2023-12-16T07:34:11.412194461Z 172.21.0.4 - myuser [16/Dec/2023:08:34:11 +0100] "GET /data/import/url HTTP/1.0" 200 22184 "https://my.web.url/search/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
2023-12-16T07:34:11.552022915Z 172.21.0.4 - myuser [16/Dec/2023:08:34:11 +0100] "GET /static/vue/css/import_view.6a6a6c498702.css HTTP/1.0" 200 0 "https://my.web.url/data/import/url" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
2023-12-16T07:34:11.552724558Z 172.21.0.4 - myuser [16/Dec/2023:08:34:11 +0100] "GET /static/vue/js/import_view.f52cd75761f8.js HTTP/1.0" 200 0 "https://my.web.url/data/import/url" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
2023-12-16T07:34:12.299874775Z 172.21.0.4 - myuser [16/Dec/2023:08:34:12 +0100] "GET /static/webfonts/fa-regular-400.f5f2566b93e8.woff2 HTTP/1.0" 200 0 "https://my.web.url/static/fontawesome/fontawesome_all.min.2acd020d0b21.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
2023-12-16T07:34:12.340672369Z 172.21.0.4 - myuser [16/Dec/2023:08:34:12 +0100] "GET /api/space/1/ HTTP/1.0" 200 289 "https://my.web.url/data/import/url" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
2023-12-16T07:34:12.503123150Z 172.21.0.4 - myuser [16/Dec/2023:08:34:12 +0100] "GET /manifest.json HTTP/1.0" 200 1113 "https://my.web.url/data/import/url" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
2023-12-16T07:34:12.513237769Z 172.21.0.4 - myuser [16/Dec/2023:08:34:12 +0100] "GET /static/assets/logo_color144.png HTTP/1.0" 200 0 "https://my.web.url/data/import/url" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
2023-12-16T07:34:13.945719863Z 172.21.0.4 - myuser [16/Dec/2023:08:34:13 +0100] "GET /static/assets/spinner.168a09fd2600.svg HTTP/1.0" 200 0 "https://my.web.url/static/css/app.min.050361699392.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
2023-12-16T07:34:13.979431418Z 172.21.0.4 - myuser [16/Dec/2023:08:34:13 +0100] "GET /service-worker.js HTTP/1.0" 200 33402 "https://my.web.url/service-worker.js" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
2023-12-16T07:34:14.260393191Z reording from lenticchie 150 g ben lavate to 150 g lenticchie  ben lavate
2023-12-16T07:34:14.289174328Z reording from aglio 1 spicchio to 1 spicchio aglio 
2023-12-16T07:34:14.313201618Z reording from curcuma 1 cucchiaino to 1 cucchiaino curcuma 
2023-12-16T07:34:14.327090245Z reording from curry 1 cucchiaino to 1 cucchiaino curry 
2023-12-16T07:34:14.345069455Z reording from latte di cocco 100 ml to 100 ml latte di cocco 
2023-12-16T07:34:14.358302935Z reording from passata di pomodoro 2 cucchiai to 2 cucchiai passata di pomodoro 
2023-12-16T07:34:14.384215948Z Traceback (most recent call last):
2023-12-16T07:34:14.384987392Z   File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
2023-12-16T07:34:14.385002264Z     return self.cursor.execute(sql, params)
2023-12-16T07:34:14.385397276Z psycopg2.errors.UndefinedColumn: column cookbook_propertytype.fdc_id does not exist
2023-12-16T07:34:14.385409826Z LINE 1: ...egory", "cookbook_propertytype"."open_data_slug", "cookbook_...
2023-12-16T07:34:14.385416320Z                                                              ^
2023-12-16T07:34:14.385421823Z 
2023-12-16T07:34:14.385907572Z 
2023-12-16T07:34:14.385940299Z The above exception was the direct cause of the following exception:
2023-12-16T07:34:14.385966425Z 
2023-12-16T07:34:14.386357151Z Traceback (most recent call last):
2023-12-16T07:34:14.386688021Z   File "/opt/recipes/cookbook/helper/recipe_url_import.py", line 203, in get_from_scraper
2023-12-16T07:34:14.386700134Z     recipe_json['properties'] = get_recipe_properties(request.space, scrape.schema.nutrients())
2023-12-16T07:34:14.387065527Z   File "/opt/recipes/cookbook/helper/recipe_url_import.py", line 225, in get_recipe_properties
2023-12-16T07:34:14.387077046Z     for pt in PropertyType.objects.filter(space=space, open_data_slug__in=list(properties.keys())).all():
2023-12-16T07:34:14.387423789Z   File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/query.py", line 398, in __iter__
2023-12-16T07:34:14.387444606Z     self._fetch_all()
2023-12-16T07:34:14.387797714Z   File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1881, in _fetch_all
2023-12-16T07:34:14.387809155Z     self._result_cache = list(self._iterable_class(self))
2023-12-16T07:34:14.388159820Z   File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
2023-12-16T07:34:14.388171515Z     results = compiler.execute_sql(
2023-12-16T07:34:14.388549175Z   File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
2023-12-16T07:34:14.388560837Z     cursor.execute(sql, params)
2023-12-16T07:34:14.388897911Z   File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
2023-12-16T07:34:14.388909492Z     return self._execute_with_wrappers(
2023-12-16T07:34:14.389256584Z   File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
2023-12-16T07:34:14.389267979Z     return executor(sql, params, many, context)
2023-12-16T07:34:14.389623576Z   File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
2023-12-16T07:34:14.389635061Z     with self.db.wrap_database_errors:
2023-12-16T07:34:14.389983729Z   File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
2023-12-16T07:34:14.389994808Z     raise dj_exc_value.with_traceback(traceback) from exc_value
2023-12-16T07:34:14.390435271Z   File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
2023-12-16T07:34:14.390446668Z     return self.cursor.execute(sql, params)
2023-12-16T07:34:14.392527182Z django.db.utils.ProgrammingError: column cookbook_propertytype.fdc_id does not exist
2023-12-16T07:34:14.392546572Z LINE 1: ...egory", "cookbook_propertytype"."open_data_slug", "cookbook_...
2023-12-16T07:34:14.392553429Z                                                              ^
2023-12-16T07:34:14.392558875Z 
2023-12-16T07:34:14.396746615Z 172.21.0.4 - myuser [16/Dec/2023:08:34:14 +0100] "POST /api/recipe-from-source/ HTTP/1.0" 200 5245 "https://my.web.url/data/import/url" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
2023-12-16T07:34:21.650822867Z Internal Server Error: /api/recipe/
2023-12-16T07:34:21.650843860Z Traceback (most recent call last):
2023-12-16T07:34:21.650850728Z   File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
2023-12-16T07:34:21.650856377Z     return self.cursor.execute(sql, params)
2023-12-16T07:34:21.650861701Z psycopg2.errors.UndefinedColumn: column cookbook_propertytype.fdc_id does not exist
2023-12-16T07:34:21.650883256Z LINE 1: ...egory", "cookbook_propertytype"."open_data_slug", "cookbook_...
2023-12-16T07:34:21.650901106Z                                                              ^
2023-12-16T07:34:21.650907940Z 
2023-12-16T07:34:21.650913247Z 
2023-12-16T07:34:21.650918350Z The above exception was the direct cause of the following exception:
2023-12-16T07:34:21.650923678Z 
2023-12-16T07:34:21.650928742Z Traceback (most recent call last):
2023-12-16T07:34:21.650933863Z   File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
2023-12-16T07:34:21.650939268Z     response = get_response(request)
2023-12-16T07:34:21.650944435Z   File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
2023-12-16T07:34:21.650966038Z     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2023-12-16T07:34:21.650972531Z   File "/opt/recipes/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
2023-12-16T07:34:21.650978086Z     return view_func(*args, **kwargs)
2023-12-16T07:34:21.650983316Z   File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
2023-12-16T07:34:21.650988549Z     return self.dispatch(request, *args, **kwargs)
2023-12-16T07:34:21.650993792Z   File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
2023-12-16T07:34:21.650999183Z     response = self.handle_exception(exc)
2023-12-16T07:34:21.651004278Z   File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
2023-12-16T07:34:21.651009637Z     self.raise_uncaught_exception(exc)
2023-12-16T07:34:21.651014854Z   File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
2023-12-16T07:34:21.651020129Z     raise exc
2023-12-16T07:34:21.651025218Z   File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
2023-12-16T07:34:21.651047163Z     response = handler(request, *args, **kwargs)
2023-12-16T07:34:21.651052628Z   File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/mixins.py", line 20, in create
2023-12-16T07:34:21.651057985Z     headers = self.get_success_headers(serializer.data)
2023-12-16T07:34:21.651063191Z   File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 555, in data
2023-12-16T07:34:21.651070223Z     ret = super().data
2023-12-16T07:34:21.651075991Z   File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
2023-12-16T07:34:21.651081252Z     self._data = self.to_representation(self.instance)
2023-12-16T07:34:21.651086554Z   File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/serializers.py", line 522, in to_representation
2023-12-16T07:34:21.651096687Z     ret[field.field_name] = field.to_representation(attribute)
2023-12-16T07:34:21.651102592Z   File "/opt/recipes/venv/lib/python3.10/site-packages/rest_framework/fields.py", line 1838, in to_representation
2023-12-16T07:34:21.651125373Z     return method(value)
2023-12-16T07:34:21.651130988Z   File "/opt/recipes/cookbook/serializer.py", line 884, in get_food_properties
2023-12-16T07:34:21.651136366Z     return fph.calculate_recipe_properties(obj)
2023-12-16T07:34:21.651141593Z   File "/opt/recipes/cookbook/helper/property_helper.py", line 35, in calculate_recipe_properties
2023-12-16T07:34:21.651146711Z     caches['default'].set(CacheHelper(self.space).PROPERTY_TYPE_CACHE_KEY, property_types, 60 * 60)
2023-12-16T07:34:21.651152005Z   File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/cache/backends/locmem.py", line 53, in set
2023-12-16T07:34:21.651157284Z     pickled = pickle.dumps(value, self.pickle_protocol)
2023-12-16T07:34:21.651162408Z   File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/query.py", line 351, in __getstate__
2023-12-16T07:34:21.651167592Z     self._fetch_all()
2023-12-16T07:34:21.651172708Z   File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1881, in _fetch_all
2023-12-16T07:34:21.651178083Z     self._result_cache = list(self._iterable_class(self))
2023-12-16T07:34:21.651197534Z   File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
2023-12-16T07:34:21.651204365Z     results = compiler.execute_sql(
2023-12-16T07:34:21.651209940Z   File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
2023-12-16T07:34:21.651215254Z     cursor.execute(sql, params)
2023-12-16T07:34:21.651220270Z   File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
2023-12-16T07:34:21.651225511Z     return self._execute_with_wrappers(
2023-12-16T07:34:21.651230721Z   File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
2023-12-16T07:34:21.651236011Z     return executor(sql, params, many, context)
2023-12-16T07:34:21.651241159Z   File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
2023-12-16T07:34:21.651246403Z     with self.db.wrap_database_errors:
2023-12-16T07:34:21.651252423Z   File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
2023-12-16T07:34:21.651257849Z     raise dj_exc_value.with_traceback(traceback) from exc_value
2023-12-16T07:34:21.651278393Z   File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
2023-12-16T07:34:21.651284926Z     return self.cursor.execute(sql, params)
2023-12-16T07:34:21.651290257Z django.db.utils.ProgrammingError: column cookbook_propertytype.fdc_id does not exist
2023-12-16T07:34:21.651300219Z LINE 1: ...egory", "cookbook_propertytype"."open_data_slug", "cookbook_...
2023-12-16T07:34:21.651306176Z                                                              ^
2023-12-16T07:34:21.651311483Z 
2023-12-16T07:34:21.657304269Z 172.21.0.4 - myuser [16/Dec/2023:08:34:21 +0100] "POST /api/recipe/ HTTP/1.0" 500 145 "https://my.web.url/data/import/url" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
```

**Comment by vabene1111** [comment]
fdc_id is a new field on property type, looks like your migrations did not run

**Comment by marmata** [comment]
Oh I understand! Would it be safe to force the migration inside the
container via manage.py migrate?

I'm Winston Wolf, I solve problems.

**Comment by vabene1111** [comment]
feel free to try it but if they dont run typically its something wrong

**Comment by marmata** [comment]
Ok so the migration worked! Looks like I had a couple of duplicated keywords so one of the migration was failing (probably since a lot of versions!). I removed the duplicated rerun the migrations and all is working now! BTW I didn't find anywhere how to properly run the manage script using docker? Perhaps worth adding to the docs. I run it this way, by looking at the docker structure, not even sure it's the correct one: 
`sudo docker-compose exec -T web_recipes /opt/recipes/venv/bin/python3 /opt/recipes/manage.py migrate`

Thanks!
