### ISSUE TITLE
Migration Error

### ISSUE THREAD

**Issue by tuetenk0pp** [TandoorRecipes/recipes#2834]
### Tandoor Version

abf8f791360b2bc4a5c7d011877668679bcbb3f2

### Setup

Unraid

### Reverse Proxy

SWAG

### Bug description

I can not access any Recipes or other database related content. The issue first occurred after an update. It seems to be related to some migration step that fails.

## Here is the Tandoor Debug report from the web UI:

```log
Gunicorn Media: False
Sqlite: True
Debug: True

SERVER_PROTOCOL:HTTP/1.1
REMOTE_ADDR:***
SERVER_PORT:8080

HTTP_HOST:***
HTTP_USER_AGENT:Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0
HTTP_ACCEPT:text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
HTTP_ACCEPT_LANGUAGE:de,en-US;q=0.7,en;q=0.3
HTTP_ACCEPT_ENCODING:gzip, deflate
HTTP_DNT:1
HTTP_CONNECTION:keep-alive
HTTP_COOKIE:***

wsgi.errors:<gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x14a8627974f0>
wsgi.version:(1, 0)
wsgi.multithread:True
wsgi.multiprocess:True
wsgi.run_once:False
wsgi.file_wrapper:
wsgi.input_terminated:True
wsgi.input:<gunicorn.http.body.Body object at 0x14a8627972e0>
wsgi.url_scheme:http
```

As you can see, Tandoor fell back to the sqlite database although the postgres configuration is correct and tandoor actually connects to postgres to run the migration.

## Here is the Tandoor Log:

```log
Checking configuration...
Waiting for database to be ready...
Database is ready
Migrating database
Operations to perform:
  Apply all migrations: account, admin, auth, authtoken, contenttypes, cookbook, oauth2_provider, sessions, sites, socialaccount
Running migrations:
Traceback (most recent call last):
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "kw_unique_name_per_space"
DETAIL:  Key (space_id, name)=(1, 🌮 schnell) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/recipes/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 356, in handle
    post_migrate_state = executor.migrate(
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/migrations/migration.py", line 132, in apply
    operation.database_forwards(
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/opt/recipes/cookbook/migrations/0200_alter_propertytype_options_remove_keyword_icon_and_more.py", line 17, in migrate_icons
    Keyword.objects.update(name=Concat(F('icon'), Value(' '), F('name')))
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1206, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1984, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "kw_unique_name_per_space"
DETAIL:  Key (space_id, name)=(1, 🌮 schnell) already exists.

  Applying cookbook.0200_alter_propertytype_options_remove_keyword_icon_and_more...Generating static files
js-reverse file written to /opt/recipes/cookbook/static/django_js_reverse

1 static file copied to '/opt/recipes/staticfiles', 647 unmodified, 1396 post-processed.
Done
```

## Here the corresponding postgres log:

```log
2023-12-27 18:18:10.576 CET [22477] ERROR:  duplicate key value violates unique constraint "kw_unique_name_per_space"
2023-12-27 18:18:10.576 CET [22477] DETAIL:  Key (space_id, name)=(1, 🌮 schnell) already exists.
2023-12-27 18:18:10.576 CET [22477] STATEMENT:  UPDATE "cookbook_keyword" SET "name" = CONCAT(("cookbook_keyword"."icon")::text, (CONCAT((' ')::text, ("cookbook_keyword"."name")::text))::text)
```

**Comment by smilerz** [comment]
You have a duplicate keyword (1, 🌮 schnell) - you'll need to modify the database directly eliminating the duplicate keyword.

**Comment by tuetenk0pp** [comment]
Thanks! That was it

**Comment by vabene1111** [comment]
Btw this is still a bug, I screwed the migrations and need to fix them, there is a seperate issue for that
