### ISSUE TITLE
Server error 500 (pgsql issue ?)

### ISSUE THREAD

**Issue by tugdualenligne** [TandoorRecipes/recipes#2911]
### Tandoor Version

latest 1.5.11

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Bug description

I get a server error 500 when trying to reach while it was working perfectly some weeks ago
I see also errors in the log of the posgresql container

### Relevant logs

```shell
postgresql logs:
2024-01-28 20:48:54.954 UTC [2939] ERROR:  column cookbook_space.space_theme does not exist at character 85
2024-01-28 20:48:54.954 UTC [2939] STATEMENT:  SELECT "cookbook_space"."id", "cookbook_space"."name", "cookbook_space"."image_id", "cookbook_space"."space_theme", "cookbook_space"."custom_space_theme_id", "cookbook_space"."nav_logo_id", "cookbook_space"."nav_bg_color", "cookbook_space"."nav_text_color", "cookbook_space"."app_name", "cookbook_space"."logo_color_32_id", "cookbook_space"."logo_color_128_id", "cookbook_space"."logo_color_144_id", "cookbook_space"."logo_color_180_id", "cookbook_space"."logo_color_192_id", "cookbook_space"."logo_color_512_id", "cookbook_space"."logo_color_svg_id", "cookbook_space"."created_by_id", "cookbook_space"."created_at", "cookbook_space"."message", "cookbook_space"."max_recipes", "cookbook_space"."max_file_storage_mb", "cookbook_space"."max_users", "cookbook_space"."use_plural", "cookbook_space"."allow_sharing", "cookbook_space"."no_sharing_limit", "cookbook_space"."demo", "cookbook_space"."internal_note" FROM "cookbook_space" WHERE "cookbook_space"."id" = 1 LIMIT 21
```

I get also these logs from the tandoor container:
```shell
Checking configuration...
Waiting for database to be ready...
Database is ready
Migrating database
Operations to perform:
  Apply all migrations: account, admin, auth, authtoken, contenttypes, cookbook, oauth2_provider, sessions, sites, socialaccount
Running migrations:
Traceback (most recent call last):
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type integer: "170931-ground"
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/recipes/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 356, in handle
    post_migrate_state = executor.migrate(
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/migrations/migration.py", line 132, in apply
    operation.database_forwards(
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/migrations/operations/fields.py", line 235, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/base/schema.py", line 830, in alter_field
    self._alter_field(
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/postgresql/schema.py", line 288, in _alter_field
    super()._alter_field(
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/base/schema.py", line 1055, in _alter_field
    self.execute(
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/postgresql/schema.py", line 48, in execute
    return super().execute(sql, None)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/base/schema.py", line 201, in execute
    cursor.execute(sql, params)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
django.db.utils.DataError: invalid input syntax for type integer: "170931-ground"
  Applying cookbook.0205_alter_food_fdc_id_alter_propertytype_fdc_id...Generating static files
js-reverse file written to /opt/recipes/cookbook/static/django_js_reverse
1 static file copied to '/opt/recipes/staticfiles', 648 unmodified, 1397 post-processed.```

**Comment by smilerz** [comment]
Duplicate #2894
