### ISSUE TITLE
Python Client Generation

### ISSUE THREAD

**Issue by joe-hannes** [TandoorRecipes/recipes#2945]
### Tandoor Version

1.5.11

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

When trying to generate a python client with the OpenApi Generator a faulty client is generated.

Reproduction:

```bash
sudo docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate     -i <ip_addr:port>/openapi/?format=openapi-json     -g python     -o /local/out/python
```

- cd into generated `open_api client/api`
- `pip install . `
- start a python session and `import openapi_client`

### Relevant logs

```shell
Python 3.12.1 (main, Jan  4 2024, 09:41:05) [GCC 13.2.1 20231014] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import openapi_client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/config/pyscript/out/python/openapi_client/__init__.py", line 20, in <module>
    from openapi_client.api.api_api import ApiApi
  File "/config/pyscript/out/python/openapi_client/api/__init__.py", line 4, in <module>
    from openapi_client.api.api_api import ApiApi
  File "/config/pyscript/out/python/openapi_client/api/api_api.py", line 35, in <module>
    from openapi_client.models.int import Int
ModuleNotFoundError: No module named 'openapi_client.models.int'
```

**Comment by smilerz** [comment]
If you identify that the root cause please open a PR or an issue identifying exactly what needs to be changed.
