### ISSUE TITLE
Cant reach system settings

### ISSUE THREAD

**Issue by grifmo** [TandoorRecipes/recipes#3093]
### Tandoor Version

Latest Docker Compose

### Setup

Docker / Docker-Compose

### Reverse Proxy

Others (please state below)

### Other

nginx reverse Proxy

### Bug description

when accessing system page, am greeted with an error and debug output:

<html><body>
<h1>TypeError
       at /system/</h1>
  <pre class="exception_value">'&gt;=' not supported between instances of 'tuple' and 'int'</pre>
  
Request Method: | GET
-- | --
https://**********************/system/
4.2.11
TypeError
'>=' not supported between instances of 'tuple' and 'int'
/opt/recipes/cookbook/views/views.py, line 300, in system
cookbook.views.views.system
/opt/recipes/venv/bin/python
3.12.2
['/opt/recipes',  '/opt/recipes/venv/bin',  '/usr/local/lib/python312.zip',  '/usr/local/lib/python3.12',  '/usr/local/lib/python3.12/lib-dynload',  '/opt/recipes/venv/lib/python3.12/site-packages']

</body>
</html>

### Relevant logs

```shell
Environment:


Request Method: GET
Request URL: https://*******.**************.**/system/

Django Version: 4.2.11
Python Version: 3.12.2
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'django.contrib.postgres',
 'oauth2_provider',
 'django_prometheus',
 'django_tables2',
 'corsheaders',
 'crispy_forms',
 'crispy_bootstrap4',
 'rest_framework',
 'rest_framework.authtoken',
 'django_cleanup.apps.CleanupConfig',
 'webpack_loader',
 'django_js_reverse',
 'hcaptcha',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'cookbook.apps.CookbookConfig',
 'treebeard',
 'debug_toolbar']
Installed Middleware:
['corsheaders.middleware.CorsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'cookbook.helper.scope_middleware.ScopeMiddleware',
 'allauth.account.middleware.AccountMiddleware',
 'debug_toolbar.middleware.DebugToolbarMiddleware']



Traceback (most recent call last):
  File "/opt/recipes/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/recipes/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/recipes/cookbook/views/views.py", line 300, in system
    if postgres_ver >= postgres_current:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Exception Type: TypeError at /system/
Exception Value: '>=' not supported between instances of 'tuple' and 'int'
```

**Comment by smilerz** [comment]
Duplicate

**Comment by grifmo** [comment]
Could you please link to the duplicate issue?
