### ISSUE TITLE
Import from source fails

### ISSUE THREAD

**Issue by tomtjes** [TandoorRecipes/recipes#3267]
### Tandoor Version

1.5.19

### Setup

Docker / Docker-Compose

### Reverse Proxy

SWAG

### Bug description

Importing a recipe via `/data/import/url > Source` from a valid json source fails. I think it seems to expect a URL? Bookmarklet import also fails when only html and no url is provided.

### Relevant logs

```shell
::ffff:172.30.0.2 - - [22/Aug/2024:17:33:03 +0200] "GET /static/assets/logo_color_32.png HTTP/1.1" 200 0 "https://recipes.domain.tld/data/import/url?id=376" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15"
::ffff:172.30.0.2 - - [22/Aug/2024:17:33:04 +0200] "GET /api/space/1/ HTTP/1.1" 200 651 "https://recipes.domain.tld/data/import/url?id=376" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15"
Internal Server Error: /api/recipe-from-source/
Traceback (most recent call last):
  File "/opt/recipes/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/recipes/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/recipes/venv/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/recipes/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/recipes/venv/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/recipes/venv/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/recipes/venv/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/recipes/venv/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/recipes/cookbook/views/api.py", line 1461, in post
    scrape = scrape_html(html=data, org_url=url, supported_only=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/recipes/venv/lib/python3.12/site-packages/recipe_scrapers/__init__.py", line 842, in scrape_html
    host_name = get_host_name(org_url)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/recipes/venv/lib/python3.12/site-packages/recipe_scrapers/_utils.py", line 288, in get_host_name
    return url_path_to_dict(url.replace("://www.", "://"))["host"]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
::ffff:172.30.0.2 - - [22/Aug/2024:17:33:08 +0200] "POST /api/recipe-from-source/ HTTP/1.1" 500 118632 "https://recipes.domain.tld/data/import/url?id=376" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15"
::ffff:172.30.0.2 - - [22/Aug/2024:17:33:08 +0200] "GET /static/webfonts/poppins_latin_700.woff2 HTTP/1.1" 200 0 "https://recipes.domain.tld/data/import/url?id=376" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15"
```

**Comment by smilerz** [comment]
Is this from an actual source or one that you constructed?
Are you using JSON or HTML source?

**Comment by tomtjes** [comment]
Constructed sources that worked with the previous version.
Example:
```
{
  "@context": "https://schema.org/",
  "@type": "Recipe",
  "name": "Mediterranean Stuffed Zucchini",
  "description": "Mediterranean Stuffed Zucchini topped with breadcrumbs and cheese.",
  "image": "close up view of Mediterranean Stuffed Zucchini topped with breadcrumbs and cheese on a white platter",
  "recipeIngredient": [
    "Zucchini",
    "Olive oil",
    "Onion",
    "Garlic",
    "Ground lamb",
    "Coarse salt",
    "Black pepper",
    "Tomato sauce",
    "Tomatoes",
    "Feta cheese",
    "Pine nuts",
    "Mint leaves",
    "Bread crumbs",
    "Mozzarella cheese",
    "Water"
  ],
  "recipeInstructions": [
    {
      "@type": "HowToStep",
      "text": "Preheat oven to 450 degrees F (230 degrees C)."
    },
    {
      "@type": "HowToStep",
      "text": "Use a melon baller to separate and remove seeds and pulp separately from the zucchini, carving out each half and leaving about a half-inch shell. Chop zucchini pulp into pieces about 1/4 inch in diameter. Discard seeds."
    },
    {
      "@type": "HowToStep",
      "text": "Heat olive oil in a large skillet over medium heat. Cook and stir onion and garlic in hot oil until tender, about 5 minutes. Add ground lamb; continue to cook and stir until lamb is lightly browned, 5 to 7 minutes. Stir chopped zucchini into the lamb mixture. Reduce heat to medium-low. Simmer mixture until the zucchini is hot, about 3 minutes. Drain excess grease. Season lamb mixture with coarse salt and black pepper."
    },
    {
      "@type": "HowToStep",
      "text": "Remove skillet from heat. Stir tomato sauce, tomatoes, feta cheese, pine nuts, and 1/4 cup mint leaves through the lamb mixture; spoon into the zucchini halves."
    },
    {
      "@type": "HowToStep",
      "text": "Put stuffed zucchini halves into a large baking dish. Pour water into the baking dish."
    },
    {
      "@type": "HowToStep",
      "text": "Bake in preheated oven for 30 minutes."
    },
    {
      "@type": "HowToStep",
      "text": "Mix bread crumbs and mozzarella cheese in a bowl. Sprinkle 1/4 cup mint leaves over the zucchini and top with the bread crumb mixture."
    },
    {
      "@type": "HowToStep",
      "text": "Continue baking until the top is crusty and browned, about 10 minutes more."
    }
  ],
  "cookTime": "PT40M",
  "prepTime": "PT20M",
  "totalTime": "PT60M",
  "cookingMethod": "Baking",
  "nutrition": {
    "@type": "NutritionInformation",
    "servingSize": "1 stuffed zucchini"
  },
  "recipeYield": "4 servings",
  "author": {
    "@type": "Person",
    "name": "Cook's Note"
  },
  "recipeCategory": "Main course",
  "recipeCuisine": "Mediterranean",
  "note": "You can use basil in place of the mint to send the flavor into an Italian or Middle Eastern direction. If you do, consider changing the meat to ground beef, the nuts to walnuts, and the cheese to all mozzarella."
}
```

**Comment by tomtjes** [comment]
Thank you!
