### ISSUE TITLE
Error 500 on Import from source

### ISSUE THREAD

**Issue by jjauzion** [TandoorRecipes/recipes#3295]
### Tandoor Version

1.5.19

### Setup

Others (please state below)

### Reverse Proxy

Others (please state below)

### Other

cloudron

### Bug description

What I do:
- Go to "Import Recipe" 
- Then click the "Source" tab
- Then past the following json
- Click import

Result:
Get a error 500 "Failure There was an error importing the recipe!"

Here is the console log error from the browser:
<img width="828" alt="Screenshot 2024-09-06 at 13 47 52" src="https://github.com/user-attachments/assets/711dab70-e15f-46a9-b12c-1c510cdda4b2">

Here is the json which seems well formatted
```
{
  "@context": "https://schema.org/",
  "@type": "Recipe",
  "name": "Katchapouri (pain au fromage)",
  "recipeIngredient": [
    "4 g de levure sèche de boulanger",
    "8 à 9 cl de lait entier",
    "5 g de sucre en poudre",
    "250 g de farine",
    "8 g de sel",
    "1/2 œuf",
    "40 g d'huile végétale",
    "15 g de beurre",
    "250 g de mozzarella",
    "150 g de feta",
    "1/2 œuf",
    "Beurre"
  ],
  "recipeInstructions": [
    "Délayez la levure dans le lait tiède et le sucre. Remuez et laissez reposer quelques minutes.",
    "Râpez les fromages et déposez-les dans une passoire ou un tamis pour en extraire le jus résiduel.",
    "Versez la farine dans un saladier, ajoutez le sel et formez un puits. Incorporez le demi-œuf battu, l'huile et la moitié du mélange levure/lait/sucre. Ajoutez le beurre, mélangez, puis continuez de pétrir la pâte sur le plan de travail. Ajoutez au fur et à mesure le reste du mélange levure/lait/sucre. Lorsque la pâte est lisse et homogène, déposez-la dans un saladier, couvrez et laissez reposer jusqu'à ce qu'elle double de volume.",
    "Pendant ce temps, récupérez les 3/4 des fromages égouttés et déposez-les dans un saladier. Réservez le reste dans un petit contenant. Incorporez 2 cuil. à café du demi-œuf battu au reste des fromages râpés restants. Mélangez le reste du demi-œuf battu avec les 3/4 des fromages râpés jusqu'à obtenir une boule compacte.",
    "Dégazez la pâte, déposez-la sur une feuille de papier sulfurisé et étalez-la du bout des doigts. Déposez au centre la boule de fromage, puis recouvrez-la avec la pâte pour obtenir une plus grosse boule. Abaissez la pâte du bout des doigts, puis terminez à l'aide d'un rouleau à pâtisserie. Faites un petit trou au centre de la pâte et déposez-la sur une plaque allant au four. Préchauffez le four à 200 °C (th. 6-7). Répartissez le reste des fromages sur la surface de la pâte, puis enfournez pour 20 min environ. Le pain va gonfler et le fromage gratiner.",
    "À la sortie du four, faites fondre un petit morceau de beurre sur les bords du pain. Dégustez chaud."
  ]
}
```

### Relevant logs

```shell
Sep 06 13:47:54 Internal Server Error: /api/recipe-from-source/
Sep 06 13:47:54 Traceback (most recent call last):
Sep 06 13:47:54 File "/app/code/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
Sep 06 13:47:54 response = get_response(request)
Sep 06 13:47:54 File "/app/code/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
Sep 06 13:47:54 response = wrapped_callback(request, *callback_args, **callback_kwargs)
Sep 06 13:47:54 File "/app/code/.venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
Sep 06 13:47:54 return view_func(*args, **kwargs)
Sep 06 13:47:54 File "/app/code/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
Sep 06 13:47:54 return self.dispatch(request, *args, **kwargs)
Sep 06 13:47:54 File "/app/code/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
Sep 06 13:47:54 response = self.handle_exception(exc)
Sep 06 13:47:54 File "/app/code/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
Sep 06 13:47:54 self.raise_uncaught_exception(exc)
Sep 06 13:47:54 File "/app/code/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
Sep 06 13:47:54 raise exc
Sep 06 13:47:54 File "/app/code/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
Sep 06 13:47:54 response = handler(request, *args, **kwargs)
Sep 06 13:47:54 File "/app/code/tandoor/cookbook/views/api.py", line 1461, in post
Sep 06 13:47:54 scrape = scrape_html(html=data, org_url=url, supported_only=False)
Sep 06 13:47:54 File "/app/code/.venv/lib/python3.10/site-packages/recipe_scrapers/__init__.py", line 842, in scrape_html
Sep 06 13:47:54 host_name = get_host_name(org_url)
Sep 06 13:47:54 File "/app/code/.venv/lib/python3.10/site-packages/recipe_scrapers/_utils.py", line 288, in get_host_name
Sep 06 13:47:54 return url_path_to_dict(url.replace("://www.", "://"))["host"] <30>1 2024-09-06T11:47:54Z 4v9c.l.time4vps.cloud a885b77c-238d-4ea7-b606-c430381c9855 165713 a885b77c-238d-4ea7-b606-c430381c9855 - TypeError: 'NoneType' object is not subscriptable
Sep 06 13:47:54 127.0.0.1 - - [06/Sep/2024:11:47:54 +0000] "POST /api/recipe-from-source/ HTTP/1.0" 500 117829 "https://tandoor.espace.ninja/data/import/url" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" <30>1 2024-09-06T11:47:54Z 4v9c.l.time4vps.cloud a885b77c-238d-4ea7-b606-c430381c9855 165713 a885b77c-238d-4ea7-b606-c430381c9855 - 172.18.0.1 - - [06/Sep/2024:11:47:54 +0000] "POST /api/recipe-from-source/ HTTP/1.1" 500 117829 "https://tandoor.espace.ninja/data/import/url" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
Sep 06 13:47:59 Internal Server Error: /api/recipe-from-source/ <30>1 2024-09-06T11:47:59Z 4v9c.l.time4vps.cloud a885b77c-238d-4ea7-b606-c430381c9855 165713 a885b77c-238d-4ea7-b606-c430381c9855 - Traceback (most recent call last): <30>1 2024-09-06T11:47:59Z 4v9c.l.time4vps.cloud a885b77c-238d-4ea7-b606-c430381c9855 165713 a885b77c-238d-4ea7-b606-c430381c9855 - File "/app/code/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner <30>1 2024-09-06T11:47:59Z 4v9c.l.time4vps.cloud a885b77c-238d-4ea7-b606-c430381c9855 165713 a885b77c-238d-4ea7-b606-c430381c9855 - response = get_response(request) <30>1 2024-09-06T11:47:59Z 4v9c.l.time4vps.cloud a885b77c-238d-4ea7-b606-c430381c9855 165713 a885b77c-238d-4ea7-b606-c430381c9855 - File "/app/code/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response <30>1 2024-09-06T11:47:59Z 4v9c.l.time4vps.cloud a885b77c-238d-4ea7-b606-c430381c9855 165713 a885b77c-238d-4ea7-b606-c430381c9855 - response = wrapped_callback(request, *callback_args, **callback_kwargs) <30>1 2024-09-06T11:47:59Z 4v9c.l.time4vps.cloud a885b77c-238d-4ea7-b606-c430381c9855 165713 a885b77c-238d-4ea7-b606-c430381c9855 - File "/app/code/.venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view <30>1 2024-09-06T11:47:59Z 4v9c.l.time4vps.cloud a885b77c-238d-4ea7-b606-c430381c9855 165713 a885b77c-238d-4ea7-b606-c430381c9855 - return view_func(*args, **kwargs) <30>1 2024-09-06T11:47:59Z 4v9c.l.time4vps.cloud a885b77c-238d-4ea7-b606-c430381c9855 165713 a885b77c-238d-4ea7-b606-c430381c9855 - File "/app/code/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view <30>1 2024-09-06T11:47:59Z 4v9c.l.time4vps.cloud a885b77c-238d-4ea7-b606-c430381c9855 165713 a885b77c-238d-4ea7-b606-c430381c9855 - return self.dispatch(request, *args, **kwargs)
Sep 06 13:47:59 File "/app/code/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch <30>1 2024-09-06T11:47:59Z 4v9c.l.time4vps.cloud a885b77c-238d-4ea7-b606-c430381c9855 165713 a885b77c-238d-4ea7-b606-c430381c9855 - response = self.handle_exception(exc) <30>1 2024-09-06T11:47:59Z 4v9c.l.time4vps.cloud a885b77c-238d-4ea7-b606-c430381c9855 165713 a885b77c-238d-4ea7-b606-c430381c9855 - File "/app/code/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception <30>1 2024-09-06T11:47:59Z 4v9c.l.time4vps.cloud a885b77c-238d-4ea7-b606-c430381c9855 165713 a885b77c-238d-4ea7-b606-c430381c9855 - self.raise_uncaught_exception(exc) <30>1 2024-09-06T11:47:59Z 4v9c.l.time4vps.cloud a885b77c-238d-4ea7-b606-c430381c9855 165713 a885b77c-238d-4ea7-b606-c430381c9855 - File "/app/code/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception <30>1 2024-09-06T11:47:59Z 4v9c.l.time4vps.cloud a885b77c-238d-4ea7-b606-c430381c9855 165713 a885b77c-238d-4ea7-b606-c430381c9855 - raise exc <30>1 2024-09-06T11:47:59Z 4v9c.l.time4vps.cloud a885b77c-238d-4ea7-b606-c430381c9855 165713 a885b77c-238d-4ea7-b606-c430381c9855 - File "/app/code/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch <30>1 2024-09-06T11:47:59Z 4v9c.l.time4vps.cloud a885b77c-238d-4ea7-b606-c430381c9855 165713 a885b77c-238d-4ea7-b606-c430381c9855 - response = handler(request, *args, **kwargs) <30>1 2024-09-06T11:47:59Z 4v9c.l.time4vps.cloud a885b77c-238d-4ea7-b606-c430381c9855 165713 a885b77c-238d-4ea7-b606-c430381c9855 - File "/app/code/tandoor/cookbook/views/api.py", line 1461, in post <30>1 2024-09-06T11:47:59Z 4v9c.l.time4vps.cloud a885b77c-238d-4ea7-b606-c430381c9855 165713 a885b77c-238d-4ea7-b606-c430381c9855 - scrape = scrape_html(html=data, org_url=url, supported_only=False) <30>1 2024-09-06T11:47:59Z 4v9c.l.time4vps.cloud a885b77c-238d-4ea7-b606-c430381c9855 165713 a885b77c-238d-4ea7-b606-c430381c9855 - File "/app/code/.venv/lib/python3.10/site-packages/recipe_scrapers/__init__.py", line 842, in scrape_html <30>1 2024-09-06T11:47:59Z 4v9c.l.time4vps.cloud a885b77c-238d-4ea7-b606-c430381c9855 165713 a885b77c-238d-4ea7-b606-c430381c9855 - host_name = get_host_name(org_url) <30>1 2024-09-06T11:47:59Z 4v9c.l.time4vps.cloud a885b77c-238d-4ea7-b606-c430381c9855 165713 a885b77c-238d-4ea7-b606-c430381c9855 - File "/app/code/.venv/lib/python3.10/site-packages/recipe_scrapers/_utils.py", line 288, in get_host_name <30>1 2024-09-06T11:47:59Z 4v9c.l.time4vps.cloud a885b77c-238d-4ea7-b606-c430381c9855 165713 a885b77c-238d-4ea7-b606-c430381c9855 - return url_path_to_dict(url.replace("://www.", "://"))["host"] <30>1 2024-09-06T11:47:59Z 4v9c.l.time4vps.cloud a885b77c-238d-4ea7-b606-c430381c9855 165713 a885b77c-238d-4ea7-b606-c430381c9855 - TypeError: 'NoneType' object is not subscriptable
Sep 06 13:47:59 172.18.0.1 - - [06/Sep/2024:11:47:59 +0000] "POST /api/recipe-from-source/ HTTP/1.1" 500 117829 "https://tandoor.espace.ninja/data/import/url" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
Sep 06 13:47:59 127.0.0.1 - - [06/Sep/2024:11:47:59 +0000] "POST /api/recipe-from-source/ HTTP/1.0" 500 117829 "https://tandoor.espace.ninja/data/import/url" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
Sep 06 13:48:00 127.0.0.1 - - [06/Sep/2024:11:48:00 +0000] "GET / HTTP/1.0" 302 0 "-" "Mozilla (CloudronHealth)"
```

**Comment by smilerz** [comment]
duplicate #3267
