### ISSUE TITLE
How to enable PDF export?

### ISSUE THREAD

**Issue by zodac** [TandoorRecipes/recipes#3309]
### Issue

I wanted to try exporting some of my recipes in PDF format, but when I try to use it, I get the error:

`The PDF Exporter is not enabled on this instance as it is still in an experimental state.`

Is there a way to enable it?

### Tandoor Version

1.5.19

### OS Version

Docker

### Setup

Docker / Docker-Compose

### Reverse Proxy

Others (please state below)

### Other

Apache

**Comment by AtharvaGurao** [comment]
I can help you with it

**Comment by zodac** [comment]
So I tried to enable it, but found the following in the logs (main snippets, DEBUG mode enabled):

```
[INFO] Starting Chromium download.
...
100%|██████████| 183M/183M [02:41<00:00, 1.13Mb/s]
[INFO] Beginning extraction
...
[INFO] Chromium extracted to: /root/.local/share/pyppeteer/local-chromium/1181205
Exception in thread Thread-2 (do_export):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/recipes/cookbook/integration/integration.py", line 68, in do_export
    files = self.get_files_from_recipes(recipes, el, self.request.COOKIES)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/recipes/cookbook/integration/pdfexport.py", line 56, in get_files_from_recipes
    return asyncio.run(self.get_files_from_recipes_async(recipes, el, cookie))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/recipes/cookbook/integration/pdfexport.py", line 18, in get_files_from_recipes_async
    browser = await launch(
              ^^^^^^^^^^^^^
  File "/opt/recipes/venv/lib/python3.12/site-packages/pyppeteer/launcher.py", line 307, in launch
    return await Launcher(options, **kwargs).launch()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/recipes/venv/lib/python3.12/site-packages/pyppeteer/launcher.py", line 148, in launch
    self.proc = subprocess.Popen(  # type: ignore
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/share/pyppeteer/local-chromium/1181205/chrome-linux/chrome'
```

Not sure if there might be some permission issues? I'm using Docker on Windows, but don't have any volume mounts for the '/root/.local/share/' directory.
