### ISSUE TITLE
PDF export unable to find downloaded Chromium binary

### ISSUE THREAD

**Issue by zodac** [TandoorRecipes/recipes#3316]
### Tandoor Version

1.5.19

### Setup

Docker / Docker-Compose

### Reverse Proxy

Apache2

### Bug description

I enabled the experimental PDF export option (as discussed in https://github.com/TandoorRecipes/recipes/issues/3309), but when I attempt to export any recipe (single or all), it fails due to Chromium not being found. I can see in the logs that the binary seems to download, so I'm unsure why it's failing.

Not sure if there might be some permission issues? I'm using Docker on Windows, but don't have any volume mounts for the '/root/.local/share/' directory.

### Relevant logs

```shell
[INFO] Starting Chromium download.
...
100%|██████████| 183M/183M [02:41<00:00, 1.13Mb/s]
[INFO] Beginning extraction
...
[INFO] Chromium extracted to: /root/.local/share/pyppeteer/local-chromium/1181205
Exception in thread Thread-2 (do_export):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/recipes/cookbook/integration/integration.py", line 68, in do_export
    files = self.get_files_from_recipes(recipes, el, self.request.COOKIES)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/recipes/cookbook/integration/pdfexport.py", line 56, in get_files_from_recipes
    return asyncio.run(self.get_files_from_recipes_async(recipes, el, cookie))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/recipes/cookbook/integration/pdfexport.py", line 18, in get_files_from_recipes_async
    browser = await launch(
              ^^^^^^^^^^^^^
  File "/opt/recipes/venv/lib/python3.12/site-packages/pyppeteer/launcher.py", line 307, in launch
    return await Launcher(options, **kwargs).launch()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/recipes/venv/lib/python3.12/site-packages/pyppeteer/launcher.py", line 148, in launch
    self.proc = subprocess.Popen(  # type: ignore
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/share/pyppeteer/local-chromium/1181205/chrome-linux/chrome'
```

**Comment by vabene1111** [comment]
the PDF export is an experiemtal community feature that I do not offer support for, sorry. The exact issue you are having is one of the main reasons. 

Community is welcome to fix this :)

**Comment by zodac** [comment]
BTW, I came back to take a look at this. I was able to get the export 'working' by running `chmod -R 0777 /root/` to give access to the directory where the chromium binary is. But even then I just get a .zip file with the recipe in JSON format.

Did this ever work? Not sure if I'm just doing something wrong, but if not, it seems pointless to include something that doesn't work and isn't going to be maintained - may as well remove the option (or hide it to avoid confusion)?

**Comment by koenieee** [comment]
Someone ever get this working on proxmox? Where can I find the chromium library and how can I append this to my LXContainer?

**Comment by vabene1111** [comment]
pdf export is for now dropped with Tandoor 2 and given that its a community hack I sadly lack the time to support it.
