### ISSUE TITLE
K3s running DietPi v9.7.1 on Raspberry Pi 4 Model B Rev 1.2

### ISSUE THREAD

**Issue by sruckh** [TandoorRecipes/recipes#3319]
### Issue

I am trying to install Tandoor Recipes on K3s cluster running DietPi on Raspberry Pi 4.  I am trying to follow the k8s instructions which seemed fairly straightforward.  Create my secrets, change my ingress, and apply the .yaml files.  I don't think the nginx container ever comes up. The is in the logs for the recipes pod:

Error from server (BadRequest): container "recipes-nginx" in pod "recipes-86df8b96cd-sgfsj" is waiting to start: PodInitializing

Neither pod is coming up:

recipes-postgresql-0                0/1     CrashLoopBackOff        54 (4m14s ago)   4h16m
recipes-86df8b96cd-sgfsj            0/2     Init:CrashLoopBackOff   18 (119s ago)    114m

The two PVCs were created, the secrets were created. the services were created, and the ingress controller was created.

It looked like other people in the "Discussions" were running k3s.  I know k8s is not officially supported, but is anyone else running a similar configuration on k3s with Raspberry Pi?  The docs seemed fairly straightforward, and not too many things to tinker with that would be problematic.  Anyone have suggestions, or things that I should look at?

Thank you.

### Tandoor Version

vabene1111/recipes pulled 09/23/2024

### OS Version

DietPi 9.7.1

### Setup

Kubernetes

### Reverse Proxy

Others (please state below)

### Other

Lighttpd

### Environment file

```shell
No environment file
```

### Docker-Compose file

```shell
No docker compose. Using Kubernetes deployment from github.
```

### Relevant logs

```shell
dietpi@ruxcluster01:~/recipes/docs/install/k8s$ kubectl logs recipes-postgresql-0
Defaulted container "recipes-db" out of: recipes-db, init-chmod-data (init)
exec /entrypoint.sh: exec format error

dietpi@ruxcluster01:~/recipes/docs/install/k8s$ kubectl logs recipes-86df8b96cd-sgfsj
Defaulted container "recipes-nginx" out of: recipes-nginx, recipes, init-chmod-data (init)
Error from server (BadRequest): container "recipes-nginx" in pod "recipes-86df8b96cd-sgfsj" is waiting to start: PodInitializing

dietpi@ruxcluster01:~/recipes/docs/install/k8s$ kubectl get pods -o jsonpath="{.items[*].spec['initContainers', 'containers'][*].image}" |tr -s '[[:space:]]' '\n' |sort |uniq -c
      2 cloudflare/cloudflared:latest
      1 docker.io/bitnami/minideb:stretch
      1 docker.io/bitnami/postgresql:11.5.0-debian-9-r60
      1 docker.io/bitnami/postgresql:15.4.0-debian-11-r45
      1 docker.io/gotson/komga:latest
      2 ghcr.io/goauthentik/server:2024.6.3
      1 nginx:latest
      1 registry-1.docker.io/bitnami/redis:7.2.3-debian-11-r2
      2 vabene1111/recipes
```

**Comment by sruckh** [comment]
after getting the database pod working (by changing tag to latest), the following error is from init-chmod-data container:

Updating database
Traceback (most recent call last):
  File "/opt/recipes/venv/lib/python3.12/site-packages/django/db/backends/base/base.py", line 289, in ensure_connection
    self.connect()
  File "/opt/recipes/venv/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/recipes/venv/lib/python3.12/site-packages/django/db/backends/base/base.py", line 270, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/recipes/venv/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/recipes/venv/lib/python3.12/site-packages/django/db/backends/postgresql/base.py", line 275, in get_new_connection
    connection = self.Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/recipes/venv/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "recipes-postgresql" to address: Name does not resolve
