### ISSUE TITLE
Shopping list export to clipboard or Mark Down

### ISSUE THREAD

**Issue by CodePrivateer** [TandoorRecipes/recipes#3467]
### Tandoor Version

1.5.25

### Setup

Others (please state below)

### Reverse Proxy

No reverse proxy

### Other

Self Hosted in Proxmox LXC installed with community-scripts.github.io

### Bug description

When you click the shopping list option "Copy to clipboard" or "Copy as Markdown table" nothing happens and the browser console displays this error:
chunk-vendors.js:347 TypeError: Cannot read properties of undefined (reading 'writeText')
    at s.clipboard (shopping_list_view.js:1:89797)
    at Or (chunk-vendors.js:347:29985)
    at HTMLAnchorElement.n (chunk-vendors.js:347:11763)
    at o._wrapper (chunk-vendors.js:347:68081)
kr @ chunk-vendors.js:347
wr @ chunk-vendors.js:347
yr @ chunk-vendors.js:347
Or @ chunk-vendors.js:347
n @ chunk-vendors.js:347
o._wrapper @ chunk-vendors.js:347

Tested in Edge and Chrome, same problem and error, attached the chrome browser console log.

### Relevant logs

```shell
shopping/#:1 The Cross-Origin-Opener-Policy header has been ignored, because the URL's origin was untrustworthy. It was defined either in the final response or a redirect. Please deliver the response using the HTTPS protocol. You can also use the 'localhost' origin instead. See https://www.w3.org/TR/powerful-features/#potentially-trustworthy-origin and https://html.spec.whatwg.org/#the-cross-origin-opener-policy-header.
manifest.json:1 Manifest: Enctype should be set to either application/x-www-form-urlencoded or multipart/form-data. It currently defaults to application/x-www-form-urlencoded
shopping_list_view.js:1 started loading locale messages
shopping_list_view.js:1 finished loading messages in  6  ms
shopping_list_view.js:1 loaded local user settings age 2347.975 
shopping_list_view.js:1 refreshing user settings from API
shopping_list_view.js:1 loaded local user settings age 2347.977 
shopping_list_view.js:1 refreshing user settings from API
shopping/:444 service worker not in navigator
(anonymous) @ shopping/:444
load
(anonymous) @ shopping/:436
chunk-vendors.js:347 TypeError: Cannot read properties of undefined (reading 'writeText')
    at s.clipboard (shopping_list_view.js:1:89797)
    at Or (chunk-vendors.js:347:29985)
    at HTMLAnchorElement.n (chunk-vendors.js:347:11763)
    at o._wrapper (chunk-vendors.js:347:68081)
kr @ chunk-vendors.js:347
wr @ chunk-vendors.js:347
yr @ chunk-vendors.js:347
Or @ chunk-vendors.js:347
n @ chunk-vendors.js:347
o._wrapper @ chunk-vendors.js:347
shopping_list_view.js:1 running autosync
shopping_list_view.js:1 running autosync
shopping_list_view.js:1 running autosync
shopping_list_view.js:1 running autosync
shopping_list_view.js:1 running autosync
shopping_list_view.js:1 running autosync
shopping_list_view.js:1 running autosync
shopping_list_view.js:1 running autosync
shopping_list_view.js:1 running autosync
shopping_list_view.js:1 running autosync
shopping_list_view.js:1 running autosync
shopping_list_view.js:1 running autosync
shopping_list_view.js:1 running autosync
shopping_list_view.js:1 running autosync
shopping_list_view.js:1 running autosync
shopping_list_view.js:1 running autosync
shopping_list_view.js:1 running autosync
chunk-vendors.js:347 TypeError: Cannot read properties of undefined (reading 'writeText')
    at s.clipboard (shopping_list_view.js:1:89797)
    at Or (chunk-vendors.js:347:29985)
    at HTMLAnchorElement.n (chunk-vendors.js:347:11763)
    at o._wrapper (chunk-vendors.js:347:68081)
kr @ chunk-vendors.js:347
wr @ chunk-vendors.js:347
yr @ chunk-vendors.js:347
Or @ chunk-vendors.js:347
n @ chunk-vendors.js:347
o._wrapper @ chunk-vendors.js:347
shopping_list_view.js:1 running autosync
shopping_list_view.js:1 running autosync
shopping_list_view.js:1 running autosync
shopping_list_view.js:1 running autosync
shopping_list_view.js:1 running autosync
shopping_list_view.js:1 running autosync
shopping_list_view.js:1 running autosync
shopping_list_view.js:1 running autosync
shopping_list_view.js:1 running autosync
shopping_list_view.js:1 running autosync
shopping_list_view.js:1 running autosync
shopping_list_view.js:1 running autosync
shopping_list_view.js:1 running autosync
shopping_list_view.js:1 running autosync
```

**Comment by smilerz** [comment]
Are you connecting via https?

**Comment by CodePrivateer** [comment]
> Are you connecting via https?

no, the server is in my private network.

**Comment by smilerz** [comment]
Browsers don't support access to the clipboard over http.
